### ISSUE TITLE
Extend crag node with fields for seasonal closures

### ISSUE THREAD

**Issue by theSCRAG** [theCrag/website#1247]
Today:
You could only add a seasonal closures as a textual description to field "Access Issues"

Improvement:
add two date fields ("from" and "til") below field "Access Issues".

Then we have the possibilty to work with these datas in future:
- grey out closed crags or add "forbidden sign"-icon to crag and overviews.
- get list of closed crags over API
  and so on

Background:
In some areas are many seasonal closures.
e.g. in Frankenjura ( http://www.ig-klettern.com/natur/sperrungen.php ) the seasonal closures change weekly.

Sample:
Access Issues ["bird protection"]
From: ["01.02.2014"] til: ["30.07.2014"]

**Comment by lordyavin** [comment]
+1

**Comment by brendanheywood** [comment]
The new warning system can be used for temporary closures and the warning can then be dismissed when season is over. The next year the same warning could be reopened again with 1 click to save some typing.

Bonus points we can add fields to the warnings to accept an expiry date, which we did discuss but pushed back out of MVP.

**Comment by Mdemaillard** [comment]
reopened under #3422

New feature to set a date range for (scheduled) crag closures. In Germany we have a lot of scheduled closures due to nature conservation. It would be neat to just enter the official dates once and the closed tag is set and removed automatically.

So if someone wants to log an ascent from the past it has to be outside of the date range of the closure.

Originally posted by @lordyavin in #3421 (comment)

**Comment by scd** [comment]
Realistically I don't think we will implement predefined dates in time for helping the current series of closures.

There are quite a few components required to put dates in closure field because it is currently implemented with a tag. Potentially it is a complet re-implementation which touches a lot of code and testing and data migration. Alternatively there is a trigger to remove the tag, so existing code will continue to work, but we have to manage a layer for automatically removing tags.

Maybe we should think differently and add an alert date to a warning.

**Comment by rouletout** [comment]
This is covered by the following functionality and processes:

1) Warning system to display the closures
2) Automated (opr if small manual) updates from advocacy groups that take the responsibility to "own the data an dates"

Closing

**Comment by lordyavin** [comment]
Don't understand point 2

**Comment by rouletout** [comment]
It means that Advocacy groups that take the responsibility to maintain the data can do that manually or via API.

**Comment by lordyavin** [comment]
I see, are there any prepared snippets for common CMS?
