### ISSUE TITLE
Rethink forums in regions, states and countries

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1365]
Currently can't post above a TLC but there is obvious desire for this. Need to think about how and who would get notified, and also permissions for who can start a new post (small karma).

**Comment by scd** [comment]
I have made a live fix here as so many of our forums are empty.

Forums now have three modes 'direct' node discussions, 'descendants' node discussions and 'all' = descendants+ancesters. Before we just had the descendants so the region forums looked busy, but the route forums looked empty.

There are some tab selections to choose the mode. Above TLC it defaults to 'all' and below tlc it defaults to 'all' if there is nothing in the 'desendants' forum, otherwise it defaults to decendants.

This means that all forums now have content.

It was a fairly simple fix to the sql statement, by adding a union. There were some minor fixes in some other files.

 - [ ] Something that I am concerned about is how to identify duplicate content for google indexing.

**Comment by brendanheywood** [comment]
This is great! :)

I think the filter toggle is probably fairly low value, most people probably won't really even see it or know what it means. Maybe we could make it a drop down with more verbose explicit options like:

* Show only discussion add to Australia
* Show all discussions inside Australia
* Show all discussions affecting Australia

Those words are crap but something along those lines including the node name. If it is a route you would only get 2 options. 

Something like the github watch menu:

![image](https://cloud.githubusercontent.com/assets/187449/15148324/09a93e76-1708-11e6-864e-f591087c30ce.png)

**Comment by scd** [comment]
The main push for this was to get some content in. I would not have even have bothered with the different settings, however it is pretty easy for local crag discussions to be drowned out by world and region discussions.

Modelling improvements off github I think is appropriate.

@brendanheywood what do you think about duplicate content on these pages. Is there a way to tell google to ignore components of a page? Should we not index a page if there is no direct content? Do we not bother?

**Comment by brendanheywood** [comment]
One thing I have noticed recently is that there are now lots of new discussions being started at the world node. I'd like to squash this ASAP as it is spamming a lot of people will see stuff unrelated to them and it will turn them off. So gotta figure out why and how people are posting there (did you change permissions as well as the stuff above?) and gently nudging them into a more appropriate node first.

Stuff like this:
http://www.thecrag.com/discussion/852470907/looking-for-climbing-partners-in-qingdao-and-hebei
http://www.thecrag.com/discussion/847541061/partner-wanted

etc should all be at the crag they belong too

Re duplicate content I'm not worried at all, google is pretty good at knowing which pages are index pages.

This may simply be a natural side effect of everyone seeing more stuff as usage grows, or maybe just a statistical quirk now. But still want to discourage it as much as possible

**Comment by scd** [comment]
I did not change anything that would effect this. if somebody posts at
world level it will miss most people's dashboard. We get it because we have
manually subscribed to world level.

**Comment by brendanheywood** [comment]
Ok so I think the recent influx was purely down to chance, still want to fix it but it can wait.

On the other hand you mentioned that people will not be shown world or country level discussions in the dashboard, they should see these: the logic used in the forum pages should be identical to that in the forum pages.

**Comment by scd** [comment]
Let's hold off on the discussion of what the dashboard should and should not do until we have time and energy to work out what it means for people to be 'watching' a crag. There are a couple of related concepts which need to be discussed together
 - [ ] watching a crag
 - [ ] what is shown in the dashboard
 - [ ] restrictions on posting at world/country level

I was happy to make the forums change at cliff level because it looked pretty poor having empty forums. My guess is that we will end up agreeing and aligning the dashboard with the forum logic.

**Comment by scd** [comment]
@brendanheywood what remains to be done in this issue. I get the feeling it is just a karma test for starting a discussion. So a new user cannot start a world discussion.

**Comment by brendanheywood** [comment]
I think leave this open for now, I think once the dust has settled this one will be just some language cleanup

**Comment by DaneEvans** [comment]
This seems to be an issue again at the moment, I'm not sure if it's due to changes, or just a few more users prepared to use the world forum to post a help ticket. 

I think the higher level ones need to have more gates than just a low karma threshold. 

Maybe a page that has a large warning that you are targeting a large audience, and that unless it has wide appeal it will be removed, and offers you a list of more suitable alternatives 
- help pages
- message support
- a country/state level forum 

I can't think of a genuine use case for a 'world' post apart from admin messages.

**Comment by Mdemaillard** [comment]
one thing that for sure leads to random posts in World level, is that while navigating it is easy to land at World even when you don't want to. That is actually not only for forum, but search, list view and the like.
Not really sure how but i end up regularly searching my way back down to country/crag level.

**Comment by Mdemaillard** [comment]
splitting the last issue and closing this rambling one.
