### ISSUE TITLE
meta description in index

### ISSUE THREAD

**Issue by scd** [theCrag/website#1416]
We don't meta description for our index pages. As far as I can tell this property does not get used for SEO ranking, but does get used when displaying a page in Google.

Is there any reason why we don't have meta description. It should be about 155 characters, have key search terms, unique and promote us.

Maybe something like

"Free online trad climbing guide for Arapiles (Djurite) Australia. Information sourced from theCrag.com, the world's biggest collaborative climbing database"

Adjust for world, regions, cliffs, & routes.

**Comment by brendanheywood** [comment]
Bit the bullet and added the redundant description. My reasoning is that after gzip the two strings will get conflated anyway so there is little downside, and the meta tag is a much older spec and so will have better support in other / older robots. And then had the idea that we could merge the two tags and it turns out you can, so I've done that instead:

http://stackoverflow.com/questions/6203984/combing-the-meta-description-and-open-graph-protocol-description-into-one-tag
