### ISSUE TITLE
Disable Cite Publication functionality

### ISSUE THREAD

**Issue by scd** [theCrag/website#1447]
Generally people are not interested in providing this level of information and it is pretty useless unless you do the whole guidebook.

**Comment by matozoid** [comment]
I'm mildly interested in having this feature user-accessible. Here is an example of what I'm thinking of: https://nl.belclimb.be/topt_list.asp

**Comment by georg-d** [comment]
> I don't think referencing a particular page in a guide book has much value at all

If it's not causing ongoing development efforts, I'd prefer to keep it – whether in normal edit UI or "power edit" UI – because it sometimes eases & speeds up to find a certain crag: Several guidebooks are lacking proper alphabetical index and/or map, even some books with hundreds of pages, e.g. "Finale Climbing" by Marco Tomassini of 5/2017 (he knows about it and wants to improve in next edition expected for 2023+). Some guidebooks group crags by valley, others by mountain, others by administrative or political regions. Moreover, all these features as well as the crags & sectors may have different names in different languages – some even in the same language – but many guide books just mention one name. All of that can make it a hard time to find which guide contains certain crags of interest. For example, I have 4 guide books covering the region around Lago Maggiore and I either need to consult a map to understand the structure of the table of content, or I need to read the names of _all the many crags_ (and to know the synonyms 🙄).

**Comment by georg-d** [comment]
> Melwin, as a user, would you be prepared to do the extra work of adding page numbers to a routes? 

I'd definitely do on hierachy level of crags. Sometimes, I'd do for sectors or routes – especially for guide books that do "cherry pick" only some few sectors/routes of one crag, but do this for many crags.

> Guidebooks tend to have a lifetime of about 5 years before either their print run ends or a new version is made, so the data entry would have a limited lifetime value.

While I agree the page reference's value declines over time, I don't consider it is completely lost after 5 years. For example,

- if no new version of the guide book is made. For example, "Klettern im Dreiländereck" by Frick has been plain re-printed several times since 1998 and is still sold in 2022 (so 24 years later!) as no other guide covers the same region.
- if climbers typically do not buy each new version, e.g. because it's about a holiday region you're visiting only every vew years and you do not want to buy each time a book for 40€.
- if you want to look up information in an older guide, e.g. personal notes, to find out what changed

**Comment by rouletout** [comment]
Guidebooks are now linked (since 101) in the Plan your Trip section - closing
