### ISSUE TITLE
Recent crags dropdown doesn't appear inside process pages

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1498]
* [ ] no recent crags
* [x] no list of help articles
* [x] nav context is missing

**Comment by Mdemaillard** [comment]
what is defined as process apges ?
- merge, relocate, edit photo, that kind of things ?
- bulk edit route ? edit area ?

**Comment by Mdemaillard** [comment]
The Top page header including help articles is available in all process pages listed above. -> box ticked.

Recent crag drop-down (from Index): it is NOT present, while Favorite is. 
Honnestly i dont see the point except for standardizing. Because while in a process page, you should not navigate, which is why the full navigation pannel is not visible either. If you want to navigate, cancelling the process by going back to index is one click away.

**Comment by rouletout** [comment]
Nio comments since @Mdemaillard write up which seems fine to me, closing
