### ISSUE TITLE
A glossary / climbing dictionary / clarification of climbing terms for non English

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#1633]
I have read the help pages for tick types and gear style several times and I think that I understand most of the stuff. But still there are some strange difference in using the terms. E.g. in Germany we don't use the term "trad". I don't know why but for some reasons people talk about "clean" climbing because there are no pre-set protections. Another example is "alpine". We use alpine always if we do a multi-pitch route in the Alps or in high altitude regions. For us this indicates that a route is not protected as a sport climb and you have to bring your trad rack with. But there are so called "plaisir" routes which are well protected and you don't need additional gear beyond quick draws and a rope. I think "plaisir" is a term introduced by the Swiss. In Germany some call such routes "alpine sport routes".

Of course this terms depend on history, tradition and the local language. I would love to see that theCrag grows and this means we need a system that is understood by every member of the international climbing community. We need good and clear documentation and maybe a vocabulary that helps non English climbers to write good descriptions with the correct terms and to use the website.

BTW: Please excuse my English ;-)

**Comment by brendanheywood** [comment]
Is this something we can close off now that the lang packs are getting sorted? Or is there still changes to the english we should also make?

**Comment by scd** [comment]
I think we should keep this open until we have done the ticking release. This is because the help articles are not translated. However we may decide that some help articles (eg tick types, and grades) are more than just articles and should be translated.

**Comment by brendanheywood** [comment]
Can we close this after this release?

**Comment by lordyavin** [comment]
Are the help pages going to be translated?

**Comment by scd** [comment]
Yes we are in the process of doing this. We are about half way through. Our general rule is that when we touch a help page we translate it. There are dozens of help pages and each one takes a fair bit of work.

**Comment by lordyavin** [comment]
Let me know if I can help with translations. The wife of [Wile E Coyote](https://www.thecrag.com/climber/wileecoyote) is a translator and his English/German is very well too. Maybe they can help to review the translations.

**Comment by rouletout** [comment]
Hi Kai, ich mach grad auf Deutsch weiter - danke für dein Angebot. Die Ticking und Logbuch Seiten sidn parat - aber es gibt immer Neues, jetzt gerade einen "Beginner Artikel" - wärst du bereit, bei der Übersetzung zu helfen? Das wäre super!! Am besten wir machen via Email weiter..., Danke und LG, Ulf

**Comment by lordyavin** [comment]
Is this issue used as a reminder to translate the help article? Should we add all open translation as a todo list?

**Comment by rouletout** [comment]
I wouldn't create issues for missing translations - we manage them separately as the number of languages and keys makes that a tricky task. If you are up for new "bigger" translations (articles), please contact me first as we will re-work most of them before translation.

**Comment by lordyavin** [comment]
Then this issue is somehow obsolete because we are translating and localizing the site.

**Comment by brendanheywood** [comment]
The way I’ve interpreted this issue is to have a dictionary concept on the site. And both the words and their definitions could be both translated and also have a location scope. It’s much more broad than just tick types or concept specific to thecrag. 

Eg ‘carrot’ would be English and probably only have a scope of Australia. Eg an American could see it but know it’s location specific 

Arete is a French word but used in English etc. I’d want this to be a proper data model and be able to be collarotively editable. Eg we might only allow coordinators to add terms

**Comment by quaestor** [comment]
I like the idea of the glossary. It would be an amazing addition to the markup if terms present in the dictionary were also coloured and their description shown when hovering over them.

**Comment by scd** [comment]
+1

**Comment by brendanheywood** [comment]
+1 from support

**Comment by Mdemaillard** [comment]
Merging #355 into this  - from @MelwinQ

Just an idea for the far far away day when you run out of inspiration:
When climbing abroad, understanding locals or guidebooks is often not easy. Even if you speak the language, because of the climbing lingo most words you won't find in ordinary dictionaries. It would be nice to have a dictionary for the most important climbing terms for the place you go to. It could be an optionaly component for PDF-guides, or someday even enable automatic translations of route descriptions (far fetched, I now).
I found two such lists (selected languages, no advanced functionality) on the web:
http://www-dft.ts.infn.it/~esmargia/mountain/climbing_dict.html
http://www.gdargaud.net/Climbing/Lex_En.html
Perhaps at least one of them could even be convinced to donate the initial stock of words, so the dictionary doesn't need to start from scratch.
As always, thanks for what you have done so far,
Melwin

 structure data terms
 random extra trivia term data model
 have alpha chooser (just normal right side menu ToC?) (can we automate this, what about korean / chinese / japanese?)
 have language swapper in articles
 ability to show translations from any language A to B
https://stackoverflow.com/questions/3891556/how-do-you-sort-cjk-asian-characters-in-perl-or-with-any-other-programming-la

https://e2f.com/4796/

**Comment by rouletout** [comment]
+1 from reply to welcome message - help on abbreviations like RB, BB

**Comment by Mdemaillard** [comment]
+1 from discussion, Definition of "Point Types" in Topos (Carrot Bolt, Lower offer, Belay, Fixed Belay, Hanging, Semi hanging...)

**Comment by georg-d** [comment]
+1 for such a climbing dictionary, suggesting to add descriptions/photos/sketches where more helpful than plain translations, and willing to help. My mother tongue is German and my English is quite OK but I am not fluent with "climbing English". I've an IT background and could also help with the data model.

**Comment by rouletout** [comment]
Glossary is implemented in v1 - closing

**Comment by lordyavin** [comment]
Wow, after 7 years we finally got it. Thanks @rouletout. Who assembled it? :thumbsup:

**Comment by rouletout** [comment]
This was a joint effort with input from partners...

**Comment by georg-d** [comment]
You can find the glossary at https://www.thecrag.com/en/article/glossary
