### ISSUE TITLE
Use Select2 for tokenised / tagging style input for 'with' 'invite' 'photographer' 'climber' etc

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1764]
Rough todo list, split from #831:

* [x] check latest versions and match dependencies to our version of bootstrap http://ivaynberg.github.io/select2/
* [x] check whether we keep the bundled css or swap to https://fk.github.io/select2-bootstrap-css/3.5.1.html
* [x] check if we are actually using Select2 elsewhere, I think on the anon homepage for crag search, check it still works
* [x] get the ajax lookup working, should be same as at.js
* [x] get the templating working, should be similar to at.js
* [x] for fields that allow free text as well as @ links turn on 'Auto Tokenization' but only tokenise on comma, not on default whitespace http://ivaynberg.github.io/select2/#tags
* [x] in the UI people should see each tag as "Brendan Heywood" - I think worth showing the free text as different in some way to the linked ones, maybe show a mini avatar to make it really clear they are different
* [x] under the hood the hidden field will contain something like "My sister,@scd,@cgome,and my mum" which the backend then parses and links as needed. There could be multiple linked or free text components intermingled
* [x] all editing should be roundtrip, so pass the exact same string as above back into ascent editing form, photo editing form

**Comment by scd** [comment]
@brendanheywood I just wanted to run by an extension to the logic you proposed to minimise network traffic. 
  * as discussed if we have to go to the network we get lot's of results - say 50, even though only 10 are displayed. 
  * as soon as the page is open a default zero length search goes across the network and pre loaded into the cache, so that as soon as focus goes onto the field the results are already available.
  * when the user types in, check to see if that search is already cached - if yes process and we are done
  * then check cache for shorter search terms. When a shorter search term cache is found check the length of stored results. 
  * If cached result is less than 50 then we know another network search is redundant so just use the cache results from the shorter search term.
  * If there are 50 items in the shorter search term cache then we need to go back to the network to refine the search. So far this is what we discussed and is all pretty clear. The next step is the enhancement.
  * If we have found 50 items in a shorter search term cache we do BOTH process the cache and do a refined network search. Because we are prioritizing our search it is highly likely that the person somebody is looking for is already cached on our list - so process that immediately. In the meantime we also fire of a refined network search and process that when the result comes back. 

I have implemented this algorithm. I am in two minds about the last step. I think it could be good as it makes if feel fast, but it is possibly a bit jumpy. Select2 does a pretty good job though. If I have already tabbed focus then this will be maintained when the new list pops up.

**Comment by brendanheywood** [comment]
Yes this last step should be fine, you can call the query callback multiple times. Only hitch is if select borks the selection if you down arrow too fast, need to test. In chrome you can now throttle the network right back and simulate high latency easier

![image](https://cloud.githubusercontent.com/assets/187449/5591456/8fb1ea6a-91b0-11e4-8a2b-6c2e6870b4a4.png)

Not sure how you've implemented but promises are awesome at making this all a lot easier and handle the 3 states 'not loaded, loading, loaded' easier, something roughly like:

```
if (!cache[suffix]){ cache[suffix] = $.getJSON( "search?q="+suffix);

cache[suffix].done( function(){
  query.callback( transformResults( cache[suffix] ) );
})
```

http://api.jquery.com/category/deferred-object/

**Comment by brendanheywood** [comment]
Other stuff I forgot to send before:

> 3.5
Use the latest, (you probably already have)

> no min.js file in the repo
Can you make the static generator honour symlinks? then just sym link from the css dir into the submodule and it should all just work


> The example had two fields - input and text field
The textarea at the bottom is purely for demo purposes. You render a normal html input, then in JS you turn it into a hidden field and then call select2 on it.

**Comment by scd** [comment]
The promise stuff looks pretty cool. For my own benefit here is a reasonable tuturial article on how it works with posts:

http://joseoncode.com/2011/09/26/a-walkthrough-jquery-deferred-and-promise/

It seems to me we could rewrite a lot of our javascript using this.

**Comment by brendanheywood** [comment]
Sorry I've been a bit absent, working on little sleep and packing to go away on a mission now. reading and writing is still something I can mostly do with nora in my lap :)

bit more background reading for you if your bored
http://www.html5rocks.com/en/tutorials/es6/promises/

**Comment by scd** [comment]
I have now rewritten with promises. It actually solved a loading issue if a cache result was already loaded. It also solves the failed to load case as well - ie we don't keep on trying.

There was one minor complexity with preloading as we did not want to trigger the filter in this case, but did want to trigger it if the field gained focus in the meantime.

**Comment by brendanheywood** [comment]
So anyway I've added groupings to the results:

![image](https://cloud.githubusercontent.com/assets/187449/5591740/e67e05e6-91d7-11e4-8238-7d01e9a8adda.png)

I got a bit burnt digging down and debugging stuff. It turned out that I was getting a bunch of weird results because the api wasn't authenticated, even though I was logged into the site. I think it is this bug: #1419. In this case I think the api should not return anything if asked for things like 'following' and you're not authenticated.

Some of below maybe related to above:

I'm a bit confused by some of the api calls, eg this:

https://dev.thecrag.com/api/lookup/climber?page-size=250&mode=karma,follow,login&tlc=11772109&search=sc

I interpret this as 'give me anyone I follow, who has karma in 11772109 or who has a login', but it only returns people I follow??

Where as this, same as above but with 'sc' returns follows and random users:
https://dev.thecrag.com/api/lookup/climber?page-size=5&mode=karma,follow,login&tlc=11772109&search=sc

I I target someone who has karma, but I don't follow, then they appear in this list:

https://dev.thecrag.com/api/lookup/climber?page-size=250&mode=karma,follow,login&tlc=11772109&search=wog

But not in this list when they should:

https://dev.thecrag.com/api/lookup/climber?page-size=250&mode=karma,follow&tlc=11772109&search=wog

**Comment by brendanheywood** [comment]
Behind the scenes I've added this to the api:

![image](https://cloud.githubusercontent.com/assets/187449/5591744/ab1cc1c6-91d8-11e4-880f-19188f015ec4.png)

I've had to rearrange the order of calls in CustomSQL/Climber so that the priority is for stuff like 'You follow' over 'Local karma' over 'All users'. The group names and group order are completely arbitrary so we can keep on adding more depending on the context, ie later I'd want to add a 'Recent partners' which lists people I've recently climbed with.

**Comment by brendanheywood** [comment]
Cleaned up a few more style issue. ok I'm outa here til the weekend

**Comment by scd** [comment]
you beat me to it :). I will look into the API strangeness and also add a 'Who you have mentioned' group. Have a great weekend.

BTW, I fixed up some cloning issues for adding multiple shots.

**Comment by scd** [comment]
hmmm, this is starting to look good. I have fixed the api bugs and added a mention mode, which has a priority one after follow mode. This means if you have mentioned somebody recently it is easy to mention them again.

**Comment by scd** [comment]
@brendanheywood a couple of questions:

 - [ ] I have added select2 to editing route history fields. I see the arguments to do so exactly the same as for the with field on ascents. Do you agree?
 - [ ] Having a second '&' tokeniser has a logical floor for round trip editing. You cannot save the '&' so if a field already has an '&' then it cannot be saved back with that '&'. I think we should just tokenise on commas (','). 

A couple of other notes on implementation. I have updated our javascript so that the cache is global rather specific to an element. This means the cache is share between fields.

select2 is fairly intensive and lot's of declarations in route history in bulk edit started to cause javascript processing warning messages on one of my browsers. I have reduced the bulk edit default page size from 20 to 15 and this problem goes away.

**Comment by scd** [comment]
I have decided to take out the '&' tokeniser due to the round trip editing issue mentioned above. Please feel free to convince me otherwise.

There is another round trip edit problem and bug I have to work through. If there is a second name already stored in this field (eg 'Simon Dale, Campbell Gome' ) then editing, not touching and saving is causing the second name to duplicate. I think it is due to the space after the comma, but I have not had time to test this yet. Stay tuned for confirmation of the cause. If it is the cause (which I think is highly likely) then I don't want to save the updated field unless there is a change which is more than a space been remove after the comma.

**Comment by brendanheywood** [comment]
> I have added select2 to editing route history fields. I see the arguments to do so exactly the same as for the with field on ascents. Do you agree?

Yup

> select2 is fairly intensive

This may be because you are calling it once for each input, try just calling it once for the lot. Another trick is just set a small delay between the processing of each on so it's not constantly hogging the main UI js process.

> I think it is due to the space after the comma,

We should strip this out regardless, so internally no comma has a space after it. We can tidy it up in read only places in the template

**Comment by brendanheywood** [comment]
> tokenise &

I don't really get what the problem is, sounds like something isn't being escaped right so we could fix it? I'm not too fussed anyway. If we did this & would get converted to , after saving which is fine.

**Comment by scd** [comment]
I have fixed the round trip editing issue and I now tokenise on ',', '&' and 'and'. Actually I pre parse on those three and just tokenise on the first two. If the user types in and & it is consumed in exactly the same way as a comma. The thing is stored as a comma separated list with no '&'.

For historical data I parse before I display and always display as 'First Name, Second Name & Third Name'.

We only save an update if there is a tangible change to the field. This stops historical records being overwritten with the space after the comma removed. 

I think this solves the problem I alluded to in the last two comments. It is just a bit more in depth then I first appreciated.

**Comment by brendanheywood** [comment]
I experimented with 'and' but it barfs when typing names like Andrew so
that's a show stopper.

Does this logic only apply when doing and edit or are you a migration?

I've also seen some fringe data like 'Mary & David Smith, Jim blogs and Tim
jones'

It's not ideal in this case to convert the & to , but I don't think common
enough to stress about.

Sent from my iPhone

On 03/01/2015, at 8:03 PM, Simon Dale <notifications@github.com> wrote:

I have fixed the round trip editing issue and I now tokenise on ',', '&'
and 'and'. Actually I pre parse on those three and just tokenise on the
first two. If the user types in and & it is consumed in exactly the same
way as a comma. The thing is stored as a comma separated list with no '&'.

For historical data I parse before I display and always display as 'First
Name, Second Name & Third Name'.

We only save an update if there is a tangible change to the field. This
stops historical records being overwritten with the space after the comma
removed.

I think this solves the problem I alluded to in the last two comments. It
is just a bit more in depth then I first appreciated.

—
Reply to this email directly or view it on GitHub
<https://github.com/theCrag/website/issues/1764#issuecomment-68588184>.

**Comment by scd** [comment]
I am pre parsing with ' and ' - spaces around the and.

 > I've also seen some fringe data like 'Mary & David Smith, Jim blogs and Tim jones'

Too fringe, and not a show stopper because you can still type in the full names.

 >  Does this logic only apply when doing and edit or are you a migration?

I thought about migration, but want to make sure we are happy with this methodology. If so we should consider migrating the data. In the meantime it is preparsed.

> This may be because you are calling it once for each input, try just calling it once for the lot. 

How would that work? select2 adds a whole lot of html and events. I have tried cloning the html when adding the 'extra shot' in the ascent logging page and the events are still tied to the original input. I am sure it is possible, but looks a bit like re-inventing the wheel.

> Another trick is just set a small delay between the processing of each on so it's not constantly hogging the main UI js process.

I think this will work. It is only a problem on bulk edit.

BTW, I thought you were away for the weekend. You got some Internet time?

**Comment by brendanheywood** [comment]
> I am pre parsing with ' and ' - spaces around the and.

We might be talking about slightly different things. I was talking about the tokeniser option in select2, I think you're talking about the regex when parsing the data to re-edit. Just looked at the latest code and all looks good.

I am back home now, been camping for 2 nights and had a mega mission yesterday, left camp at 6:20 and back at the car at midnight. I was so tired today I feel asleep with nora on the floor with my eyes open. Doing my ticks now...

>  I have tried cloning the html

Yeah it is dependant on how each jquery plugin is written, but sounds like leave as is and add the small delay workaround. The other place it could show up is batch ticking. It will definitely show up when we do bulk history editor #558

**Comment by scd** [comment]
> The other place it could show up is batch ticking

I think 10+ batch ticks on separate routes will happen that much. The form still works anyway, just maybe has an error message.

Also I got the add shot stuff working, and that is not a problem because shots are added one at a time. So adding 10 ascents of the same route is fine.

**Comment by scd** [comment]
adding an async timer function for each select2 element solved the warning message problem. After a bit of research I now know that message pops up for lots of synchronous javascript instructions. I used 10ms timer between calls.

**Comment by scd** [comment]
this is done. Any further tasks should be written up separately
