### ISSUE TITLE
FA History potential for extra info lost when converting over

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1797]
Some real examples:

![image](https://cloud.githubusercontent.com/assets/187449/5622068/344d4400-9591-11e4-8682-5e985f4c34c0.png)

![image](https://cloud.githubusercontent.com/assets/187449/5622105/cfc30758-9591-11e4-9fdd-81eaa0378011.png)

![image](https://cloud.githubusercontent.com/assets/187449/5622109/dbfe04e6-9591-11e4-8623-3def30fa6697.png)

![image](https://cloud.githubusercontent.com/assets/187449/5622113/edbd9a84-9591-11e4-8418-2e9501b7a091.png)

![image](https://cloud.githubusercontent.com/assets/187449/5622118/00271efc-9592-11e4-8e39-494e86719c3a.png)

![image](https://cloud.githubusercontent.com/assets/187449/5622121/09ca4f1a-9592-11e4-8833-024e288496ab.png)

![image](https://cloud.githubusercontent.com/assets/187449/5622125/19463350-9592-11e4-90d7-464f2c182bb7.png)

This is really common, all of these except for the first are from the top 2 pages of routes in arapiles.

You can't just add the extra text as a new entry or you get '&' inserted where you don't want it.

This was very briefly mentioned when you asked before should FA be a select2 or should it be an at.js field. Honestly I prefer the UX of Select2, but to properly capture all this extra info it probably needs to be an at.js field. So are we comfortable losing all this extra information? I'm not super comfortable losing historical information, and there is a part of me that isn't even comfortable losing the name of the person as it was added at the time they did the route, which is why there is so much business logic in #558. I'm quite torn on this one

**Comment by scd** [comment]
The UX for select2 is far superior when we really want people to link actual accounts. I think the adoption will be a lot slower usint at.js.

Here is some additional thoughts:
 - [ ] where there is an improvement then this is a second entry so that is one use case solved
 - [ ] we have full text field for extended descriptions of what is going on.
 - [ ] we could adopt a standard of any tag in brackets (eg '(solo)') to have the previous comma dropped in display. In otherwords where select2 produces this output "@scd,(solo)" we will present it as "Simon Dale (solo)".

**Comment by brendanheywood** [comment]
I like the last item where we just drop the &. The full text ascent notes seems good but you can't even edit it from the bulk edit, only from single edit (which also is a bug). and that field doesn't even get shown anywhere useful so is pretty pointless at the moment.

So yeah lets go with the some logic that removes the '&' if there is any punctuation at the start of the next tag, - : ; ( ) [ ]

The only case above which isn't covered by this seems to be this one:

![image](https://cloud.githubusercontent.com/assets/187449/5622121/09ca4f1a-9592-11e4-8833-024e288496ab.png)

But in this case it's probably better off being a whole extra FA item potentially with it's own date, so that's fine.

**Comment by scd** [comment]
ok this is fixed in repo and hot fixed.

Also the ascents facet page was not linking to the routeHistory minor template so I fixed that to.

I am happy with this outcome. BTW your FA changes look awesome in prod, I noticed them yesterday. Have you had a look at 

http://www.thecrag.com/climber/monty/mentions

Maybe let stephen know about his fa mentions when you are done
