### ISSUE TITLE
Open up more beta markdown fields on region nodes and other types (crag area cliff region)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1807]
Eg I've been trying to tidy up at least 1 or 2 nodes from the email list each day and came across this one:

http://www.thecrag.com/climbing/brazil/minas-gerais

This is a crag but should be a region, but if I try to change to a region I will lose 2 fields. But both of those fields make perfect sense for a region. The summary we've wanted to add for a while, see #1169, and the approach is in this case is much more like a lonely planet style 'how to get there'.

Related to another issue to always show descriptions if they exist regardless of type to account for ones that have changed but I can't seem to find that issue.

**Ideas**
* [ ] if a field is present always show it, even if the node type doesn't have it
* [ ] allow any beta field at any node, but just have the default ones in place with a + button to add more
* [ ] the UI for this should mesh well with adding both multi publisher content, and also multi lingual content

**Comment by brendanheywood** [comment]
Approach at the moment inherits down, but is also overridable, so we can have 'how to get to the crag' and then 'how to get to the cliff' etc, so I don't see this as an issue if we add the extra 'how do we get to the region' above these

**Comment by brendanheywood** [comment]
Probably the best example we will ever get:

http://www.thecrag.com/climbing/germany/sachsische-schweiz

This is a 'crag' but has 18,000 routes BUT has *ever* beta field filled out with heaps of detail.

**Comment by brendanheywood** [comment]
Ok I've systematically gone through all the fields & node types and here are my thoughts on what fields they should have which they don't, and also what they should inherit that they currently don't.

* [ ] Access issues - Add to region and inherit
* [ ] Approach - Add to Area & Regions
* [ ] Ethic - Add to Region and inherit
* [ ] Unique Features & Strengths - rename to 'Summary', and add to Area, Region, Crag  (see #1169)
* [ ] Where to stay - Add to Area and Region
* [ ] History - Add to Area and Region

Note I'm working off the table in the help which I'm not sure is actually correct, need to fix up the table as we go too

**Comment by brendanheywood** [comment]
See discussion here:
http://www.thecrag.com/discussion/623378037/crag-locations-and-restucture#m624972441

Cris and I both came independently to the same conclusion we could use 'area's to group collections of crags which don't form a region, ie it's siblings aren't regions and together they don't fill the parent. So this means we should be able to clearly make all regions fit and cover the world perfectly, and then under that we go to areas or crags or whatever. 

However this does mean a semantic change, as currently the 'area' would (or should) be the TLC in the current desired TLC algorithm (but which is currently broken in lots of places #1155 #1288 #1592  ). So either we refine what we want the TLC algorithm to be to account for this use of areas, or we relax this idea of regions only having regions as siblings as there are heaps of examples where it isn't like that. Thoughts?

**Comment by scd** [comment]
I am in catch up mode here a bit. I have added the fields to the suggested area types. This is database config, so you will not see this in dev until I resync.

The Unique Features & Strengths field is meant to be a tag line. Calling it a summary changes the intention of the field. I feel that a summary is best put in the first paragraph of the description as part of best practice guide. If we don't see any real use for a tag line then we should probably remove the field as clutter.

At them moment the business rules are that the TLC is the first non-region/area or unknown. What I think you are suggesting is that a TLC should be the first non-region/unknown. I am totally fine with this. If you want to make this the new business rule then please create another issue, because this will need implementation management in a level of detail that needs it's own issue.

I have changed the inherit rules as suggested. This now leads me to propose that we also introduce a couple more area types - country, continent and world. Although not urgent I am happy to create a long term issue to introduce these.

BTW, I have updated the article. Unfortunately it is not data driven. Maybe this is something we should do at some point. 

I had some issues with pushing the article changes could you please pull the articles from their master repo and let me know if the areatypes has been updated correctly.

**Comment by brendanheywood** [comment]
> The Unique Features & Strengths field is meant to be a tag line. Calling it a summary changes the intention of the field. I feel that a summary is best put in the first paragraph of the description as part of best practice guide. If we don't see any real use for a tag line then we should probably remove the field as clutter.

Summary to me makes perfect sense. It's a very short one line summary of what the crag is all about, the description could be many paragraphs. And I definitely don't want to remove it, I want to add it to more node types, and expose it in more places so it is more useful not less. If the summary is part of the description then we can't easily extract it and use it in different places which is exactly what I want to do in #1169

How about we just call it 'tag line'?  'synopsis' also comes to mind but is a bit nerdy. BTW 18months ago in #1169 you wrote a todo for yourself to rename it to summary :)

> At them moment the business rules are that the TLC is the first non-region/area or unknown. What I think you are suggesting is that a TLC should be the first non-region/unknown. I am totally fine with this. If you want to make this the new business rule then please create another issue, because this will need implementation management in a level of detail that needs it's own issue.

This has already been logged 3 times: #1155 #1288 #1592  18 months ago.

>  areatypes has been updated correctly.

yup came through fine

**Comment by scd** [comment]
I think Tagline is better than Summary.

**Comment by brendanheywood** [comment]
Another thing to consider is that this is actually called Summary right now in the gui and has been that way for over 18 months, since around the same time we started this discussion originally:

![image](https://cloud.githubusercontent.com/assets/187449/5929294/90e35690-a6d6-11e4-8d4d-7386301b83f3.png)

Think it was done in this issue, and don't see any point in changing it

https://github.com/theCrag/website/issues/1194

**Comment by rouletout** [comment]
All items are checked and the issue described is non existent anymore - closing
