### ISSUE TITLE
Show ticked status in routes facet, and other route lists

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1847]
In any list of routes, ie a facet, the list of icons in list view, should show the same icon overlay as list view does, eg a red point or pink point or dog etc

Somewhat related to the #1318 for when we get to that too

**Comment by Mdemaillard** [comment]
Tick status is implemented in 
route facet, 
ascent facet,
![image](https://user-images.githubusercontent.com/60388146/76514277-568de800-6460-11ea-9aae-bb6c14fd5baf.png)
HTML Guide view
![image](https://user-images.githubusercontent.com/60388146/76514403-8210d280-6460-11ea-9c61-bc0d04a6bfb2.png)
PDF Guide
![image](https://user-images.githubusercontent.com/60388146/76514536-b5ebf800-6460-11ea-9d6e-45635d9ecb62.png)


Tick status Is NOT implemented in 
Node facet                     I don't believe this is required, since route facet is done.

Candidate for closure.

**Comment by rouletout** [comment]
Yes, closing
