### ISSUE TITLE
Q: Bolts vs draws field for routes A: it should exclude the anchors (updated docs / ui)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1862]
What is the interpretation of the bolts field? Is it the number of bolts on the route, or the number of draws needed to climb it? ie is there are 3 pitches with 10 bolts each should it be 10 or 30?

Should this include or exclude the anchors?

It's a drop down and not a comma delimiter field like height or grade, this seems to learn more towards total - which is probably the least useful of the two interpretations. 

* [x] update article
* [x] update tool tip hover on bolts
* [x] update inline help in bulk edit

**Comment by tomkjaerolsen** [comment]
I generally use the bolts field for number of bolts on the climb and ignore the anchors.

Eg, if it's 4UBs to a double UB belay, that = 4 bolts.

From what I have seen, I think about 75% of the crags I go to are setup up like this - but it's not completely consistent. 

Maybe if we had a separate field for anchor? That way you could have:

8 bolts + chain anchor

6 bolts + walk off/tree anchor 

4 bolts + trad anchor

etc.

That would make it quite clear if the bolts do or don't include the anchor and also give you an idea of what to expect when you get to the top.

**Comment by scd** [comment]
My assumption has always been draws, excluding anchors.

Do we want a more generic text field with it's own markdown?

Or is this part of the topo?

**Comment by nicHoch** [comment]
At the Alto Mijares area we use hashtags for the anchor type ...

**Comment by scd** [comment]
what about for multipitch?

**Comment by brendanheywood** [comment]
My intention for this was just to clarify the label in the form(s) so people knew how to interpret it, and not to change the system at all.

I don't think I'd want it as markdown, but converting it to a text field and accepting comma separated numbers of bolts for each pitch seems useful and more consistent, but we'd have to be careful how we applied bolts filtering in the facets to this data.

**Comment by brendanheywood** [comment]
I've had a bit more of a think on this, and I think the underlying principal is identical to the gear type question: 'what can I climbing with X gear?'. I think this applies to many fields, like height = what length rope should I bring? and bolts = how many draws do I need?

When it comes to multipitch I think both the max-bolts-per-pitch and the total are both needed, so we really need to break those fields down the same as we do for the grades and comma separate out the components.

On the topic of draws on the anchors, I'm +1 for draws being the number on the route itself, and the anchor separate so there is never confusion, but shown more succinctly as this will be in the route header, maybe something like with mouse hovers for more detail:

8 + 2  = 8 on route + 2 on anchor
8 + tree = 8 + natural gear
8 + crab = 8 + permanent biner you can clip without rethreading

Not sure about editing UI, maybe just a drop down with those 3 choices, any other options we've missed?

**Comment by oliverstory** [comment]
My two cents:

For single-pitch sport route: 'number of bolts' should mean number of bolts on the route, not including anchors. If consistently used, this tells me to bring that number of quickdraws plus something for the anchor. 

Anchor types vary quite a lot - e.g. around Canberra I reckon we've got all of the following:
- tree (no extra gear required - tie your rope around it)
- natural gear (gear you need to bring with you - read description for details)
- bolt belay (plain hangers - walk off or separate rap point)
- bolt belay (rap off - different from lower-off because of position of the anchor on the rock, e.g. a rounded granite boulder)
- lower-off (requires extra quickdraws or rethreading) 
- lower-off (clip-and-go / permanent biner)

You can no doubt collapse this down for simplicity as the above list tells you something about the descent from the climb, not just 'what gear do I need to climb this?'

As an aside some of these anchor types could be useful in the topo UI

For multi-pitch sport routes it's good to know how many quickdraws you need to take on each pitch. This is something commonly asked - if the mega pitch is up next, you want to make sure you're not left short. If it's a short doddle, people can use extra quickdraws to hang stuff up at the belay. I don't think knowing the total number of bolts on the whole climb (without a pitch breakdown) is that useful. For multipitch, I wouldn't include anchor bolts in the 'bolt count'. I'd expect to take something different for the anchor and people have different systems - could be a long sling, cow's tail + quickdraw, or a couple of biners to clip the rope to the bolts.

**Comment by vasilli-ra** [comment]
Was just discussing same with Simon Dale. I agree w/ oliverstory's suggestions. Somebody should make it final and close the discussion.

You should also add a small pop-up-question-mark-help-field that explains this on the web site, so there's no confusion.

**Comment by brendanheywood** [comment]
Another discussion here about this:

https://www.thecrag.com/discussion/1362851412/forum--editing-trad-routes-does-top-bolt-count-toward-the-number-of-bolts

**Comment by scd** [comment]
+1 user issue

**Comment by brendanheywood** [comment]
+1 from support email to clarify

**Comment by Luen** [comment]
I would vote for anchors to be excluded but have an extra dropdown option for the anchors as @brendanheywood and @oliverstory wrote.

**Comment by brendanheywood** [comment]
@rouletout are you able to sort this one? Or at least the article side of things and identify where else it needs to be communicated

**Comment by rouletout** [comment]
@brendanheywood I assume this should go into the re-work of this? https://www.thecrag.com/de/artikel/updatingdescriptions

There is also Issue https://github.com/theCrag/website/issues/640 that links into that.

Any other locations you can think of?

**Comment by brendanheywood** [comment]
Yes that seems like the nest place. I think we should also have some little hover tool tips in selected places, in the editing and in the bolts hover

I don't think #640 should block this task, this is mostly a documentation task where as that is a db / template change, and will also affect the facet searches and needs a few business decisions. It's not massive but I don't want the scope to creep

**Comment by brendanheywood** [comment]
I think we need a whole new section or article which covers all of the mulitpitch aspects together as there is quite a few moving parts

**Comment by brendanheywood** [comment]
List view:

![image](https://user-images.githubusercontent.com/187449/68084648-9c241e00-fe8c-11e9-864c-177180ca9a9a.png)

Bulk edit:
![image](https://user-images.githubusercontent.com/187449/68084707-53b93000-fe8d-11e9-9d38-bbab3bd3047a.png)
