### ISSUE TITLE
Force valid email address

### ISSUE THREAD

**Issue by scd** [theCrag/website#1864]
Many services force valid email addresses. Although I am not interested in this from the point of view of collecting email addresses, there is an underlying concern that, in order to protect our community, there are real climbers behind the accounts.

There are a couple of issues I am thinking about:
1) Malicious accounts. If there is a real email address I think it is much harder to create an account for malicious purposes. If they wanted to keep going with malicious attacks then they would have to create a new email address somewhere.
2) Spammers. We are now getting regular spammers. I have created the serious spam admin button which removes the message, disables the account and removes all other messages by that account. However it is too easy just to create another account.

There would be some related changes if we want to go with this:
- [ ] unique email address for accounts
- [ ] campaign to sort out email dups
- [ ] signup process to validate email
- [ ] email fails - need to validate again

**Comment by brendanheywood** [comment]
> If there is a real email address I think it is much harder to create an account for malicious purposes. 

Emails are trivial to make, this won't achieve much. The only thing this does is validate that the person who created the account has access to the email account they added.

What we really need is karma based checks for new accounts. eg you must have 10 karma before you can post to a forum, and you could get 5 karma for filling out your profile, and you could receive 2 karma every time someone follows you (who also must have some karma so you can't just make two accounts and follow each other). Or whatever, the details aren't important, even the simplest karma threshold will cut out most of the pure spammers and then we'll only have to deal with the more grey cases.

So to double check, we are still not actually requiring emails, but IF someone provides an email do we currently validate it before we use it to guarantee that the person belongs to it? It IS important that we do this so I can't sign up with someone else's email and spam them.

> do not allow simon+evil@thecrag.com email addresses if there is a simon@thecrag.com email address associated with a disabled account.

I think this will have even zero impact, do we even have a single instance of email sub addressing being used by a spam account? There are lots of other ways emails can be re-used eg BobDylan@gmail.com vs bobDYLAN@gmail.com vs bob.dylan@gmail.com vs bobdylan@gmail.com vs b.o.b.d.y.l.a.n@gmail.com (all 5 go to the same inbox) which we could also protect from, but I see absolutely no point in trying to. See above, security via email just doesn't work (the one caveat to this which we use at work all the time is when you control or can trust the email domain, eg trusting student12345@myschool.nsw.edu.au )

On the flip side, us being able to use email sub addressing is a nifty little tool that we shouldn't break for no reason. From an RFC spec point of view, an application should treat every email which isn't character for character exactly the same as a different email address because it is up to the email service to route them. Eg those 5 email addresses under an MS exchange server could all be treated as different inboxes, because exchange doesn't implement email sub addressing by default.

> campaign to sort out email dups

I'm on board with this, however before we can be serious about a campaign to sort email duplicates we need to have a solid process for merging accounts sorted, see #1092. Otherwise what action can they take?
 
The other thing I'd like to see is a more flexible login, ie allow someone to login using their email + password OR their username and password, which is enabled by this cleanup.

**Comment by scd** [comment]
+1 for karma based checks for posting in a forum and for logging in using email.

We do not validate email at the moment, so this is an important process to implement.

It is also important that we can email an account if we need to for some critical issue such as the app withdrawal.

**Comment by brendanheywood** [comment]
Yeah I think we start with the validation for all emails. I'm a tiny bit torn about actually requiring an email, first if they sign up with facebook they may not have an email, and secondly there is a growing trend amongst those younger darn kids today to not have an email at all. I don't know how much of an issue it is for us specifically something to consider.

**Comment by scd** [comment]
You are right about the email thing - both my kids only have them for signing up to stuff. The older one uses facebook the younger, snap chat or whatever his friendship group is using that week. Importantly, note that they both have email addresses they just don't use them to communicate.

I am looking at it in broader context now:
 - [ ] do we force email over web signup (I am thinking YES)
 - [ ] do we force validation before account is usable via web (I am thinking NO, but maybe dashboard has persistent validation section)
 - [ ] do we allow emailless app signup (I am thinking YES)
 - [ ] do we allow unvalidated email to use app (I am thinking YES)
 - [ ] do we send emails to unvalidate email addresses (I am thinking YES to some emails, but NO to others)

**Comment by brendanheywood** [comment]
I think make it really simple:

* emails are optional regardless of signup mechanism, regardless of context (web vs app)
* IF you give us an email, we will validate it before using it in any way

There is no point forcing an email to be used if no-one reads it and we don't need it for any other purpose.

Thinking more broadly the whole point of entering an email, a phone number, a facebook link etc are all as backup communication methods. So if they lose their account we can contact them via email, or sms or facebook or whatever. So if and when we have multiple links like this (we sorta have FB + G+ now) then we could simlpy require at least one of them.

Playing devils advocate: we could just not give a shit and force everyone to have an email account and make our life vastly simpler. Young people like your kids are not our main target audience, and if we force them to have an email then they will find a workaround like your kids have. And the reality is that as soon as they get a job or whatever then email becomes a real part of their life.

Playing devils devils advocate: there is a smaller part of the world where this problem is NOT based on age but on culture. I've read that in China most services use phone number as the primary id and not email, and I might guess this is similar to other emerging countries like maybe Africa.

> Most websites in China use a mobile phone number instead of an email address as the primary identifier for logging in and as the primary password-recovery tool — particularly relevant since email doesn’t have nearly the saturation in China that it does in the West.
http://www.smashingmagazine.com/2015/02/13/china-web-design-trends-2015/

So I'm back to thinking just make it optional, but always validate it. It's no different to if we do have their email but it bounces.

**Comment by scd** [comment]
Requirements for forcing email validation is now being managed internally. Closing.
