### ISSUE TITLE
Feeback from donate page + cancelling bug

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1868]
Just had a mate over and demo'ed the donate page and drilled him on a few questions and a few things popped out which are easy text changes mostly (and 1 big bug):

* [ ] BUG: If you sign up monthly, then remove a card, you are still on a plan which is weird as it will fail in a month. BUT you cannot cancel the plan without a card entered I get this 'Error: This card number looks invalid.'. Removing the card should cancel to plan.

Text tweaks:

I was mostly asking about the pros and cons of once off vs a regular payment, and the price point. His main points that would be a deciding factor are:

* [x] knowing that cancelling is easy before hand - it is easy, but need to sell this more as it isn't visible until after you sign up. Think just a one liner message like "You can cancel at any time from this page". I think this is reasonably clear in the email but this decision point is before he would sign up, not after
* [ ] knowing where the money goes. he was quite suspicious of donations where you don't know what % goes to the actual recipient. So I think something like:  'Your donation goes directly to keep thecrag running and X % goes to a bolting fund of our choice each year blah' need to rework these words to be succinct etc This probably needs to 
* [x] he would not be that interesting in a monthly email for each payment, but whatever is on his bank statement needs to be clearly thecrag.com and not megari or stripe or something else he doesn't recognise. I just checked our settings and this looks good

**Comment by brendanheywood** [comment]
I've done a big style cleanup and given it the same simplicity and focus as the login and signup pages. I've also made a few tweaks to the copy in particular of the initial state which is the most important:

![image](https://cloud.githubusercontent.com/assets/187449/6366180/eb04c64a-bd15-11e4-9bef-0d412959688c.png)

**Comment by scd** [comment]
+1 and really good feedback

**Comment by scd** [comment]
@brendanheywood could you please push your changes

Also what were the steps that allowed you to signup monthly then remove the card. The UI code should not let you remove the card if you are on a monthly plan. I am wondering how the UI let this happen.

I should turn off the card checking for cancelling a plan, because it is not needed. I think this is the real bug. 

I want people to cancel the plan by using the cancel plan check box. I don't want plans to be cancelled as a side effect of them deciding they don't want thecrag the credit card stored in the payment gateway. 

If they do remove the credit card then the next plan charge will fail, because the credit card is removed from the payment gateway.

**Comment by scd** [comment]
I have just done a couple of other logic fixes:
 - [x] allowed plan to be canceled without credit card validation (fixed x3 bugs in the logic chain)
 - [x] report error if removing card has api error
 - [x] fake ga url for removing card success and error
 - [x] allow somebody to change credit cards without changing plan amounts

Finally I am going to write a technical how to article about credit card payments and plans. The feedback was really good. I also want to know what will happen next if I make a payment on other sites. Having a couple of screen shots I think will help. The article will cover:
 - [ ] What is thecrag pay-as-you-feel supporter program
 - [ ] Making once off payments
 - [ ] Making a subsequent payment with the same card as last time
 - [ ] Making automated monthly payments on a plan
 - [ ] Canceling a plan
 - [ ] Changing a plan amount
 - [ ] Changing a plan credit card
 - [ ] Removing a card
 - [ ] What happens when my credit card expires
 - [ ] About thecrag payment gateway

**Comment by brendanheywood** [comment]
pulled

> Also what were the steps that allowed you to signup monthly then remove the card. The UI code should not let you remove the card if you are on a monthly plan. I am wondering how the UI let this happen.

If you can sudo as me I'm currently in this broken state and cannot fix it at all. I am on a plan, with no card, I cannot change the plan, I cannot cancel the plan, I cannot add a card.

https://dev.thecrag.com/donate

To reproduce sign up for a plan, then remove the card.

The UI *should* let you remove your card at any time, and then optionally replace it with another. So there are two solutions:

1) you can remove your card which suspends the plan, when you add another card it prompts to resume
2) you can remove your card which cancels the plan, then you can sign up again with another card

The difference will be in the timing of the next payment, so 1) is preferred.

**Comment by scd** [comment]
I think we overlapped with messages. Could you please try again with canceling the plan, you should be able to do this now without a credit card.  If it is not working then please do a screen shot of the error.

I am not implementing 'suspend' functionality at this stage. I agree that suspending is a nice feature to have, but it introduces a whole new set of states that need to be implement and tested. Until I actually see people signing up for a plan I am not willing to embark on the extra suspend coding.

I have also implemented so you can now just change your credit card details on a plan without cancelling or suspending.

**Comment by scd** [comment]
hold on, there looks like there is an unrelated regression bug - I am looking into it.

**Comment by scd** [comment]
Please pull and try again now. My apologies for the regression bug.

**Comment by scd** [comment]
I have changed the 'remove this card' text to 'remove card & plan' when you are on a plan. This means people will not accidently remove themselves from a plan so my issue is mitigated and your issue of always being able to remove the card is also resolved.
