### ISSUE TITLE
Favorite crags disappeared on profile page

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1871]
Seems that they got lost during the last release. Was that on purpose?

**Comment by brendanheywood** [comment]
@scd I think you did this on purpose, as part of #1686 but perhaps this was a little premature? My comments about the tops level tabs go hand in hand with a bunch of layout idea changes and I'm not sure it works with just the removal of the inline list. I think we add this back until we do the more sort out the more wholesale direction of the profiles, I'd had a few people ask about this.

**Comment by scd** [comment]
Not premature, it's now linked to from the title page.

![profile-favorites](https://cloud.githubusercontent.com/assets/373058/6430561/a13d1de0-c063-11e4-9c37-46b1eb8da148.png)

I think this does highlight that the facet page for favorites is not quite right when you come to it from your profile page.

**Comment by brendanheywood** [comment]
Yeah agree it's not great from either direction, from a profile or from an area. Because they are the only two directions it possibly doesn't even need to be a facet page like the other pages and could be more tailored.

@birgander2 just curious if you were using these to navigate yourself from your profile to your fav crags, or whether that you were concerned that other people looking at your profile would not see them up front? If the former, then did you know they are always present in the drop down under 'index' ?

**Comment by birgander2** [comment]
A bit of both. In fact, I was not aware that they are present in the index, too, thanks for the hint. But I also like to have the favorite crags as part of the profile, at least they make much more sense there than showing the recent crags!? In my opinion, it is fully sufficient to have the recent ones in the index only.

**Comment by brendanheywood** [comment]
Yeah recent crags doesn't make any sense in the profile page, these are only shown to you not to others viewing your page.

**Comment by scd** [comment]
> Because they are the only two directions it possibly doesn't even need to be a facet page like the other pages and could be more tailored

I would prefer to keep it as a facet for now. Facet's have proven to be very useful and we tend to find more uses for them rather than less. I would not rule out other useful facetted searches on favorites.

**Comment by brendanheywood** [comment]
Fav's will be back in the profile. This will evolve to be sorted by crags you've most climbed at
