### ISSUE TITLE
Google Maps imagery shifts horizontal position when updated - implications for maps and overhead topos?

### ISSUE THREAD

**Issue by oliverstory** [theCrag/website#1904]
Not something you can directly fix - but thought I would point this out:

Google occasionally updates the imagery used on Google Maps. Features on the map (e.g. cliffs, boulders) can shift between image versions. This means a sector boundary that accurately matched the cliff location on the last set of imagery won't necessarily match the cliff location on a new set of imagery. The problem also applies to tracks drawn in Google Maps: the imagery might move underneath the tracks from time to time.

From observation at Booroomba Rocks http://www.thecrag.com/climbing/australia/booroomba-rocks and Gibraltar Peak http://www.thecrag.com/climbing/australia/gibraltar-peak-and-corin-road-crags/area/320279823, I'd say a feature can shift by 10-20m between image versions - enough to move a boulder outside the previously-drawn sector boundary, or to move a track from one side of a boulder to the other.

This is one of the reasons I think it can be valuable to have static overhead topos to supplement the map at scales below 20m (as I've done at Gibraltar).

**Comment by brendanheywood** [comment]
Yeah point taken. One would hope over time the georegistration rachets up in accuracy over time, especially as higher res photos are added. I'd be very surprised if an error like that occurred in a city zone. Like you said not much we can do about so I'll close this issue, but I think the moral to the story is to always draw boundaries larger than the feature they contain (except for adjacent areas so they don't overlap) so that if you are standing 10-20m back from the cliff you would still be considered 'in' that area, and as a bonus it's more tolerant of tile imagery changes like this.

**Comment by oliverstory** [comment]
I think some of the topo changes you've got in the works will help too
(e.g. "draw tracks on topos")
