### ISSUE TITLE
multiple grade systems being displayed in list view mode

### ISSUE THREAD

**Issue by scd** [theCrag/website#1914]
Look at this area

http://www.thecrag.com/climbing/france/fontainebleau/area/391703718

In particular the following route:

http://www.thecrag.com/climbing/france/fontainebleau/route/348525558

Which displays 'V0 4B 4' (ie V-Scale, Font and Font alternative)

We should not be showing both the Font and Font alternative grades. However I think we should allow 'V0 4B'.

**Comment by brendanheywood** [comment]
@birgander2 I think I consider this just dirty data, the 2 font grades are definitely redundant, and the V grade according to our conversion table doesn't match up anyway. V grades at the lower end are very coarse unlike the font so don't add much value.

**Comment by scd** [comment]
@brendanheywood good point about the coarseness.

I am happy to say this is dirty data, and where it is not then it is probably leading into the 'whole grade' concept you have alluded to.

I do want to hear from @birgander2 on this issue before we make the data corrections.

**Comment by birgander2** [comment]
Yes, in this case it is dirty data for sure. But still multiple grade systems might be entered correctly, let's say "6A V2", and in this case I think only the local one should be displayed by default (in the route details you can see all of them). There must be many many such examples in the data base. I always thought that the possibility of entering multiple grade systems was there on purpose!?

**Comment by brendanheywood** [comment]
I'm not really a fan of doing filtering of the grades within the 'official grade', I want it to be as simple to edit and display as possible.  If you don't want to display two grades then don't add two. Whether a crag consistently shows only 1 grade or 2 is then up to the discretion of local editors. The other grade opinions can be added as personal grades instead and will be shown on the route detail page. Especially if the two grades don't even convert to each other, that means that either one or both of them is wrong or our grade conversion table is wrong.

**Comment by birgander2** [comment]
I agree completely. I think the double grades are a result of how they have been entered before the last release, but maybe I'm wrong. I thought this was on purpose. Maybe two different topo citations or similar (from an american topo V2 and from an European one 6A), but only one "official" grade is for sure the better solution. So let's edit...

**Comment by brendanheywood** [comment]
Ok well if you're putting your hand up to edit, can we close this issue off?

**Comment by birgander2** [comment]
Feel free. But I fear that there are thousands of enties in your database with multiple grades. If you prefer to display them all (in contrast to only the local one before) that's ok. I can of course only correct few of them.

**Comment by scd** [comment]
Hopefully others will step up as well. For those who want Karma it is a good opportunity to get some extra points fairly easily. 

If there is an area requiring more changes then you can do please send us the link and I am happy to go through it slowly in the evenings. This type of data correction issue happens after the odd release. Brendan has just finished going through 8000 topos.

**Comment by brendanheywood** [comment]
I'm gonna close this old issue. I've now come around strongly to the opinion that showing multiple grades is wrong.

 fyi I'm working on a new spec that will remove the ambiguity around the idea of two grades like "V4 6B". The rough idea is that grades that are the same 'type' eg in this case 'technical difficulty' and 'bouldering' will both be considered as a grade suggestion and they will be combined to form an internal grade distribution for that particular route. If someone else comes along and say it's a V5 then that's just another vote. They all get tallied up into an internal grade curve, and then purely for display purposes gets mapped back to the system that the local area is in, so in this case will a 6B. If enough people that this particular route is a V5 then it might drag the grade up to a 6B+ or 6C. If enough people globally say that 6A's are like V5's then we can potentially also use this to tune the grade conversion tables and recalculate everything, as we keep all the originals.

If you want to see the grades in V instead of Font, then #2527 is the better answer and it is up to whoever is using viewing the grades instead of the author so we get consistency across the whole site.

Watch #2554 for details coming soon
