### ISSUE TITLE
Some characters not displayed in photo topos

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1934]
See here, the ' in the route's name is not displayed when hovering over in the photo topo:
http://www.thecrag.com/climbing/france/fontainebleau/route/581160015

**Comment by scd** [comment]
I note the offending lines in the phototopo template:

% my $name = $node->{name}; # quick hack to fix prod bug
% $name =~ s/"//g;
% $name =~ s/'//g;

It looks like we did a quick hack to solve a server error in a timely fashion. Looking at this further there are two escape sequences that need encoding correctly. 

1. The \ " ' characters must be encoded into html enties (eg &quot; ) for inclusion in the html data property. 

2. The \ " characters must be further escaped in the JSON string. Note that the ' character is not escaped in the JSON string. See\

http://stackoverflow.com/questions/2275359/jquery-single-quote-in-json-response/2275428#2275428

After making these changes I think it works ok now. hot fixed.

@brendanheywood can you cast your eye on this logic and have a quick look in the template as there are a couple of other references to $node->{name} which I think should also be encoded the same way. It is just that they were not covered by the original hack and I don't have any failure cases to test. I think it is to do with non-route topo lines. If you agree just make the changes. The lines to look at are here:

phototopo line 163
%   $points = '-1 -1 lbvnd '.URI::Escape::uri_escape_utf8($node->{name});  

and phototop line 169
"name":"fred <% $node->{name} |x %>",\

BTW, I have pushed the update in repo

**Comment by brendanheywood** [comment]
We really need to sort out the mason escaping stuff so it's much more clear. We do it very badly and inconsistently across the board, and often mix up the correct escaping method. What I'd ideally like is something like:

```html
<xml><% $text |x %></xml> xml escaping
<p><% $text |h %></p> text -> html escaping
<p class="<% $text |a %>"></p> html attribute escaping
<a href="<% $url |u %>"></a> url escaping
<script>
var foo = '<% $js |j %>';  js text escaping
</script>
<style>
.class {
  content: '<% $css |c %>';  css text escaping
}
</style>
```

Possibly some more around flattening and sanitising markdown that may contain html

Then we should systematically go through and test with an escape busting string like:

```
  Some text ' " < > ? & + # - = etc
```

**Comment by scd** [comment]
+1

It may be more complex than that as well because this particular failure mode was combined html escaping and json escaping. data-jsondata='"key": "<% $somedata |aj %>"'  and order is important. I think this escaping is not obvious for a maintainer of code. 

I think we need to first document all the escaping scenarios. We also need to consider the impact of utf8, which is most probably just a perl implementation issue, at least in most cases. I am happy put this on my todo list. 

I am not surprised this is done badly, because escaping was an after thought. 

In some ways I am thinking of a bigger picture process where we define our perfect template/css/js combination then build up the components of the framework from scratch, of which escaping will be one component. We have sort of been moving toward this, but a little ad hoc.

**Comment by brendanheywood** [comment]
Yes there are a couple nesting use cases to consider

The escaping could be done as a template, but I think the syntax would be a pita and verbose, and the sugar of the |x notation makes it really effortless. It might even be worth have a null escaping method like |n and then we can very easily check across the code base that everything is at least escaped.

**Comment by scd** [comment]
I have started a separate issue, but I think we can close this an move on when you are happy that this specific issue is resolved.
