### ISSUE TITLE
XML export link isn't working (and related help pages)

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#1942]
On http://www.thecrag.com/article/KMLCragGuide the link to the KML-guide throws an error.
I'd definitely like to know how to creat kmls from nodes, I couldn't find any entry in the menu.

**Comment by brendanheywood** [comment]
bugger :(

The kml link / export you should get for free, it is the same data as shown in the embedded map in list view with the outline of each crag. There is not yet any capacity to add arbitrary lines, shapes or points to the maps like tracks, boundaries or points of interest see issue #108 for that. But if and when we implement that then you should get this for free in the kml export.

There hasn't been a massive interest in kml, we implemented it and gpx export way back when I first joined in order to take location data offline. I'd be interested to hear what use cases you have in mind so we can see whether it's something best solves with fixing / improving the kml export or whether it's best solves with an offline app.

**Comment by TillF** [comment]
Here's my preference:
I would like to export the coordinates of some nodes of interest, so I can import them into my navigation program of choice. I would not opt for an extra apt, since I do not use Android, and such an app will unlikely provide all the features I find in my navigation program.
Thus, a simple kml or gpx export would be excellent, followed by a listing of the (centroid) coordinates in the list view or the PDF-guide. At the moment, the only way to get hold of some coordinates I found was switching to map editing mode and copytyping the coords displayed during hovering.

**Comment by brendanheywood** [comment]
ok this is an undocumented / buried feature: go to any page like

http://www.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge

now add on /gpx to the end:

http://www.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/gpx

That still works and should be a pretty good starting point, let me know what you think and how you would be better (apart from being accessible from the webpage)

**Comment by MelwinQ** [comment]
I just checked 
http://www.thecrag.com/climbing/kazakhstan/area/664436484/gpx
This yields a GPX with only a single waypoint - this is the only route that is contained within this node. However, all 7 subareas have location data (whereas the route itself has none).
To me, the desirable behaviour would be to put the centroids of all located entities into the gpx. I dunno if gpx can accommodate any hierarchy, but it will also do without. Instead, unlocated child node (i.e. the route) should rather not be included.

**Comment by brendanheywood** [comment]
@scd the /kml_link failure traced this back to last august when the func for this page was changed to '&xxxx' seemingly on purpose. I swapped in back in dev and it still works fine. Did we decide to deprecate this?

**Comment by brendanheywood** [comment]
ok @MelwinQ I've fixed the bug with the kml export so now it is working again (in our dev site):

http://dev.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/area/11382948/kml

Just tack /kml onto any url to test it

@TillF the kml export works they way you want with the boundaries of all areas and is much more expressive. I have also tweaked the GPX export to include area centroids regardless of children locations. The data on our dev system is a bit old so I made a test located area in kazakhstan here:

http://dev.thecrag.com/climbing/kazakhstan/kml

**Comment by MelwinQ** [comment]
Thanks a bunch, looks great at first glance. I'll do more checking as soon as I find the time.

**Comment by brendanheywood** [comment]
Just re-tested this and it's all still working so I've just added back the links to the download menu for non region level nodes which have location data for both kml and gpx:

![image](https://user-images.githubusercontent.com/187449/29461827-7f8aa4b4-8470-11e7-8fe6-87132fcf744f.png)

@rouletout I think this one is worth putting onto your list to spread the news about, not many people know about and those that do probably couldn't find it anymore and have forgotten about it.

The article is pretty basic:

https://www.thecrag.com/article/KMLCragGuide
