### ISSUE TITLE
How to archive outdoor routes?

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#1950]
I know of a big rock fall and I want to mark the lost routes. How to do it without deleting them? Ticking should not be possible any more and the display should clearly show that the route is closed, does not exist anymore or ...

**Comment by scd** [comment]
Historical ticking should be possible. A lot of climbers back date their ticks when they cut over to thecrag for their logbook.

The archiving that we implemented in the gym is not quite right, because the route becomes no longer visible. I guess we can use the same flag, with different behavior for outdoor routes.

I think for now put some text in the description of the route or parent area (if all the routes are gone).

**Comment by brendanheywood** [comment]
This is pretty well a dup of #1244. I'm closing this please read the use cases in the other issue and and more input there if needed
