### ISSUE TITLE
Missing ascent styles DWS tick, Boulder flash?

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1954]
There seems to be no good way to enter a DWS ascent (tick? solo?), why not adding DWS as an own style? Also a bouldering category is missing: flash can be found under lead, but what when not flashing: tick? red point? solo? It is a bit confusing what to do.

**Comment by brendanheywood** [comment]
I've had a good think about this and other 'weird' ascents like top roping a boulder, or leading a DWS. There is almost always some weird route which doesn't fit the mould so I'm keen not to limit the ascents styles but merely highlight or encourage the 'right' ones. Some DWS for instance can actually be lead as sport routes from a boat, so if doing as a DWS would probably best be ticked as a solo rather than as a lead. We have a vague plan of turning the ticking more into a set of flags internally, like 'first attempt', 'no beta', etc to better model the real messy world for all styles not just DWS.

Se #1259 and #1217 for a bit more discussion, but it still needs a bit more analyis

**Comment by scd** [comment]
+1 about the plan to turn it into a set of flags. I am happy to add styles as long as it does not take us down a more difficult path to migrate when we change over.

**Comment by birgander2** [comment]
Flags are a good idea, only probably tricky for the profile summary (don't know). However, for the few remaining 'non weird' cases (as mentioned above) a simple extension of the ascent list would be a fast and simple solution. In any case one can always add comments in case of weird ascents types...

**Comment by scd** [comment]
@birgander2 we have had further discussion in issue #1217

**Comment by brendanheywood** [comment]
So planning to address this in a few weeks, the current thinking is we will add a few more tick types, rename a few other, and also filter them all to only the ones that makes sense for the type of climb eg dws, boulder etc

**Comment by brendanheywood** [comment]
Closing this as done in https://github.com/theCrag/website/issues/1217
