### ISSUE TITLE
topo lines missing from gym topos in feature template

### ISSUE THREAD

**Issue by scd** [theCrag/website#1965]
https://www.thecrag.com/climbing/australia/queensland/brisbane/rocksports-indoor-climbing/room4/rope22

**Comment by scd** [comment]
hotfixed

**Comment by brendanheywood** [comment]
What was this? escaping?

**Comment by scd** [comment]
topo js code was commented out at the bottom of the gymFeature template

**Comment by brendanheywood** [comment]
Ah, I have a vague memory of this actually being on purpose for rockit to save some ms render time as they didn't need it

**Comment by scd** [comment]
Do I need to detect if there are topos and only include it if there are. Best of both worlds?

**Comment by brendanheywood** [comment]
Sure but if you are going to do this lets do it right. What I want is a hidden global var that the templates can access to add dependencies via a function. So the topo template would say something like 

```
% requireJS('topo.js');
```

* [ ] If it gets required multiple times it gets ignored. The list of required js files files is retained in the order they were added.
* [ ] the normal file path expansion into the versioned file would still work
* [ ] Then the footer template can grab this list and render it in order. This would vastly simplify the way we manage the dependencies for each page and has the potential to streamline a lot of pages that don't need particular code.

* [ ] I think it would be good if the function took a second argument, which is a javascript expression which if true means the script is should be loaded. For almost all this will default to just 'true'. This allows us to do stuff like:

% requireJS('topo.js', 'Modernizr.inlinesvg');

So the topos will only get loaded in a browser that can support them.

% requireJS('maps.js', 'window.matchMedia( "(min-width: 500px)" ).matches');

So that the full google maps widget will only load if the browser window is over a certain size(otherwise fall back to a static map).

This expression would need to be available to the footer template to render into the javascript to execute the test and then write the script tag if it passes.

**Comment by scd** [comment]
I am splitting this into two issues. This issue is now dependant on #1967

**Comment by Mdemaillard** [comment]
hum, if i understand right this was hotfixed, and the underlying performance topic split. 
So candidate for closure.
