### ISSUE TITLE
More gym thoughts

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1978]
Just went through the motions of starting to enter the gym stuff for UNEOAC as a dog meat eating test case and have some minor usability tweaks:

* [ ] color is often more important or as important than name, and they are often tightly related. Let's move colour right under name

![image](https://cloud.githubusercontent.com/assets/187449/8981764/29c4d99e-36fe-11e5-8621-6c5b695d2247.png)

* [ ] This error message sucks: "On row 2, you have an invalid color name. On row 9, you have an invalid color name." It would be much better to give the route name as well, and highlight the invalid data

* [x] The busted colors were 'brown' and 'orange' - why are these invalid? I've added these to API/Tools.pm is this the only place?

**Comment by brendanheywood** [comment]
* [ ] in the auto complete dropdown it should show as a first priority the list of editors for the gym under a 'Setters' grouping. Maybe this should be generic to cover normal crags too, maybe just 'Editors'?? Or could just swap the naming depending on gym vs crag

**Comment by brendanheywood** [comment]
* [ ] some menu items are missing - in particular it's impossible to re-order routes in a gym

**Comment by brendanheywood** [comment]
* [ ] descriptions don't show? ie I've added desc's to the three blacks variants to tell them apart but they don't show: http://www.thecrag.com/climbing/australia/new-south-wales-and-act/northern-tablelands/uneoac/area/708682578

**Comment by scd** [comment]
Colors are css2 compliant as far as I can remember. css3 has many more color names, but css2 has a restricted set. I am happy to be convinced that we can use a wider range of colors. Otherwise we might start to specify how we are going to do more generic color solutions.

Good idea with the Setters autocomplete. Although I prefer keeping it generic and calling it Editors. It is more important that the shortlist of names are there than the actual name of the grouping.

I thought we made the business decision to omit descriptions, or maybe it was an oversight. We should readdress this and include them.

The action button still has the resequence functionality. But there may be some capability that is missing because we cannot get to the route page. Need to assess.

**Comment by brendanheywood** [comment]
The colors has a regex whitelist which I have added the extra ones to and hot fixed but I think it needs a restart so I left it at that.

**Comment by scd** [comment]
restart or reload will do it. 

/etc/init.d/apache2 reload

I am sure I will restart it again soon because there seems to be an emergency hot fix almost every day.

**Comment by brendanheywood** [comment]
Ok there is something else missing, the colours work but are not in the dropdown or the comment next to the field. Must be in the db? Missing is orange, brown, tan

**Comment by scd** [comment]
We made a decision a while ago to only support css2 colors. There are many more css3 colors. I am not sure the color support for browsers. If you can speak to that I will do the necessary back end work. We may have to map the color names to their hex.

**Comment by brendanheywood** [comment]
No I'm talking about something else, how do I update these two lists:

![image](https://cloud.githubusercontent.com/assets/187449/9054111/ef4279a4-3ac0-11e5-89a8-4dd0fe09cc70.png)



.... never mind I found it :)

**Comment by scd** [comment]
Great. But are there any css2 vs css3 color issues we need to consider?

**Comment by brendanheywood** [comment]
css2 is from 2003, it's only ie9 that is the issue:

http://caniuse.com/#feat=css3-colors

I'd just ignore it, and if its a hassle then we can regex replace just those couple colors with their rgb in the template at render time.

**Comment by scd** [comment]
I have done all the things listed here:
 - [x] improved error message reporting when in multiple route create mode
 - [x] moved color to under the route name
 - [x] update default route setter to be a mention not just a name (an I came across this in debugging)
 - [x] added 'Area developers' (what you called setters) to name completions in history. This is now available in any crag. I did not want to use the name Setters as it is to specific. Editors is sort of wrong because these may not have edited anything. I think area developers is the closest I can think of, which covers FAs and Setters. Happy to hear other thoughts on this
 - [x] the resequence menu item is still there under restructure. We may wish to re-address where we put it.
 - [x] route descriptions were clearly filtered out in nodeListView template (line 384). I think we are readdressing that decision. I have put it back in, which meant I needed to create a max height for the swatch grade and also move the descriptions over to the right a little bit so it was not hidden under the grade. I also added a class 'gym-feature' to the markdown descriptions so that we can format gym feature descriptions differently if we want.

Closing
