### ISSUE TITLE
Replace area activity feeds with streams

### ISSUE THREAD

**Issue by scd** [theCrag/website#1982]
It would be good to replace area activity feeds with streams. This should be straightforward down to top level crag as it is pretty much the same functionality as account streams but configured in a particular way. The non straightfoward issues we need to work through are:

 - [ ] do we extend the month time window for crags. Eg inactive crags may not have anything in a month, especially in winter. We could extend it to a year, but then this would be no good for regions and countries because the query is not so good over a year timeframe for a country with a lot of activity (eg Australia).

 - [ ] for updates, streams are aggregated to account and top level crag. That means that when you are at a route (or cliff) there are no update streams events associated with that route (or cliff). So how do we handle this?

 - [ ] For cliffs I can see the following options.
  - [ ] Option 1: inherit the top level crag stream at cliff level. I think this may end up being confusing though, especially as this would include sub crags of top level crags (mt stapyton in grampians).
  - [ ] Option 2: don't show streams or feeds at cliff level, but rather point people to facets.
  - [ ] Option 3: keep feeds the same as they are at cliff level. More code maintenance.
  - [ ] Option 4: do something clever by joining activity log for that cliff with the events of top level crag, then displaying events with activity log filtered. This means an event may look different if viewed from the context of 'The Plaque' (which would only show plaque related activity), versus Arapiles (which would show all activity at Arapiles). This seems right to me, however we have to be clear that we are ok with viewing events in different contexts gives different results.
  - [ ] Option 5: change our underlying model. I really don't want to do this.

 - [ ] and for routes we have the same options. However performance may become an issue with option 5 because we could have a big query (Grampians for a month) but filtered to very little information. We can optimise this with some smarts. Actually I think it is simple to optimise at route level, but more difficult to optimise at area level.

 - [ ] as we get lower down the index I think I want to see different things anyway.  It is more about the audit trail of what has happened. Eg a route was created then moved to another cliff. If this was done over several days then this information would be spread over several events. Also audit trails are more difficult with private accounts. So I think we park this particular aspect for now.

I think we just need to get something in place which has reasonable functionality and has mostly the same code base as streams in the rest of the system.

**Comment by brendanheywood** [comment]
> do we extend the month time window for crags.

For the atom feed in the metadata you link to the next and previous page blindly. Feed readers like feedly will do all the smarts to paginate and join them together. Some very simple feed readers might get a truncated list if it's the first day of the month and they don't support pagination. I'm not too fussed about that.

In the context of the embedded feed on the area page I think keep it the same window size and just load up more pages on demand client side. We could do some quick tricks here like looking at the stored statistic for the last modified node and then starting the pagination at that point.

I also like facebooks model where when you get to the end instead of just having a 'Next' you get a list of years or months and can load exactly what you want.

Option 4: look good to me and what I naturally thought of first. It's nice to see in the context of cliff X that person Y added 100 routes across the whole crag but only N routes in this cliff. I think for the first release thought we could just filter the events themselves but not actually customise the event text.

**Comment by scd** [comment]
I just integrated the streams onto the home page. I remove the Facebook link because it took up valuable space for very little benefit. The streams are way better.

**Comment by scd** [comment]
I mean the site-wide home page.

**Comment by scd** [comment]
I have also replaced the route and area activity feeds with streams. 

When we get below top level crag or gym then the algorithm bases the filter on the activity log items. We do the same at routes, but also have a 12 month window for routes.

At route level it is actually pretty cool to see what else the person did, so having the full event is a feature. At cliff level it may be a little confusing, but it is workable.
