### ISSUE TITLE
expand update event

### ISSUE THREAD

**Issue by scd** [theCrag/website#1995]
Within an update event we should expand each event item to be more descriptive, similar to the activity log now.

In particular I really really want to show how descriptions have changed. There is perl module which does exactly what we want:

http://search.cpan.org/~yappo/String-Diff-0.06/lib/String/Diff.pm

We should order by node, then date. This means that if somebody made multiple updates to a route then they would all be shown consecutively. In some cases we should be able to combine, so for example you create a route then update the style then we really only need to say you created the route. I need to think about this more.

It is possible that a single event have a lot of updates (eg fully document a crag in a single day). We need to consider how this is optimised server side.

**Comment by scd** [comment]
I have just done an audit of all the activity log items and have some thoughts about combining similar activities if they appear in the same node in the same event.

Group: Create, update, and delete area activity
 * Register Area
 * Update Area Type
 * Merge Area
 * Delete Area
 * Request Area Name Change
 * Resequence Area
 * Update URL
 * Various area restructure ghost events only if their main event is not in the same event.

Group: Create, update and delete route activity
 * Register Route
 * Delete Route
 * Reparent Route
 * Merge Route
 * Update route details
 * Update route history
 * Rename route
 * Request route rename
 * Update Grade Contribution
 * Update Principle Grade
 * Update Star contribution
 * Update URL
 * Archive Node
 * Unarchive Node

Group: Update area descriptions. Keep on it's own, so we can see descriptions changes

Group: Update route descriptions. Keep on it's own, so we can see description changes

Group: Locate area. Keep on it's own, so we can potentially show the map.

Group. Locate route. Keep on it's own, so we can potentially show the map.

Group: Upload photo, update and remove photo. (the update photo does not currently exist)

Group: Make topo, update topo route, relink topo and remove topo should all be grouped and the final topo presented. (actually the relink and remove topo activities do not currently exist)

Group: Log ascent, update ascent and delete ascent should be grouped (actually the update and delete ascent do not currently exist as an activity log item).

Group: Add shortcut, remove shortcut. (remove shortcut does not currently exist)

Discussion events are separate within the event.

**Comment by brendanheywood** [comment]
There is a lot of cross over here with #1918 and #662 so I think what you said above would close both of them off. There was a reference to a different diff perl module which differed html instead, do we want to show a diff of the raw markdown or the resultant html? or diff the markdown and then convert it to html with red/green highlights of whats changed?

**Comment by scd** [comment]
There is a lot to this issue I am just going to brain dump until it becomes clear:
 - [x] ghosting implemented such that if a ghosting activity appears in the same event as the activity it is ghosting then it will be dumped from the stream report.
 - [ ] we need the changed topo data, not the current topo data
 - [ ] check discussion order, I have moved things around so I think this may be broken. I think different events need different ordering. For example an update event should be ordered in index order, while discussion should be date order.

**Comment by scd** [comment]
- [ ] if lot's of activity in an event then we should trigger summary mode

**Comment by scd** [comment]
- [ ] you should not be able to edit a topo from the feed

**Comment by scd** [comment]
FYI, streams now show historical descriptions as a diff of what was changed. Pushed. If it is a new description alltogether then no diff otherwise the `<ins>` and `<del>` markup is used on the pre proposed markdown text. I am not sure if we should process the diff before or after we do the markdown processing.

The one case where it would matter is where an `@brendaheywood` is corrected to a `@brendanheywood`. I this case the diff will interfer with the markdown.

**Comment by scd** [comment]
Awesome, I have just got topos in streams to show historical changed data. If a topo has 10 lines then it will only show the lines which were changed and use the historical data. If there are several lines changed then all the changed lines will be included. If there are several consecutive changes to a line then your last change is shown. If the topo tool had the ablility to show an old outline line then I could also show what it was changed from.

Pushed, but limited testing.

**Comment by scd** [comment]
I just came across a little structural issue which will actually also help us define specific parts of the stream.

We have already locked into this idea of having an inflate variable which provides the object details once for a stream no matter how many times you refer to it. The inflated object uses current values not historical values. I started down the track of overwriting current values with historical, but this is flawed if you have an object referred to in multiple events (eg update a route on two consecutive days). 

What I am now doing is defining the inflate as current data and providing historical->{objectID} for historical data that needs to be displayed.

This makes me think that when we refer to object such as a route, we use the current values, however if there was anything pertinent that was different at the time then it can be made explicit in the event details. For example a route was called "Original But Wrong Name" when registered, but later corrected to "Now Correct Name" then the reference to the route will show the current "Now Correct Name" but the route details will say something like "Originally created as 'Original But Wrong Name'".

**Comment by brendanheywood** [comment]
Re topos I think we have to be careful not to confuse people who see the subset which has changed and think it is current state. So either clearly show that it's a 'diff' topo or show state at that point in time. Dunno how best to show a diff, using color isn't a great option, dotted lines for old topos overlaps with the hidden style but could work. Perhaps best could be to show current state and then toggle to previous state on hover or with a new button

**Comment by brendanheywood** [comment]
Re diffs: http://dev.thecrag.com/climbing/australia/mt-coolum/stream

Can we tune the way it does diffs at all, this is a little horrid:

![image](https://cloud.githubusercontent.com/assets/187449/9291951/29702c7a-4421-11e5-9b43-ac4a5b9cfb92.png)

Also added some colour:
![image](https://cloud.githubusercontent.com/assets/187449/9292022/8fdf6806-4424-11e5-8702-3c6bfeb1631f.png)

**Comment by brendanheywood** [comment]
I think as long as the diffs are always on word boundaries that would be 90% of the problem fixed.

**Comment by scd** [comment]
I was thinking the same thing about the word boundaries. If we did word boundaries then I think it would not matter if it was pre or post markdown processing.

**Comment by scd** [comment]
On the issue of topos (and also descriptions for that matter), there are three relevant states:
 * Before the update
 * After the update
 * Current state

The way we use activity log (ie monitor daily) we are most interested in the current state which closely resembles the activity updated state, because the update is usually pretty recent. However the stream event should describe what has been changed by that person. 

I recon we ghost the pre-update topo line with an opacity of 30% and show the changed line. I agree it would be good to to have a button (not hover because of touchscreens) to toggle to current state.

I think a similar concept applies to descriptions.

**Comment by brendanheywood** [comment]
ok lets make up some history:

* a year ago I make a topo and add 3 routes, A, B, C
* a month ago I add another 1 D and modify an existing one A2
* yesterday I add another one E and delete a route B

What I'd expect to see in the stream when scrolling back is a history of how the topo evolved:

* yesterday: A2, C, D, E
* a month ago A2, B, C, D
* a year ago A,B,C

I think we agree that only showing the new or changed routes isn't great and we also want to show unchanged routes to give the update state at that point in time. Perhaps the simplest way of showing which ones have been updated vs unchanged routes is to only give the changed ones the grade colors and leave the unchanged ones in grey. We can do this now with zero topo code, just don't send the gradeband data over for them. Dunno about route deletes, we could show it in some way like a black dotted line but for now I reckon just don't show it.

The next level of complication is when multiple people both edit the same topo on the same day. I see this happen a lot in the wild with two people climbing together and working on stuff that night, or with me scanning new topo edits and tweaking them. If we leave things as described above then you will see two topo versions in the stream showing the interim state X1 done by person A and then the update X2 by person B. It could get a bit weird when both make multiple edits to multiple topos interleaved and we only show **what they changed**, so in event X it could show the state of topo A1 and B2 (their latest tweaks) while the next event by B could show A2 and B1. Because each event contains 2 topos it's impossibly to order them correctly and end up with the most recent event showing the correct final state. If we merged the topo events together and only show one updated state that would work in some cases but I think that would create a bunch of other problems.

So I think the best solution is to instead say each event shows the state of the topo(s) **at the time of the event last update timestamp** which could include updates by other people, and in most cases will be identical to just the changes by that person but this isn't guaranteed. So it's not as simple as showing what that person did, but instead how it was left after they last touched it.

Back onto the topic of diffs and text, I think the idea solutions would be a bit more sensitive to the context. So if the only diff was one letter in a word then I reckon wrap just the changed letter, but if it was one word add and remove then wrap them, but if it hit some threshold like 90% of a paragraph them wrap the whole block, not at the word level.

**Comment by scd** [comment]
I have added a objects => undef variable to the phototopo template which gives us the ability to override the topos current objects with the historical objects.

@brendanheywood I don't fully agree with you about what time slice to show in the topo. I still think it is important to show what a particular person has done in an event. If I see an event with my name on it then I expect that it will show what I changed not what I and others changed. I think this is required for transparency. If we were to join the events of the two people then I would agree with you, but that is way difficult with our current architecture, so we are not going to do that.

I have made a compromise which I think is the best of both worlds:
 - [x] show the objects that the person has changed plus
 - [x] show the objects that the person has not changed and
 - [x] indicate if there is more recent topo lines. 

I separate the objects that have and have not been changed so that at some point we can display them differently. However we do it should work for both shapes and points (ie areas and routes). 

If one person is editing a topo then this is effectively the same as you are suggesting, but if two people are editing a topo simultaneously then neither will necessarily match the current version.

Displaying an indication that the topo does not match the current topo data is my preferred approach in doing this because it also works for historical entries where the topo has been changed on subsequent days. If we need to, I would be happy to also display the current topo data.

I am now storing the full state of the topo objects before and after changing the lines in a topo. This makes it easier to get the required diffs without complex lookups based on timestamps.

There is something I am still working on before you can pull from repo and test.

**Comment by scd** [comment]
ok I think it is working now for new events and historical events.

You can see the text 'This is not the most recent topo' above a topo that has more recent data.

![tc-topo-event](https://cloud.githubusercontent.com/assets/373058/9354041/675a1a1e-46b0-11e5-90e2-e9bc1a26745f.png)

QUESTION: Do we want to also show the current state as well as the historical changed state.

Note that there is a hard delete issue with topo routes which means that it is possible that historical topo time slices may not be identical now as they were back then. We should be soft deleting.

**Comment by scd** [comment]
in repo

**Comment by brendanheywood** [comment]
> QUESTION: Do we want to also show the current state as well as the historical changed state.

I think keep it simple, your solution with the warning if it has since changed is good, and this is a small edge case. I don't think we'd ever want to show two versions of the topo side by side, and I don't have a lot of bandwidth for implementing much in the topo tool to handle it, like ghosted lines or whatever.

**Comment by scd** [comment]
I think this can be closed now
