### ISSUE TITLE
Handle end of stream somehow

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2003]
If you go back in time to the beginning:

* [ ] load more should go away
* [ ] have a nice place holder to show the beginning of the timeline

In theory areas should always start with a 'create' node event but are we generating all retro events?

**Comment by scd** [comment]
This needs a lot more discussion and performance investigation.

For fast MySQL processing speed of steams assumes known time windows for filtering stream events.  I think processing speed can be fast for an open time window for a particular person or a particular crag, but generally speaking there could be processing speed issues finding the first event in a stream.

A crag is efficient because there is a direct index on that node, unless it is more than 8 levels deep or it is below top level crag (in which case we have to join events with matching activity). 

There is not a direct index on a person as we have to join with the Involved table. However a person is relatively efficient because there are a limited number of events associated with a person.

Generally speaking I am not confident that we can quickly (<500ms) find the first event in a stream for all cases. However I realise that often when posed with a problem we find a way.

Not all streams will start with a create node. The very first event on a persons stream may be a tick event. I think it would be true to say that all index streams start with a create node

The reality is that we do not have all the historical information we need to go back to theCrag big bang, when the first world node was created. I wish we did.

We are creating retro events on the 700k activity log items in the index, but that only covers half the routes.

We could make up create node activity which pre dates existing activity log and assign it to a system account, then do some special processing to display it slightly differently.

I think this issue is in the too hard bucket for now.

**Comment by brendanheywood** [comment]
How about a completely different approach. How about as well as having a stat per node for last update we also store first update. For an area we'd just say 'area was added' may not really need much detail. Climber is 'climber joined thecrag'. 

So are we making retro events?

**Comment by brendanheywood** [comment]
Sorry missed you're comment re retro - but anyway lets step back a step because I think there's more to this. The real usability issue is two fold, lets imagine a stream history whre someone makes a crag in 2001, then very little happens for 10 years, then it has a bit of a redevelopment and a few peope ticks and there are more updates. When you get to the end of the recent chunk you'd need to click 'next' 120 times to get more, and you don't know if it's broken or if there is no more or what.

So what I think is internally we do 2 things:

1. store a stat for the earliest stream event, once this is set this should in theory never change. The 'load next' api can see if this is within it's boundary and just tack on a flag or fake event or whatever we need
2. I think we commit to stream window size of a month everywhere and then index wether there is any stream content at the BLC + year + month bits (or acount + year + month bits). This would be very efficient as we only need to store '2010:12345:16bitmask'. 16 bits = 1 for each month and 4 left over. I'd guess we have roughly 10,000 BLC's which perhaps on average 10 years of stream data = 100,000 records and each record should be 3 integers so small data and very fast to lookup. And whenever we do a lookup for the current month we will usually get a few months ahead as well, and even if we wanted to load it's entire stream presence history it would be a very small query of a dozen records. We'd retro calculate the old stuff but then only need to do a bit OR update at the BLC level for new stream event to keep it current.

This opens up the possibility a lot better UX, eg when we get to the end of the feed, say 2015 Aug, instead of simply saying 'Load more', we could say 'Load July 2015' and if there is more pages in the current month we can show that. If there is no data for a while we can just show what is the next month to load. And if we really wanted instead of just a load more we could show a quick list of all the years there is data for and people can load up which every year and drill into the month in 2 clicks without having to load and scroll back heaps and heaps. Facebook does this in a couple places:

![image](https://cloud.githubusercontent.com/assets/187449/9323471/697853f2-45c4-11e5-9ecf-ade0bd2529b3.png)

**Comment by scd** [comment]
We are making retro events, but only from the pre-existing activity log. This means it is partial retro events and will not include anything from before the activity log went online. Furthermore the activity log has progressively included more activity items.

The node create date is the first update, however re parenting may cause some issues which may mean that the first update date is before the node create date. So yes we would have to store first activity date.

This would work for a specific node and be blindingly quick. If we were querying the crags you are watching then it would be the oldest date. Similarily for accounts and accounts you are following.

This would give you the oldest possible date for a stream event but but because of filtering different event types (ticks/updates/etc) there may not be any events associated with that date for the stream we are querying.  This is not a problem for a standard node stream because we are including all event types, but will be a problem for account stream events which has all manner of filtering.

I just saw your last post and stream bitmap will probably do it. I think all my comments still apply so I am going to post this and think about your comments in more detail.

**Comment by brendanheywood** [comment]
It won't matter if the stream history is missing events, it only matters that the stream events and the index are consistent so we can quickly look at the index and see if there is anything older. When generating the 'firstmod' stat we could detect if there was a 'nodecreate' event and if not just set a flag and then in the stream template we'd show something like 'Lost in the mists of time' similar to how we show '< 2004' in the profile page.

So I think we agree that the area streams are fairly well catered by this setup. Yes the account merged streams will be a bit more work but I think will be well sorted too. If we are following 20 crags and 30 people that means we need to check 50 nodes stream event bits to see if there is more to load, but in reality this is still only a single call, and if we craft the query carefully to only return a single item which is the bit OR of all records. I don't this as much different to what we are already doing to union in all the log stuff to create the events anyway

**Comment by scd** [comment]
I think you are suggesting a StreamHasContent table. Let's not worry about the bitmap because it will not make much difference in efficiency because we have to join with each year anyway.

On the otherhand if we did want to use the bitmap idea for accounts and nodes we could store a large bitmap of months starting from 2000. There is no reason why bit maps cannot have thousands of bits. 

Option 1: StreamHasContent table with fields Entity (Node/Account), Year/Month. All our stream queries finish on the last day of the month, so I might align to that which may give us some coding join effeciencies. Possibly We could also have a field for the stream type (eg update/tick/all). When we build the Stream query we could use the same where clause without start dates, to get the compete content. One advantage here is that we could also store how many events.

Option 2: Open ended months since 2000 bitmaps tied to specific nodes and accounts for stream content. As it is tied to the specific node there is no additional joins so very efficient. We would have to have one for each type of stream activity (eg update/tick).

Note that the original version of theCrag used search bitmaps to quickly look through the index for grades, styles, etc. There were about 1000 bits and when one was set at a route level would roll up. It was pretty awesome and super fast even with 1999 technology. This was ported to mysql fields and I think is still in there, so I know large bitmaps work with MySQL.

If we were to implement open ended month bitmaps on nodes then implementation may be pretty simple and could be done on activity with ancestor rollup. The one thing that could cause headaches is the rolling date nature of discussions, so a discussion may move from one month to the next which may result in the previous month changing status from having content to not having content. Maybe we just ignore this.

**Comment by brendanheywood** [comment]
Whatever is fast, I've never used big bitmaps but sounds great. Option 2 looks better to me but I'm not fussed. The false positives with moving forum should be ok as long as when we detect it we clean up the map as we go.

**Comment by scd** [comment]
I just read your next comment. Yes I am happy that there is a solution here. I don't think we have to make structural changes to the way the streams currently work so we can just make these improvements when we feel we want to.

I am in two minds as to whether we prioritise this for the current release or put it off. Overall I think there will be significant work implementing this. Assuming we go with the large bitmap idea:
 - [ ] add x5 bitmap fields (all,tick,update,upload,configure) to Account and Node.
 - [ ] when we log activity we check the account bitmaps and update them if neccessary, we check the node bitmap and update it rolling up to world node. 
 - [ ] if it is a discussion event we may have to assess and rework historical bitmaps for account and nodes. If we are not worried about false hits then we can ignore this task altogether
 - [ ] merging requires merging node bitmaps and rolling up changes.
 - [ ] reparenting requires reassessing parents bitmaps with node removed and rolling up changes. Same for new parent.
 - [ ] deleting I think we keep bitmaps
 - [ ] create a second has content sql statement which uses the same where clause to get full bitmap history for the stream.
 - [ ] UX changes
 - [ ] logic to back to next time window with content.

**Comment by brendanheywood** [comment]
Yeah I think it can wait for another release

**Comment by scd** [comment]
We might be able to use our stats framework to manage the bitmaps. If this is the case there is quite a bit less work in this than I first thought.

**Comment by scd** [comment]
More thoughts on this. There are 8 stream types

1. tick
2. favorite
3. join
4. update
5. upload
6. follow
7. customise
8. discuss

From a search point of view these map to three configuration choices

1. ticks
2. updates
3. discuss

Rather than having 1 database field for every stream type we could have one byte for all 8 stream types, or half a byte for three aggregated search types. I do not think we ever need to index on these fields, just AND them and read the result. The advantage of combining is that if you want any stream type the answer is in the byte itself.

I am pretty sure there are no stream events which predate 2010 ( I will check to confirm). This means we could start the byte count at Jan 2010, each month taking up half a byte.

The biggest problem I see at the moment is that this does not take into account permissions of the user who created an event. There may be an event that can only be seen by some people. In which case the bit map map say there are events but the query returns nothing.

Maybe we just live with the occasional stream and a positive bit map means there 'could be events'. A negative bit map means there is definitely not events. Are we happy to live with this??????

**Comment by brendanheywood** [comment]
Given that almost all stream events are public I think this is ok

**Comment by scd** [comment]
All discuss events are public.

Ticks on private accounts are not public.

Updates on private accounts are currently not public, but this issue is still under discussion, so at some stage they may go public for future events not past events.

The large majority of events will be public, but I think 'almost all' would be overstating it. I think that it would be fairly rare that the only events in an area are private. So I agree with you that it is ok.

**Comment by brendanheywood** [comment]
A random test case I found just then:

http://dev.thecrag.com/climbing/australia/cathedral-rocks/route/446614434

have to click back 4 times to get the history

**Comment by scd** [comment]
As it stands now this will be very common at the cliff and route level at minor crags, especially outside of Australia. My feeling is that this will be a bit shit and I am rethinking completing this issue before the release. I am pretty sure we have defined what needs implementing. I am not so concerned about getting every UX aspect working, but it would be good to get the stream to always show the first window with content and for the next button to go to the next window with content. As long as we are ok with the private accounts creating an occasional misfire then I think we should do this work for the release.

**Comment by brendanheywood** [comment]
Yeah  I think there is a lot we can leave and refine, but this one we should get mostly right before release.

**Comment by scd** [comment]
This is done in repo. However it will not work until I give you another copy of dev. I am syncing from prod first then re running the data migration scripts. Will take a couple of days. In the meantime here is what I have done.

Template data
============

 - [x] Added data->{activeDates} to the template, which returns all the dates where there are stream hits. eg ["2014-10","2015-07","2015-08"]
 - [x] note that this template data can be used for the direct templates (.../stream), but not in the templates that embed the stream (eg /dashboard).

Template
============

 - [x] The template populates the 'data-active-dates' parameter in the stream-content div. 
 - [x] This is then used by javascript to find next previous active window and end of stream
 - [x] There is a little complexity in the embedding, in that this information is not supplied until the first emedded stream is returned. When that happens the data-active-dates parameter is updated.
 - [ ] We could enhance the UX to show the active years as you suggested by using the data->{activeMonths} template variable. But I think this is less important, so I will leave it up to you if you want to do anything in this release.

Javascript
============

 - [x] First call does not need to know anything about the active months. It just returns the current window which may or may not have any events. If it does not have any events the the javascript uses the data-active-dates setting to find the next window. Therefore it does not matter if we are querying on a 12 month or one month basis for the current window. The change to the javascript was replacing the prevMonth function with a prevActiveMonth function.
 - [x] Historical stream windows are always on a single month basis.
 - [x] When we get to end of stream the the button disables and a message is displayed.

Backend 
============

This is actually pretty cool because it required for statistics to be added to our statistics package and a couple of SQL calls to calculate the statistics baselines. I needed a field to be added to the following statistic tables:
 - [x] Direct route statistic 
 - [x] Direct area statistic
 - [x] Rollup node statistic
 - [x] Direct account statistic

I defined a statistic processing point 'Log Activity' which triggers a delta change to the statistics. I already had bitmap filters in the statistics package as a standard type, so rollup worked without any changes, delta changes came with a very simple piece of code converting a date to a bitmap and management of the bitmap for reparenting (and other restructure activities) was already in place. This left a simple query to determine the baseline bitmap for an account based on the events they were included and nodes based on activity they covered. 

The bitmap itself is a sequence of 4 bit groups representing a month starting at 2010-01 (offset equals 1). Activity actually started in about October 2010, but I figure the 2010 start date has a nice symmetry. It is not in my plans at any stage to backdate events further back then when our activity log first started. I have defined the following bits in the 4 bit group.:

 - [x] bit 1: updates
 - [x] bit 2: ticks
 - [x] bit 3: discussions

This means we can align the bitmap to a persons stream configuration. For example if they only wanted to look at updates.

BTW there are some deficiencies in MySQL for handling large bitmaps of variable lenghts, in particular with GROUP_OR and GROUP_AND. Perl is brilliant at this, so it simply means I had to defer this calculation to Perl.

Importantly this solution is fast, and it solves the end of stream problem and the empty stream window problem. The later is critical to how cool this thing looks in first release.

Warning
=================
Account permissions mean that occasionally we will get an active stream window which returns no events.

**Comment by brendanheywood** [comment]
Sweet!

**Comment by scd** [comment]
Yup, really sweet. I am very pleased with how this one worked out.
