### ISSUE TITLE
Generic html loading data attributes

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2008]
Used for lots of different stuff:

```
<div class="stream">
<p class="content">The start of a sentence...</p>
<a href="/stream" data-replace-url="/stream?embed=3" data-replace-closest=".stream" data-replace-find=".content">Load more</a>
</div>
```
- [ ] on page load or on injection of any new content do a quick init for anything with a data-replace attr and add click handler
- [ ] onclick grab the url results
- [ ] optional: walk up to whatever is in '-nearest'
- [ ] optional: walk down to whatever is in '-find'
- [ ] show a greyed loader over the soon to be replaced content
- [ ] replace it when it arrives, remove loader, blur the original click target

Will massively reduce the amount of boilerplate event handling and js we need to download and can be used in a ton of places.

**Comment by scd** [comment]
+1

**Comment by scd** [comment]
I have mostly done this. It is a little bit more complex then I first thought because there are specific things we must do when loading streams

I have changed the steam css so it aligns with this concept
<div class="stream"> 
  <div class="stream-content>
  <button>  // the more button

Also the following data variables are allowed:
 data-replace-container=".stream"
 data-replace-content=".stream-content"
 data-replace-mode="append" // append or replace mode
 data-replace-prepare="stream-prepare" // an optional pre registered function if anything needs to be prepared before getting the html
 data-replace-function="stream-function" // an optional pre registered function if special processing required
 data-replace-resolve="stream" // using the jquery deffered object in case there are timing issues pre registering functions
 data-replace-url=

The basic framework is now in place. There are a couple of UI improvements as you suggested. 

@brendanheywood, maybe have a look at what I have done in common.js. The pre-registered functions are in stream.js

**Comment by scd** [comment]
FYI, this is working for streams in repo.

**Comment by brendanheywood** [comment]
Yeah I was thinking about the loading stuff too and thinking it would be much better to have isolated plugins that simple listen for a 'initialise' custom jquery event, and then do whatever they need to do. so instead of the the streams code calling $('.phototopo').phototopo() then the topo lib handles it, all the stream code does if fire the event and walk away. It shouldn't need to know who is listening

**Comment by brendanheywood** [comment]
done yonks ago
