### ISSUE TITLE
Old dates in stream are wrong?

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2016]
![image](https://cloud.githubusercontent.com/assets/187449/9388939/b9deab32-47ab-11e5-98e7-aed8c5baf361.png)

ie once past a threshold everything is 17 days ago, is this just an artefact of the way we've generated the events on dev or is this a bug?

**Comment by scd** [comment]
This is because the time for this field comes from the record create/update date. 17 days ago was when I ran the migration script in my dev.

I think we should use the event date if it is more than 2 days old. This will get around the problem. I am not keen to change the system create date or update dates.

**Comment by scd** [comment]
fixed in repo
