### ISSUE TITLE
User Profile: Home Crag Selection

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2031]
I just wondered if it would be nice to get informed if a new theCrag member joined the community and selected the same home crag than me. Generally it is hard to detect if there are new members in my area who I may know.

To ease this it would be helpful to select one or more home crag(s) in the profile settings. The system may then inform other users, with the same home crag, that there is a new community member or that one has moved. For the sake of privacy the system should ask the user if he or she agrees.

**Comment by brendanheywood** [comment]
I think this will already be covered well by the new stream events which show new favs in your stream if you also fav those areas.

**Comment by scd** [comment]
Yes this is in the new streams work. Also you can see who has favorited an area using faceted search, for example:

https://www.thecrag.com/climbing/australia/arapiles/favorites

You get to this by clicking on the areas route or ascent statistic then clicking the Favorites tab.

**Comment by lordyavin** [comment]
But a favourite crag is not equivalent to a home crag. E.g. I love the Dolomites and selected them as a favourite but of course this is not my home crag. It is too far away and if there is someone that likes the Dolomites too and lives in Australia doesn't help to get connected with climbers in my area.

**Comment by nicHoch** [comment]
+1 for a home crag property

**Comment by brendanheywood** [comment]
We've gone through a lot of this thinking a while back. Some people live nowhere near a crag but regularly travel to ones where they climb. Some people live near 10+ crags like me, so a region would be better than a crag. There are lots of grey fuzzy areas and simply using the fav concept cuts through them all. Most peoples favourites are crags that they regularly go to. And we keep adding meaning to the fav concept, mostly around notifications, if this gets to much we may eventually split this into 'fav' and a 'watching' concepts.

If we were going to add a 'home' concept I think it would be better to simple make it a town / city rather than a crag and do a reverse geosearch using google maps and do something proximity based. Perhaps we could do this as part of partner finding feature. There are lots of other idea that vaguely cross over this too, such as a friend suggestion feature where we email you once a month with others who lok like you might know based on fav, ticks, mentions etc. 

Regardless I think we sit on this for a while so you can see what we are about to release with the streams stuff as it's pretty cool and then we can come back to this later.

**Comment by scd** [comment]
The find a partner post is the most common topic in forums. I think a lot of websites are doing this, but it is becoming an expectation that thecrag should do this, especially for newbies on the site and on the busier areas such as brisbane.

Potentially the app, when we get around to it, could really help here, especially with location information. This is a really big topic and we are a fairly long way off any detailed development in this area.

I think the fundamental issue is that thecrag has got to get more usage in many areas around the world. There is enough in existing functionality where you could connect with people if there were a lot of people using it in your local area. This comes down to us continuing to improve the general facilities of the site and the users continuing to contribute.
