### ISSUE TITLE
Rob stream feedback: Don't want to see comments on random peoples ascents

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2053]
Not sure we need to split any settings here, but perhaps just change the way it works for all. So a comment on an ascent which creates a discussion is still only shown to the same people who would have seen the ascent in the first place.

**Comment by scd** [comment]
But that is how it was before???? The only difference is it did not bubble to the top of the ascent activity log.

I think it was ok before because ascent comments soon scrolled off the bottom of the list so they did not see them that often. Anyone who messaged their ascent would go directly to their inbox.

What this is telling me is that the dashboard space is very precious. Maybe we should split the personal messages and the streams with an advertisement. This would clearly mark the two different regions. 

I think it is very subjective. If somebody posts and awesome send with video I am sure people would want to see it.

If you really want you can set your streams to be just your friends. No random people.

**Comment by scd** [comment]
I have changed the defaults, so I think this one goes away. Also fixed the bug where you had not selected ticks but were getting them anyway because there was a discussion.

**Comment by scd** [comment]
I am pretty sure this is resolved by the change in defaults. Closing
