### ISSUE TITLE
The grade '3' on boulder is not being interpreted as Font grade in UIAA context

### ISSUE THREAD

**Issue by scd** [theCrag/website#2072]
I think I may have forgotten to parse the FB_ALT grade in UIAA context boulder gear type.

http://www.thecrag.com/climbing/germany/leipziger-kletterschule/route/747148929

**Comment by birgander2** [comment]
I had the same problem when entering boulders graded 4, 5, 5+. In fact in many areas, FB_ALT seems to be used for boulder grades up to 5+, and FB_normal from 6a on. The same concept is existing for routes, rockfax guides are an example.

As a side note: it would be good to show somewhere which system is actually parsed when entering routes. I remarked the problem only because of an "unusual" colour of the formated grade box.

**Comment by scd** [comment]
When you enter the text for the grade in the UI field the UI should query the server and display what the server thinks this grade is. This display should appear just to the right of the text field. If you hover your mouse over this it will tell you what grading system it is. @birgander2 can you give this a go next time you enter a route or upgrade a route.

I just fixed this in my dev so it will be working for next release.

**Comment by birgander2** [comment]
Thanks for the hint, it works! But: Same problem for Finnish context, FB_ALT is interpreted as "Finnish"
