### ISSUE TITLE
Event fav item missing area name:

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2073]
No area name (@nicHoch)

* [ ] https://www.thecrag.com/event/746978877

show up here fine:

http://www.thecrag.com/climbing/italy/sasso-del-drago/favorites

**Comment by scd** [comment]
This is due to somebody favoriting and unfavoriting. The deeper issues is that we currently hard delete favorites, we should be soft deleting. Furthermore we are not tracking unfavoriting as an activity. 

Until these are fixed this event should be filtered out of the display. Hot fixed.

**Comment by brendanheywood** [comment]
Did they fav then unfav ad then refav? They are faved in the facet and have been all along so that doesn't seem to make sense? That event should exist?

**Comment by scd** [comment]
The symptoms are as if they fav, unfav, fav then unfav.  This was the 'and' part of it.

I think there is something else going on as well because the favorite in the facet search is still there:

http://www.thecrag.com/event/746569248

Which is actually a sub area.

So my suggestion of what happened is as follows:
  * favorited Sasso del drago
  * unfavorited Sasso del drago
  * favorited Sasso del drago
  * unfavorited Sasso del drago
  * favorited sub area Settore Drive-in

**Comment by brendanheywood** [comment]
Would be in apache logs if not in Db logs

**Comment by scd** [comment]
A lot of work to go to for something that is fixed. I created a similar scenario in my dev and it broke in a similar way. The only difference in prod is the final favorite of a sub area. It all consistent to me.
