### ISSUE TITLE
fr_alt ticked as fr

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2093]
Quite minor bug: when I tick a route of, let's say grade 5+ (fr_alt), it will be 'translated' to 5b+ (fr). The fb_alt grade can even not be selected manually from the dropdown. With fb_alt it works correctly.

**Comment by scd** [comment]
For debugging, here is an example:

https://www.thecrag.com/climbing/france/aiguille-du-midi/route/19862545

**Comment by scd** [comment]
hot fixed. 

There were a couple of issues here actually. I changed the logic a little so that you can tick ALT grades if the route is configured with an alt grade. I have applied this to all _ALT grade labels so we don't have to configure each individually. I also excluded the Distance and Exposure ratings as they should not be tickable grades.
