### ISSUE TITLE
Round avatars everywhere?

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2099]
Do we want this?
- [x] refactor css as this is currently a bit tangled with other templates (eg linkClimber)
- [x] fix the nesting to avoid the bug in iphones with rounded corners on images
- [ ] if we are going to roll out round avatars everywhere then we can save some bytes by doing this server side as well to remove data https://github.com/thumbor/thumbor/wiki/Round-corners (bonus points, I can do this in the templates just make sure the filter is turned on)
- [x] also thinking about setting a max bytes for specific avatar sizes, probably 2k for the standard size

The only place I probably wouldn't want this is in the profile page for the person big pic, and probably in the climber cards in the leaderboards but will trial it and see.

**Comment by scd** [comment]
I am not convinced we should do round avatars everywhere. I love them in the streams, mainly because they work much better in the avatar train because of a more distinct edge. At the moment I am really happy just using the rounded avatars in the streams to brand the streams.

Does the server-side rounded edges use a transparent background - it does not look like it to me. In this case the avatar train will look crap, unless I am missing something here?

When we start pushing out crag avatars, I think it is worthwhile considering turning account avatars into rounded avatars. But until then I do not see it as a priority.

Won't thumbor solve the max bytes problem when we give the avatar a dimension? It won't set a max bytes, but it will produce an efficient image.

We need to refactor css for a lot of reasons, but this should be done properly with a lot of discussion and a style guide.

**Comment by brendanheywood** [comment]
It would still have the css for round corners and borders, but instead of cropping the image which contains data its cropping flat white which compresses really well. Any way to sit on this for ages

**Comment by brendanheywood** [comment]
I'm happy to sit on this I meant.

**Comment by scd** [comment]
Ok, I get it. Yes let's sit on this

**Comment by brendanheywood** [comment]
This is pretty well done, just will be a long tail of migrating bits of to the new template
