### ISSUE TITLE
"View your trips" broken

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2122]
When I click on a trip in the list of my trips, I get:

`Apache Module Load Portal Error: Error: Error during compilation of : Global symbol "$sponsorRef" requires explicit package name at line 152. Stack: [/usr/local/share/perl/5.14.2/HTML/Mason/Interp.pm:639] [/opt/CIDS/perllib/CIDS/Application/Portal/GeneratePortal.pm:350] [(eval 3223):1] [/opt/CIDS/perllib/CIDS/MyApache2/WebPortal.pm:446] [(eval 3223):0]`

**Comment by scd** [comment]
hot fixed

**Comment by birgander2** [comment]
It was working, but after I haved changed the location now I get (the list itself is fine with the new location):
Apache Module Load Portal Error: Error: Can't use string ("") as a HASH ref while "strict refs" in use at line 154. Stack: [:154]

**Comment by scd** [comment]
I will have to look at this again in a couple of days.

**Comment by scd** [comment]
So I don't have to look again, it is in this event here:

http://www.thecrag.com/event/775664715

But they are in the ascent facet search:

http://www.thecrag.com/climbing/spain/mallorca/route/381040602/ascents/?sortby=when-climbed,desc

(which I think may be because this display use the route grade)

I will have to investigate, but my guess is the grade is not being saved on the ascent. The _ALT grades do have some special case programming.

I am unable to put any time into this for at least a couple of days

**Comment by rouletout** [comment]
This is not supported anymore, closing
