### ISSUE TITLE
Error message when adding trip

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2126]
Added a trip and got:
"Apache Module Load Portal Error: bad profile uri"
The trip apparently has been added, although "restricted" despite of me creating it as "public".
Got the same error for adding another trip.

**Comment by MelwinQ** [comment]
PS: There seem to be two options of creating trips: I used Action -> Start a climbing trip.
There, one can choose "Access Restriction", which seems less differentiated than the options in the dialogue when adding a trip starting from the trip table.

**Comment by scd** [comment]
We are having difficulty finding the time to support trips properly at the moment. I will try and find the time to remove the server errors, etc. However a lot of the trip functionality is no longer part of the main site (eg ticking).

The problem was that it did not get used enough to justify my time and development effort when compared to other features that are crying out to be finished.

Potentially trips could be awesome on thecrag, but it is going to be a while before we get there.

**Comment by MelwinQ** [comment]
No sweat, you'll know the priorities. I like the feature, though.
However, when you tackle it, you may want to check:
- I could't find a way to delete a trip. Either, there is none or it is hard to find.
- Entering a location for the crag makes "Loading..." appear at the top of the page, but nothing happens

**Comment by rouletout** [comment]
Not existing anymore, closing
