### ISSUE TITLE
Gym feature show no ascents

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2128]
I organised a gym as gym->sector->feature->routes. The ascents / edits are shown everywhere, but not under the feature listing. [Example here](http://www.thecrag.com/climbing/germany/oberbayern/area/612839985)

**Comment by Mdemaillard** [comment]
The activity stream does work under the link provided, as well as seasonality graph. 


What does not is the grade graph overview for the Sectors and Features
![image](https://user-images.githubusercontent.com/60388146/76517786-a1aaf980-6466-11ea-8f47-6a5f6f213ab6.png)

If the issue was the Stream, candidate for closure.
