### ISSUE TITLE
Photos of region not shown

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2138]
I recently uploaded 10 photos to [Sächsische Schweiz](http://www.thecrag.com/climbing/germany/sachsische-schweiz), now there are 24. Nevertheless, my recently added photos are never shown in the region display, only when I dive in further in the index. Is that a normal behaviour? I don't think so, since other (older) photos are shown!?

**Comment by scd** [comment]
I think photos need to be reviewed. This is a process we plan to dump and just get the community to review.
There may be something else going on because even though they need to be reviewed, I thought they still should show occasionally, just at a lower priority. 

Yes they do show at route level then they do show at lower index levels. 

I think you are right, something seems to be not working properly.

**Comment by scd** [comment]
@birgander2 are your photos displaying properly now in Sächsische Schweiz

**Comment by birgander2** [comment]
Sort of, yes, thanks! However, after some reloads (with empty cache!) I have the strong impression that still certain images appear much higher priority than others. "browse all photos" shows correctly 25 photos, but after about 10 reloads the region index (showing 4 at a time) has cycled through only maybe 10 of them. 2 photos are basically always among those 4 shown. But anyway, not really so important...

**Comment by scd** [comment]
Yup, there is an old back end process we need replacing which causes this. Currently we manually review all photos and categorise images which can result in different priorities. The process involves extra work from us and is not transparent, so it is not the best process in the world. It suited us many years ago when we had not so many photos. Now not so good.

**Comment by scd** [comment]
I have made an update in my dev. Closing
