### ISSUE TITLE
style "mixed"

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2150]
A trad route with bolts is currently classified as "mixed".
I am not a native speaker, but I have a different notion of "mixed climbing" (https://en.wikipedia.org/wiki/Mixed_climbing). As far as I can tell, this style (i.e. using ice tools on rock and/or ice) is not yet covered and could be added. 
"Trad+bolts" probably needs a different label - what about "Trad+bolts"? However, concerning your guideline question "What kind of gear do I need?" this category is obsolete, as it is just "trad", since I need trad gear to climb, bolts or not.
If you decide this category should persist, adding it to the dropdown when adding a route would be nice. Otherwise, a trad route with an unknown number of bolts cannot be entered correctly.

**Comment by birgander2** [comment]
+1  

I was also already wondering about the strange "mixed" definition on thecrag, for me "mixed" means rock / ice combinations involving some drytooling (see wiki, even has its own grading system). Anyway, since partly bolted adventure climbs involving trad are not so seldom, some kind of label would be nice.

**Comment by brendanheywood** [comment]
thanks guys, I'm going to close this as a duplicate, can I get you both to have a read through #1457 and add any comments you feel are missing to it please?
