### ISSUE TITLE
Search for climber/climber: unexpected results

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2181]
Using the search form for climber for "mel"
http://www.thecrag.com/climber/search?S=mel&P=7478674&Search=search
yields
MELLBERRY (private account)
Should private accounts really be visible in that search?

Conversely, my account (melwin) is not found. Is this related to #1849?

**Comment by MelwinQ** [comment]
with all due respect, "unrespected" should read "unexpected".

**Comment by brendanheywood** [comment]
There is a lot of vagueness around exactly what a private account means. My take is that private accounts should be searchable, and you can go to the account page, but you just don't see much. Otherwise how can you connect with someone? 'private' as a concept should be scrapped and replaced which more meaningful finer grained profile options.

btw you can edit your previous github comments to fix typos

**Comment by brendanheywood** [comment]
I'm going to close this, see #1704 - for the ongoing discussion on the privacy model, and #1849 for the search fuzzy logic
