### ISSUE TITLE
PDF Generation Numbering Wrong

### ISSUE THREAD

**Issue by safarir** [theCrag/website#2183]
When a route in a area does not start at 1, the PDF route numbering still start at 1 which cause all the images to be wrongly numbered. This can be **really dangerous** as I discovered when I tried to climb a 5.6 which was more like a 5.10

This should really be considered a critical BUG and be fix ASAP.

Example:
[https://www.thecrag.com/climbing/canada/gatineau-hills/area/11925301](https://www.thecrag.com/climbing/canada/gatineau-hills/area/11925301)

**Comment by scd** [comment]
Ahh, I see what is going on. When routes are mixed with areas the numbering on the website is different from the numbering on the PDF. In both cases the topo aligns with the numbering on the website.

Yes this is problematic and a scarey bug. Thankyou for pointing this out. I will try and find some time to work on this tonight, otherwise it might be a couple of days before I get a chance.

**Comment by scd** [comment]
@safarir I have done an emergency fix. Could you please have a look at the following url which will dynamically generate the PDF:

https://www.thecrag.com/climbing/canada/gatineau-hills/area/11925301/pdf

And let me know if it is ok. 

Please note that we have still got to work out what to do with the pre-generated pdfs. They normally refresh themselves in a month, but that is too long.

BTW, thankyou for pointing out this bug as it has a huge impact on the community. It has come about because of a couple of factors and assumptions. The essence of the bug is that the PDF generation did not have exactly the same algorithm for calculating the topos.

We need to think about a more robust way of doing this so we don't have to align algorithms.

**Comment by safarir** [comment]
@scd Thank you for your awesome job and your quick fix ! This is really appreciated
