### ISSUE TITLE
Protection rating X clash with Saxon grades X

### ISSUE THREAD

**Issue by scd** [theCrag/website#2201]
Protection rating X clashes with Saxon rating X. What to do?

**Comment by brendanheywood** [comment]
Is this actually a real issue, are saxon difficulty grades used side by side with the X danger grades?

**Comment by nicHoch** [comment]
No that is no real issue because the us protection rating is not used in Germany and particularly not in Saxonia. 

I would propose to implement the E system E1 E1/E2 E2 E2/E3 E3 this is used in Germany Switzerland and Austria not at every Crag but at some.

It is not used in Saxonia but if this grading system is in place maybe some user will adopt that for Saxonia as well. Not sure but more probable as the US system.
Nicky

Am 11. Mai 2016 11:00:28 MESZ, schrieb Brendan Heywood <notifications@github.com>:
>Is this actually a real issue, are saxon difficulty grades used side by
>side with the X danger grades?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/2201#issuecomment-218401850

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by thorstencho** [comment]
To introduce a protection rating system that is different than the traditional one and hence more informative - like E1 to E3- would be cool and revolutionary. Maybe we´ll write history :-)

**Comment by scd** [comment]
It sounds like we should implement the E protection rating system and then decide later where and how it should be used.

**Comment by scd** [comment]
What is the difference between the E1 to E3 protection rating system and the E1 to E5 exposure rating system used in some countries in europe?

**Comment by nicHoch** [comment]
To be honest: i do not know. I looked a bit around and obviously there 
is no common standard. In some parts it is E1 to E3 with slash grades in 
other parts up to E5 or E6.

Am 17.05.2016 um 05:27 schrieb Simon Dale:

**Comment by georg-d** [comment]
For E1...E6 I found quite similar definitions as for S1...S6. I did not really get the differences between the grading schemes E1...E3 and E1...E6 and S1...S6 but I got the impression the definition is either more covering multipitch alpine routes or more single pitch sports / mixed routes.

**Comment by georg-d** [comment]
> It sounds like we should implement the E protection rating system and then decide later where and how it should be used.

**I would appreciate if _any_ protection/danger rating system(s) would be implemented _soon_, because without them, users do several hacks/workarounds,** e.g. changing a route from sport to mixed or trad to show "it's more demanding than pure sports" (despite you can't place any nut or the like), increasing the UIAA grade so the hardest move is still easy for the route's grade,... In contrast to grades in description text areas, these workarounds are not transparent, so they are not easily reversible when protection ratings are implemented in the future => the longer we wait, the worse the data.

**Comment by scd** [comment]
After next release we will have added

 * R protection rating scale
 * S protection rating scale
 * Commitment level

We already have YDS

 * YDS protection rating

This leaves two more systems referenced in this issue

  * E1-E6
  * P????

How important are the remaining two?

**Comment by lordyavin** [comment]
I'm not aware of P but the British E system is relevant in Europe.

**Comment by scd** [comment]
I think I am still confused with some definitions. Is the British E system the same as the British Adjectival grade which we have implemented up to E11 or is there a different British E system.

**Comment by lordyavin** [comment]
Should be the same I think.

**Comment by rouletout** [comment]
Fixed with release 88
