### ISSUE TITLE
bouldering on profile page should pick the most used grading system

### ISSUE THREAD

**Issue by scd** [theCrag/website#2260]
from user ...

In all the other tabs (e.g. the sport one) it looks like, for the the route by grade overview, the system decide to use the most used grade system in the ascents.
In the boulder tab it is forced to V-scale and it is not possible to change it (forcing it to, as an example, Fontainebleau is only affecting the custom tab).

**Comment by birgander2** [comment]
Or, even better: let the user configure two grading systems, one for routes and one for boulders.

**Comment by brendanheywood** [comment]
Yes it should be configurable but should also have a sane default. We have enough grade system metadata to do a great job of this automatically. Also the be strict there should be a configurable grade system preference for all gear types, ice, alpine etc

There is a few overlapping issues here, eg by default I think that all grades shown should be in their native grade, not your local grade. ie if it happens to show some boulders in France and some in Aus then I'd expect those to each be in their local grade. The issue here is that we need to clearly show the local system if it is different to the expected grade. We already do this in list view based of the country of the crag, we just need to make this logic consistent for profiles too.

**Comment by Mdemaillard** [comment]
might have been covered by Release 81 - Universal Grade Conversion update

**Comment by scd** [comment]
I am closing because this can now be controlled by the user.
