### ISSUE TITLE
Top rope color in gradeband in page header has lost it's color

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2302]
Think this was related to the translation work, the css class is now a raw key and was previously a human readable string so the class has change from class="top rope" to class="toprope"

**Comment by brendanheywood** [comment]
current:
![image](https://cloud.githubusercontent.com/assets/187449/17313945/b6164262-58a3-11e6-82a8-e8c9f37b1186.png)

fixed:
![image](https://cloud.githubusercontent.com/assets/187449/17313965/e528fd60-58a3-11e6-9261-1b2cbecba414.png)

**Comment by brendanheywood** [comment]
ok now a knock on bug with tags missing color:

![image](https://cloud.githubusercontent.com/assets/187449/17314000/3126145a-58a4-11e6-94b6-1ae02bec9afa.png)

**Comment by brendanheywood** [comment]
@scd I think this may need a template data change and am a bit unsure of what the proper fix is, also this affects a couple other stream templates too:

![image](https://cloud.githubusercontent.com/assets/187449/17314085/f5789cec-58a4-11e6-8e2d-fd4a5015083a.png)

eg in minor/routeStyle I think $route->{style} should be a raw key and not a lang string

**Comment by scd** [comment]
CSS needs refactoring to align with key stubs.

Having
```
span.tags.top.rope {
```
in the css and triggering via `class="tags top rope"` is not great practice.

We are using the translations as a refactoring opportunity. Translation stubs are being devised programattically so we should use them now.

In the css it should now look like
```
span.tags.top-rope {
```
in the css and triggering via `class="tags top-rope"`.

I am holding off in the css refactor for a while because there are other issues. For now I have just fixed in the template. 

Fixed in repo.
