### ISSUE TITLE
On manual account creation page have a password hide / show toggle

### ISSUE THREAD

**Issue by bricechilders** [theCrag/website#2313]
Don't know if [it was intentional](http://www.lukew.com/ff/entry.asp?1941), but when I created my account, my password was visible in the password field. Made me anxious and look over my shoulder. I suppose it is less trouble for the user than typing in the password twice to make sure it is consistent without seeing it - but since the user is giving their email anyway, if they mistype in a single hidden-password field and find they can't log in with that password, password reset should be no big deal anyway. At least, it would be nice if there was a "Show Password" checkbox that was unchecked by default.

Example: http://imgur.com/a/hHORt

**Comment by scd** [comment]
@bricechilders we should probably fix that as it seems to be standard to have it hidden by default.

From a personal security note it is far more secure if you create a unique password for every site, in which case it would not matter.

**Comment by brendanheywood** [comment]
No this was an explicit decision, pretty well every usability study for the last 10 years has consistently found that showing password at creation time (but obviously not later when entering them) improves the usability of the page, reduces the change of typos and so the end result is actually better security. This is in the same category as duplicating the email (or password) field which lots of sites still do because they think they should, but it's a horrible user experience.

This has been in place for a couple year but very occasionally we do get concerned people asking about it. I do agree that the show password checkbox would make some people more comfortable so I'll add that to the todo list and rename this issue accordingly.

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/77256679-62f01d00-6c78-11ea-88ce-a5ee12ca6917.png)

has been implemented
