### ISSUE TITLE
Small tag icons next to routes

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#2358]
Hey,

just thought about, that it would be great if there would be small tag icons at the crag overview next to each route, if there are tags assigned. This would give a nice overview what kind of climb it is and it would motivate to assign tags to the routes itself.

Just made a example image of what I mean:
![unbenannt-1](https://cloud.githubusercontent.com/assets/3040689/18193217/bd1c8a30-70db-11e6-9770-78305bda2932.jpg)

New icons should be created for bouldery or endurance routes. Same would be great for boulders for a sitstart, standstart or laydown start.

**Comment by birgander2** [comment]
See #2304 in fact this is exactly what I mean.

**Comment by Drazhar** [comment]
#2304

**Comment by lordyavin** [comment]
Duplicate of #2304

**Comment by Mdemaillard** [comment]
Thanks, and True i use that when i close without merging any content. 
I do the opposite when merging content to limit the number of emails sent. (i.e. sparing the email on the dup being closed, but still referencing it in the "main issue")

Not sure if one or the other is more worth since i couldn't find more function when two issues are marked as duplicated rather than just referenced.
