### ISSUE TITLE
Translations: welcome e-mail

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2361]
The links and text at the bottom of the welcome e-mail should also be translated. Ulf should be added to the list of members.

<img width="512" alt="screen shot 2016-09-02 at 17 46 18" src="https://cloud.githubusercontent.com/assets/19162952/18197998/37810162-7135-11e6-9d23-426bc3631f4a.png">

**Comment by scd** [comment]
Hmmm, I thought I had done this. Obviously a bug somewhere.

Actually I think the email footers are translated to the language associated with the persons account. At the moment you cannot select German but the browser has.

So we need to work out the business rules for emails, so the footers and the content are consistent.

Note that the source of the problem is that the footers are added to the email later. Emails are pushed to a queue, and when they are dequeued, various processing happens including adding footers. It is at this point the system looks up the persons language for the footers.

**Comment by scd** [comment]
This needs language to be passed as a parameter to the email queue. There framework was there but was missing from some emails.
 - [x] welcome
 - [x] following
 - [x] pdf
 - [ ] bulk
 - [ ] import logbook dequeue
 - [ ] discussion notifications
 - [ ] promote editors

**Comment by rouletout** [comment]
This looks all good, closing
