### ISSUE TITLE
Translations: German grammer issue / question (again)

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2367]
I ran a few times in a different German grammar issue. We use quite often “area type” as variable, in German this can be a female, male or neutral subject which changes the “this” (in this area / this sector / this cliff). I tried to navigate around it by modifying the sentences as far as possible but some really don’t make sense anymore. I also don’t like the solution to list the options like dieser / dieses / diese as for the user it doesn’t make sense in the context (he doesn’t know what other options there are).
Do you have any ideas how to solve that?

An example is the key "template.maps.contact-us-if-know-location”

**Comment by scd** [comment]
@UFU608 can you please give a couple examples in German of what the system is outputting and what it should output. So I need four things in one example
 - the key
 - an example of the german text for this key being wrong
 - an example of the german text for this key being right
 - the correct german text

**Comment by UFU608** [comment]
- For the key given above the English is:
...this crag... / ...this cliff... / this sector / this area etc.

- In German the result is always dieser (or whatver you put) Sektor / dieser Klettergebiet / dieser Felswand / dieser Gebiet

- In German correct would be: dieser Sektor / dieses Klettergebiet / diese Felswand / dieses Gebiet

**Comment by scd** [comment]
So different area types have different genders.

Hmm, this could be a problem to do properly because now the translation system needs to know the gender of every noun in German.

Idea 1
====

Can we manage this by dumbing down the sentence differently in German. For example in English it is currently
```
Please contact us to let us know where this {areaType} is.
```

But we could change it to 

```
Please contact us to let us know where this area is.
```
(In otherwords just getting rid of the area type and using a generic area).

Idea 2
====

Alternatively we could have a key for `this-area-type`, so we could do something like:

```
Please contact us to let us know where {thisAreaType} is.
```

However this solution will only work for languages where the word that changes gender is next to the noun. So I am 

Idea 3
====

Add some complexity to the translation software

```
Please contact us to let us know where {g system.this, areaType} {areaType} is.
```

Before I implement something like the third idea we would have to discuss internally. In the meantime go with idea 1, as it does not lose too much and is better than getting the wrong gender.

**Comment by nclementel** [comment]
FYI: same problem in Italian.

**Comment by UFU608** [comment]
What if we use the actual area name? Names have no articles and the problem would be gone. Thoughts?

**Comment by MelwinQ** [comment]
I'd favour Ulf's last suggestion
"Please contact us to let us know where <the Matterhorn> is."
as it avoids parts of the trouble.
However, sites with plural names still prove difficult, I guess also in English:
"Please contact us to let us know where <the Shawangunks> is."

**Comment by UFU608** [comment]
Do we have an agreement there? Just to make sure before we proceed with translations...

**Comment by scd** [comment]
Yes I am in favor of simlier wording. Please make an issue note whereever you have had to do this in so I can also simlify the english

**Comment by UFU608** [comment]
The following keys were updated:
template.action-area.update-permissions-area-type
template.maps.locate-area-type
template.action-area.update-area-type
template.area.please-contribute
template.node-info.add-info

**Comment by UFU608** [comment]
all but the last one were changed to "areaName" - last one has no variable anymore

**Comment by scd** [comment]
fixed
