### ISSUE TITLE
Translations: Capitalization wrong and parts not translated

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2382]
In attached screenshot "Ticktypen" should be capitalized and "by Ulfi" should be "von Ulfi"

<img width="1009" alt="screen shot 2016-09-16 at 16 28 32" src="https://cloud.githubusercontent.com/assets/19162952/18578421/ca6d3608-7c2a-11e6-9a74-e60ed4dad727.png">

**Comment by MelwinQ** [comment]
Same with "felswand" in 
felswand hat noch keine Untergebiete oder Routen!
(cliff has no subareas nor routes)
e.g. at https://www.thecrag.com/climbing/switzerland/alpen/zentralschweiz/uri/area/982764840

**Comment by MelwinQ** [comment]
Related but also different, one line below the previous example:
Solltest du den / das felswand kennen, füge bitte deine Informationen hinzu
should be 
Solltest du den / das / die Felswand kennen, füge bitte deine Informationen hinzu.

As discussed in #2367, using the node name instead of the area type may simplify the issue:
Solltest du "someRocksName" kennen, füge bitte deine Informationen hinzu.

**Comment by scd** [comment]
fixed in simon's dev
