### ISSUE TITLE
Policies: Acceptable site behaviour vs. Offensive Content

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2386]
At the bottom of the page we link to certain policies but not directly to the offensive content policy. Should we switch the one for acceptable site behaviour with the one for offensive content? The acceptabel site behaviour has more the look and feel of a "help document" and not a policy.

https://www.thecrag.com/processmap/offensivecontentpolicy

**Comment by brendanheywood** [comment]
Can we just merge these?

**Comment by UFU608** [comment]
Agreed, would be best to put in "policy" style and not as a help article. The policies are translated too.

**Comment by brendanheywood** [comment]
@rouletout in the interim do we want to link to the offensive policy?

Do we also want to clean that up and turn it into a new policy page instead of a process map?

https://www.thecrag.com/en/copyright
https://www.thecrag.com/en/terms
https://www.thecrag.com/en/privacy
https://www.thecrag.com/en/offensivecontent <-- new?

**Comment by rouletout** [comment]
Leave that until we cleaned up our terms

**Comment by brendanheywood** [comment]
@rouletout can we close this now?

**Comment by rouletout** [comment]
Yes, closing.
