### ISSUE TITLE
undue karma?

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2397]
Although I love pushing my karma-rank, it seems I have been credited some unjustified points.
In my "Pending karma" (still in English, btw) I can see many entries like
Update Principle Grade: Riesentreppe
for every route I have re-ordered, although I have not updated their grade.

**Comment by scd** [comment]
Yes this is a blow back from an update to the way grades are being stored. There was one step in the analysis I missed (or made the wrong assumptions) which meant users who bulk edit an area for the first time since the change get credited with a hidden update to the registered grade.

Given that it is a once off issue for each route, I don't plan to do anything further. Thankyou for letting me know, though :)
