### ISSUE TITLE
Review top end grades and ensure future growth / stats aren't an issue

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2417]
So there's been a lot happening lately at the high grades including a possible new V17 boulder:

http://www.rockandice.com/climbing-news/nalle-hukkataival-sends-world-s-first-v17

and Ondra sent the first 5.15c

http://www.climbing.com/videos/adam-ondra-climbs-change-the-worlds-first-515c/

So we need to:
- [ ] make sure the V17 is in our list (15c already is)
- [ ] make sure there is plenty of room for inevitable future growth
- [ ] if we keep squeezing future harder grades into smaller and smaller slices of the remaining 'grade space' will this affect stats in any way? ie do we assume that the difficulty jump between two grades is consistent along the whole spectrum, or is this simply too hard to validate?

https://www.thecrag.com/article/Grades

**Comment by scd** [comment]
I don't think there is any fundamental reason why we cannot add harder and harder grades. The grade space is open ended. We may choose to add another grade band above elite, otherwise the elite band can just grow.

Configuration changes needs to be part of a release. The time consuming part is getting the conversions right. I think we should get these reviewed and the elite level.

**Comment by brendanheywood** [comment]
Ok well this issue is just adding V17 and the rest is fine. I don't think we'd ever want an extra band above elite, this is all elite stuff and having 5 consistent bands is nice

**Comment by Mdemaillard** [comment]
V17 is in, in elite band. 
![image](https://user-images.githubusercontent.com/60388146/76420648-1de00700-63ab-11ea-8cc2-7aba77583f3f.png)
Closing
