### ISSUE TITLE
Install facebook pixel tracking

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2439]

**Comment by lordyavin** [comment]
Does this implementation affect the data of non-facebook users? Are there any privacy issues for me if you release this?

**Comment by brendanheywood** [comment]
This might help:

"The Facebook pixel only tracks traffic if the user is logged into Facebook at the time of the website visit."
https://www.facebook.com/business/help/community/question/?id=10154238916686704

**Comment by lordyavin** [comment]
Is this a technical limitiation or by design?

**Comment by brendanheywood** [comment]
It's not a technical limit it's how the service works. If facebook (or google via google analytics which we also use, or perhaps even via google maps, or even gravatar or any other 3rd party services we utilize) wanted to be evil they could, but they currently are not to the best of our knowledge. The point of facebook pixel is to track users coming from facebook posts into our platform to measure how effective they are. If you don't use facebook you aren't really in the equation at all.

If you are really concerned there is nothing stopping you from using a browser plugin like ghostery
https://www.ghostery.com/

**Comment by lordyavin** [comment]
Unfortunately Ghostery may be part of the problem. The company behind the add-on is part of  advertising industry and sold user data. There is an [article](https://www.heise.de/tr/artikel/Die-Geister-die-ich-rief-1890700.html) from the well-respected heise publisher about this issue.

Regarding GoogleAnalytics: It is possible to [opt-out](https://tools.google.com/dlpage/gaoptout) from it. So no issue for me but maybe for others that don't know about that add-on. This add-on was provided by Google after a deal with the the German commissions for data protection and freedom of Information (2011?). In these days the add-on wasn't available for every platform/browser combination and therefore the commission defined new rules for webmasters and website operators to be compliant to German data protection laws. I'm not a lawyer and I'm not sure if this applies to theCrag but the site is available in Germany, translated into German and allows Germans to join the community and contribute content. Because of this I would expect that data handling of theCrag is conform to the German laws.

I know that such per country rules/regulations/laws are hard to cope with for an international website but you (the theCrag team) have to face and master such issues if you want to provide the service e.g. in Germany. 

I also know that most people from other countries role their eyes because of the strict data protection laws and rules in Germany. IMHO this rules protect the unaware and uninformed people. Unfortunately the rules and laws are often too old, outdated or hard to apply on internet services. But they exist and may advance to match problems the internet raises.
