### ISSUE TITLE
Structured Tags: inheritance question / issue

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2450]
Some structured tags are inherited from an area to e.g. a cliff such as rock type, others are not (e.g. No Camping, No Fire). My personal view is that tags should behave the same as it is not clear for the user which ones are inherited and which ones aren't. Easier to delete one from an underlying cliff if it is not correct....

**Comment by brendanheywood** [comment]
See also #1714.

I see this as working in one of a couple ways:

1) any tag can be negated. If someone add Kid friendly to a crag, then one cliff can explicitly remove that tag which stops it inheriting. I see this as the most difficult to model, and the most difficult to clearly communicate in the UI, and it may have some performance issues.

2) only certain tags can be negated, and they can only be negated with another tag (rather than removed). eg Camping is allowed at the crag, but a cliff has No camping, or Dog friendly vs No dogs.

3) Similar to above, but taken a step further and having mutually exclusive groups around a particular theme. For instance a crag could be mostly 'Any tide' but one area is 'Low tide' and another is 'By boat'. These are simple negations.

If we introduced either 2) or 3) then we must be pretty sure that in almost every case nobody will want to use the tags together. For instance I think we discussed rock inheriting and being override-able like this, but there are plenty of cliffs or even individual routes which have two very different rock types in them.

If we really did want to be able both override a tag AND have multiple set then we could just say the tag state in the lowest node wins. eg if we had

Crag (sandstone) > Cliff (limestone) > Boulder (granite + limestone)

... then the final result would be "granite + limestone"

Performance wise I think we can make it work, we just need to give each tag assignment a weight which is it's node depth and only grab the max(depth) tag(s) for each unique set.

IF we implemented this then each set / theme would get a flag to say if it's mutually exclusive or not, and we'd shuffle tags around as needed. The sets which I'd say would be mutually exclusive are:

* rock type - lots
* Sun - 4 tags
* Wind - 2 tags
* Rain - 2 tags, (note Brittle when wet, and dries slowly would be in a new non-mutually exclusive group)
* Camping - 2 tags
* Fires - 2 tags
* Dogs - 2 tags
* Legality - 7 tags
* Walk in - 9 tags
* Water access - 3 tags

I also thought this might also be an opportunity to do a quick analysis of which tags are being used. I've just added another report and there is only 1 tag not being used 'Peridotite'. I was a bit surprised to find that there wasn't any obviously unused tag themes / sets. Probably the least used tag set is 'condition'.

**Comment by rouletout** [comment]
all clear, closing
