### ISSUE TITLE
Stream not correctly detecting pseudo TLC's

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2451]
https://www.thecrag.com/event/1016417880

![image](https://cloud.githubusercontent.com/assets/187449/20265071/08ba2882-aac3-11e6-92c0-bcdf4c5e5a04.png)

the node heirarchy is:

* Australia (country)
* NSW & ACT (region)
* Hunter Valley (region)
* Bulahdelah (region)
* Hoppy's Cave / Main Cave (area)
* Trackside cave (area)

I would expect this in the absence of a TLC to choose the first non-region node, ie 'Hoppy's Cave / Main Cave'

**Comment by brendanheywood** [comment]
See also #1288

**Comment by scd** [comment]
Business rules are TLC is the first non region/area/unknown so this is correct according to our business rules.

**Comment by brendanheywood** [comment]
Yeah I know, I'm reiterating that the business rules themselves are wrong. They should be:

* TLC is the highest crag in the node ancestor chain
* If there is no crag ancestor then it's the highest non-region node

**Comment by scd** [comment]
As you pointed out the other issue #1288 which refers to changing from the first non Region/Area/Unknown to the first non Region/Unknown. If you want this to be just the first non Region then please add comment to #1288 because it will be lost in this issue.

We are not going to update historical events, so I think that this issue will be solved when #1288 is solved. I therefore think we can just close this as a dup. What do you think?

**Comment by brendanheywood** [comment]
closing as dup of #1288

**Comment by scd** [comment]
Try this:

https://www.thecrag.com/api/config/i18n/de

**Comment by brendanheywood** [comment]
Wrong issue?

**Comment by scd** [comment]
ha ha
