### ISSUE TITLE
Translations: keys for followers/following

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2486]
In Italian "followers/following" keys change if you are looking at your profile page or visualising someone else one.

**Comment by brendanheywood** [comment]
@nclementel can you please provide urls for this? You can force the lang in the example with ?lang=it

**Comment by lordyavin** [comment]
There is a problem with the German translation too.
1. "followers" (noun) > "Dir folgen" (pronoun + verb)
2. "following" (adjective) > "Du folgst"  (pronoun + verb)

I looked into the translation UI and found that the strings are hard coded and I didn't find different keys for looking at the users own profile and others profiles.  So if I look at mine it is okay to display "**Du** folgst" but if I'm looking at someone else's profile it should display "**Er|Sie** folgt". The same for followers: "**Dir** folgen" vs. "**Ihm|Ihr** folgen" 

So the template must handle of the user looks at its own or a foreign profile and if it is a foreign profile it must use the gender specific pronouns.

One way to handle that would be to omit pronouns but that maybe not possible in every language. E.g. in German the term "Followers" is already widely used and known but there is no good translation for following.

Just had a quick view onto twitter and they use "Follower" and "Folge ich" (I follow) and the don't switch the pronoun. Maybe is "Ich" a good compromise. I does not depend upon sex and it works if I'm looking at my profile and the profile of others.

**Comment by Mdemaillard** [comment]
Seems sorted in german, french, spanish, for both my own and someone else's profile the key is "pronoun free" (german example below)
![image](https://user-images.githubusercontent.com/60388146/77001807-316b0f00-6963-11ea-9cbd-6085e3651de1.png)

in italian it still includes "ti", which is probably incorrect "they follow  you" for someone elese's profile.
![image](https://user-images.githubusercontent.com/60388146/77002070-97f02d00-6963-11ea-8fa4-313d84ed29d9.png)

Anyway definitely a polishing case rather than a bug. 
I am sure some italian can propose a pronoun-free text, after 3min on google translate and no italian knowledge i propose 
segui / seguaci

**Comment by rouletout** [comment]
Fixed in line with what our translator recommends and what Instagram is doing in Italian:
- Seguiti
- Followers
