### ISSUE TITLE
Should be able to lock any node type, eg region

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2495]
And ideally hotpatch and then swap sutherland back to a region:

https://www.thecrag.com/climbing/australia/sutherland

**Comment by scd** [comment]
There was a bug in the permissions assignments rather than a fundamental limitation here. This is fixed on my dev.

I have also taken this opportunity to document proposed changes to the permissions system.

https://docs.google.com/document/d/1NGNvNOZwjQQeX2hO9-RcrVGid-KxHA6nUViRuWkKx3E/edit#

It is actually not that big a change as most things are already in place. If we agree with the business rules in the document then I will start to make the changes. Please note I don't want to do a major redevelopment but rather just make some minor tweaks so we can make the thing more transparent and logical.
