### ISSUE TITLE
Ascent rating scores can be negative, and these should not be counted

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2529]
One of our principals is that a tick should never penalize you. Regardless of the parameters we tune, because of the inverse log stuff we will sometimes end up with ratings which are negative. These individual scores should not drag down your other scores and should be ignored, or "min(score, 0)"

This is gara with default decay params:

```
+------+------+--------+-------------------+-----------+
| V    | Rank | Rownum | Login             | ID        |
+------+------+--------+-------------------+-----------+
| 2995 |    1 |      1 | ALANEZZY          |   7888746 |
| 2482 |    2 |      2 | BENYV             | 123873942 |
| 2385 |    3 |      3 | HUNTERGERBERICH   | 520882356 |
| 2382 |    4 |      4 | TLB               | 115547721 |
| 2195 |    5 |      5 | BRENDANHEYWOOD    |   7727431 |
| 1891 |    6 |      6 | MITTYSTEWART13    | 254326500 |
| 1885 |    7 |      7 | KACZORON          |   9127861 |
| 1716 |    8 |      8 | CLIMBINGFOOL      |  10514689 |
| 1564 |    9 |      9 | KADAZZ            |  11233303 |
| 1492 |   10 |     10 | GORDON05          |   9309145 |
| 1310 |   11 |     11 | RCURTIS           |   7739605 |
| 1191 |   12 |     12 | JOHLSUE           |   8372364 |
| 1159 |   13 |     13 | CRAVIN            |   9207745 |
| 1127 |   14 |     14 | ALEXK             |   9390757 |
| 1101 |   15 |     15 | JAMESP            |  11195611 |
| 1032 |   16 |     16 | ROCKBRAIN         |   9092083 |
|  984 |   17 |     17 | NORTHWESTCLIMBING | 829864419 |
|  951 |   18 |     18 | SGODWIN           |  11525106 |
|  707 |   19 |     19 | DEBBIEBURGIS      | 166825755 |
|  333 |   20 |     20 | RHINCKLE          |  11107765 |
|  103 |   21 |     21 | WOGDOG            |  10125895 |
|  -34 |   22 |     22 | PMONKS            |   7758361 |
+------+------+--------+-------------------+-----------+
```

If I ramp up the decay the problem becomes way more obvious:

```
+--------+------+--------+-------------------+-----------+
| V      | Rank | Rownum | Login             | ID        |
+--------+------+--------+-------------------+-----------+
|   2232 |    1 |      1 | ALANEZZY          |   7888746 |
|   1289 |    2 |      2 | BENYV             | 123873942 |
|    776 |    3 |      3 | HUNTERGERBERICH   | 520882356 |
|    670 |    4 |      4 | MITTYSTEWART13    | 254326500 |
|    625 |    5 |      5 | RCURTIS           |   7739605 |
|   -571 |    6 |      6 | JOHLSUE           |   8372364 |
|  -1014 |    7 |      7 | BRENDANHEYWOOD    |   7727431 |
|  -1105 |    8 |      8 | TLB               | 115547721 |
|  -1819 |    9 |      9 | CLIMBINGFOOL      |  10514689 |
|  -2386 |   10 |     10 | DEBBIEBURGIS      | 166825755 |
|  -2643 |   11 |     11 | NORTHWESTCLIMBING | 829864419 |
|  -2857 |   12 |     12 | ROCKBRAIN         |   9092083 |
|  -2971 |   13 |     13 | SGODWIN           |  11525106 |
|  -4484 |   14 |     14 | KACZORON          |   9127861 |
|  -5215 |   15 |     15 | CRAVIN            |   9207745 |
|  -5333 |   16 |     16 | KADAZZ            |  11233303 |
|  -5617 |   17 |     17 | ALEXK             |   9390757 |
|  -7669 |   18 |     18 | GORDON05          |   9309145 |
|  -8855 |   19 |     19 | JAMESP            |  11195611 |
| -12111 |   20 |     20 | RHINCKLE          |  11107765 |
| -12667 |   21 |     21 | PMONKS            |   7758361 |
| -22884 |   22 |     22 | WOGDOG            |  10125895 |
+--------+------+--------+-------------------+-----------+
```

**Comment by scd** [comment]
In all but the very final steps we are working at the exponential level, where we don't have to worry about this at all. 

In the final step we take a log of the exponential value, which is where the negative comes in. So essentially this is just a max(score,0) issue when at the final step of outputting the score in the ranking query. This could even be done in the template if we wanted.

We don't have to worry about adding a negative scored route to a positive scored route because this is all done at the exponential level. Lets say you are adding 2.2e-10 and 4.1e+10 the result is still a little larger than 4.1e+10 even though the first score would have been mapped to a negative.

In your example I think you must have ramped it so that all of the ascents from each of the people were negative. 

If you think that this is essentially more than just a display issue then please let me know.

**Comment by scd** [comment]
fixed in facet

**Comment by brendanheywood** [comment]
Does this mean that negative score will show as zero, or not appear at all in the ranking? The latter seems slightly better to me. So where > 0 instead of a max(0,score)

**Comment by scd** [comment]
It will display zero.

This is a real edge case so I am not to concerned about which way we do things. 

When we shift then take the log the zero point is arbitrary and has no more meaning then any other number except that us humans don't like negative ratings.

Where I see this coming up is in an area with low ratings and old ticks.

I just don't think it matters, but if we want feedback it is better to have a methodology which is more transparent.

Maybe we should show a '?' rather then 0. Actually maybe we should show '<100' and use 100 as the cutoff rather than 0. 100 corresponds to about grade 3.

Also if this comes up a lot I want it to be in our face because maybe the solution is different all together. For example, rather than tick shifting by half a grade we tick shift by 2% of the grade (I am not sure how hard the maths is).
