### ISSUE TITLE
work out shift for conversion from performance rating to grade

### ISSUE THREAD

**Issue by scd** [theCrag/website#2539]
When converting rating to grade we can apply the shift offset prior to creating the performance rating OR not bother and apply it when converting back to a grade. I think that the two are equivalent and because it is much easier to fine tune if we apply at the final conversion we should do it there. @brendanheywood do you agree.

We have got to work out what that shift is?

**Comment by brendanheywood** [comment]
Yes I agree these are equivalent so we can do this at the latest stage. Doing if at the final stage means we can tune it on the fly without any db migration too which is great. Because of this I'm not too stressed about worrying about it's value right now, I think the order of tuning should be (unless we can do a multi regression all together) tick shift, then power factor, then decay, then this final shift.

I still think the original basis is sound: we pick a threshold of S = 2 or 3 and tune the shift so that you need to have points equivalent to red pointing S routes at grade X in order to be an X climber. The complication is that most people will have ticked a bunch of X-1 routes by the time they have ticked their first X route so they will already have the score points equivalent to 2 X ticks so I think that S should be around 2.5 or 3 as a starting point for tuning.

**Comment by scd** [comment]
This is done and is based on three ascents of a grade
