### ISSUE TITLE
Bug when trying to save a route with 'traverse' gear style

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2545]
Not sure if ti was related or not, I was attempting to create a 'Traverse' boulder problem to properly fix up the style css class and the article, but the process exploded:

Software error:

Undefined subroutine &CIDS::Application::SAPopulate::UpdateRoute::populateUpdateRouteBaselineDirectAccountNodeStatistic called at /opt/CIDS/perllib/CIDS/Application/AssembleStatistic.pm line 217.
For help, please send mail to the webmaster (scd@thecrag.com), giving this error message and the time and date of the error.

**Comment by scd** [comment]
Did you do this in your dev. This is not related to anything. It is a temporary artifact of changing dev systems and will disappear when you cutover to the new dev.

Please let me know if you want to pursue the traverse issue now and I will have to manually copy files.

Otherwise just close this issue

**Comment by brendanheywood** [comment]
meh
