### ISSUE TITLE
Re-think the font traverse grade

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2546]
From #2038 :

> Is it possibly we can only show this gear style in certain nodes that use that context so we don't pollute the world?

The ONLY places this style is being mis-used is outside France and Fontainebleau: 

https://www.thecrag.com/climbing/world/routes/with-gear-style/traverse/?sortby=at,desc

So at present there is no point to this gear style at all. We should:

* [ ] implement the FR context filtering so it isn't available elsewhere
* [ ] and we push to get more content from font using it. 
* [ ] properly add the css styles, and the help article

OR

* [ ] we just turn it off for the time being and fix the 24 mis-typed routes manually

**Comment by birgander2** [comment]
I never really liked the gear style "traverse" in the context of Fb trav grades. Everybody would call these problems still boulders. They're just horizontal instead of vertical, it's not that much different. But they possess a different grade. So in my opinion, here simply two different grade systems are used in a single area. This is indeed a problem for automatic recognition of the user input, but a new gear style is not a good solution to resove it. Better would be to let the user explicitly choose the grade system.

On a side note: I'm not even sure if all traverses in Bleau (there are many!) are graded in Fb trav. Maybe a local can help out!?

**Comment by scd** [comment]
I think we need a local to help out.

**Comment by brendanheywood** [comment]
@scd is there a limitation that grade's can't contain whitespace? Perhaps this whole thing could solved a lot easier if the grade '6a trav' could be matched to the traverse system?

**Comment by scd** [comment]
Can have whitespace. Still let's get a local involved

**Comment by brendanheywood** [comment]
@rouletout assigning to you rustle up some french boulderers, no general rush here at all

**Comment by rouletout** [comment]
Suggest to remove this gear style and re-assign the routes to existing styles

**Comment by birgander2** [comment]
Then the grades will be misleading (in Fontainebleau at least). So it's wrong, too (but probably better). For the moment anyway it seems that nobody knows for which problems the Fb trav grades apply and for which not.

**Comment by Mdemaillard** [comment]
Some problem use a #traverse in description
![image](https://user-images.githubusercontent.com/60388146/78503616-0e649b80-7768-11ea-989b-95c669c4e0de.png)

There isn't a search function to search per grade system, so not sure how to find some route graded as traverse...

**Comment by gui84** [comment]
In Fontainebleau you can get Fontainebleau grading or Fontainebleau trav grading.
For instance here : https://www.grimper.com/news-amanite-tue-mouche-8c-traversee-christophe-bichet.
So FB trav is a gear style in itself.

**Comment by gui84** [comment]
You also have traverses in some areas like Les Calanques :
https://verticalpirate-escalade.com/topos-escalade/france/calanques/castelvieil/les-grandes-traversees-maritimes/

but it's also deep water soloing or multipitch sport climbing route.

**Comment by birgander2** [comment]
Yes, I used #traverse during bulk import as quite often it is unclear whether a traverse-like boulder was graded FB or FB trav. I think the FB trav problem is tackled in the wrong way: imho we have two different grading systems here, and not two different gear styles. And the whole FB trav problem kind of special philosophy anyway.

**Comment by k-jahn** [comment]
The fb trav grading is also used here in Germany. However, the grading converts  differently from what is implemented on the Site

Source in #2038 (I assume this is what the Site conversion is based on):
http://www.rockclimber.de/index.php?view=article&id=54:bouldering

Source for the conversion I'm familiar with:
https://de.wikipedia.org/wiki/Schwierigkeitsskala_(Klettern)#Bewertungsskalen_f.C3.BCr_andere_Bereiche_des_Kletterns_und_Bergsteigens

The difference is relevant:
fb trav 6C+ converts to:
fb bloc ~5C+/6A / V1 on the site
fb bloc ~6C / V4 in my personal experience.

I find the whole approach of setting one grade system but potentially getting another, due to gear style, very counter-intuitive. I also agree, that the 'traverse' issue could be better handled within the boulder gear style via grading systems and tags

**Comment by rouletout** [comment]
Traverse gear style has been disabled. Data clean-up is required and on-going with the help of users. New routes / edits can not be assigned Traverse anymore.

**Comment by rouletout** [comment]
There are no Traverse routes in FB, so it is currently a non-issue, clsoing here
