### ISSUE TITLE
Fix up the lower V bouldering grades internal convesions (audit all systems grades widths)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2557]
In doing #2503 it's quite noticeable that the widths of the bouldering V grades changes as you go up. Going from effectively 1 grade per color band, to 3, 4, 6 and then 7 with room for 9 at the elite band. Something is quite screwy and I think it's mostly in the lower grades.

In reality the V system is roughly similar to ewbank + 20 or 21. The widths are roughly the same as ewbank, and the offset is largely the same. It should probably just start in the green band like B-scale and P-scale and the V0's should all be moved up and compressed.

This also open's up a large question, previously it only matted that grades were consistent across systems, ie the conversion was correct. It didn't matter how wide each grade was. But that's changed because we are now explicitly using the grade width to measure power factors difficulty increase from lower grades. So just yet another reason to refine all the internal grade conversions (no idea yet how to actually go about this though...)

**Comment by scd** [comment]
Yes, I agree. It is going trigger a whole lot of grade conversion work.

I will look into revising the choice of width for v grades

**Comment by scd** [comment]
I updated the grade width to align with the grade widths at the level of difficulty where the stats were taken from. I also had the wrong grade width for V-grade. It was good that your visual grade slider tool picked this up :)

I have always had the view that the CPR will trigger an extensive grade conversion review. We will also need the tools to easily make adjustments, rather than going through a release cycle.

**Comment by Mdemaillard** [comment]
candidate for closure ?
