### ISSUE TITLE
CPR: Filter leads to Error 503

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2568]
The following filter leads to error 503:

Climbers, All time Sport Ranking, Female, Tick Type (select any,  e.g.onsight)

https://www.thecrag.com/climbing/world/climbers/using-stat/all-time-sport-rating/with-tick-group/onsight/of-gender/female/ 

Sorry, didn't find how to add release 53....

**Comment by brendanheywood** [comment]
That's backend for @scd

**Comment by scd** [comment]
hotfixed. When I changed the url stub from 'power' to 'rating' I missed a spot in the dynamic query builder.

Actually this brings up another issue. This query is actually fairly server resource intensive because it has to recalculate the rankings from the raw ascent list rather then our precalculated stats. 

I am thinking that we should make all the facet fields which result in this server intensive queries only available to supporters. I think there is a strong argument that if you are going to tie up server resources then you should be paying.

Is this something we want to do? Shall I log another issue about this?

**Comment by brendanheywood** [comment]
I think figuring out which ones to hide and show would be more work that it's worth. Really at some point we need to replace the entire search infrastructure with a dedicated search engine like elastic search or solr and this will all be irrelevant.
