### ISSUE TITLE
API: add tags to node endpoint

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2597]
please add tags to the `api/node/id/` endpoint 

- either add the tags by default if the show=info is present
- or add a separate show=tag option

**Comment by scd** [comment]
I have fixed this in simon's dev. Do you want to also include the inherited tags. Normally I would only return direct tags for a node unless explicitly requested as the query is more expensive for inherited tags.

@nicHoch do you need it in sandpit as a priority?

I have also fixed this endpoint so it will return info on annotations.

Nicky, can I ask you to let me know your app priorities for api end point fixes. In particular whether it is a blocking issue that needs to be put on sandpit immediately.

If it does need to go into sandpit, could you also provide a test end point for sandpit so that I know i have solved the issue. 

As a side issue, do we need this info in the full area dumps?

Warning bells are going off if the app is using this endpoint.

**Comment by nicHoch** [comment]
this one is not blocking. Will it come to sandpit with the next priority API issue or do you push the endpoints one by one?     

I thinks tags are already included in the full area dumps. 

I think inherited tags are a must have otherwise i have to implement that inheritance on the app side and this is unnecessary logic and replicated code.

**Comment by scd** [comment]
Can you explain the app workflow for getting these tags. I think I am missing something.

If you have the full area dump, I am confused why you need to get it again using the node id end point. 

If want to work out whether inherited should be there by default or with an extra input parameter.

Otherwise I am just mindlessly implementing, which I don't like doing so much.

 - [ ] note to self, implement inherited tags.

**Comment by nicHoch** [comment]
Beyond the TLC border the app uses that endpoint to brows the index online with a node by node approach. Localy stored crags (full area dump) will prevent a "online brows" for all children.

Am 14. Februar 2017 02:08:44 MEZ schrieb Simon Dale <notifications@github.com>:
>Can you explain the app workflow for getting these tags. I think I am
>missing something.
>
>If you have the full area dump, I am confused why you need to get it
>again using the node id end point. 
>
>If want to work out whether inherited should be there by default or
>with an extra input parameter.
>
>Otherwise I am just mindlessly implementing, which I don't like doing
>so much.
>
> - [ ] note to self, implement inherited tags.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/2597#issuecomment-279575526

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by scd** [comment]
Is this a fallback while the app is downloading the full area dump? Or is there another reason why an app instance would not have downloaded the full area?

How does this work when the app is offine?

It is possible that there will be a million installs of this app. How will node to node api class scale?

**Comment by nicHoch** [comment]
One basic use case is the index browsing like a normal web browser. Why should a user download first a entire crag and than only look at one node. 
From the performance perspective why do you think is a webside page load cheaper than an api app page load. Is there no cache for the api endpoints?

I think we should move that discussion to trello or elsewhere because it is not about tags anymore.

Am 14. Februar 2017 02:43:46 MEZ schrieb Simon Dale <notifications@github.com>:
>Is this a fallback while the app is downloading the full area dump? Or
>is there another reason why an app instance would not have downloaded
>the full area?
>
>How does this work when the app is offine?
>
>It is possible that there will be a million installs of this app. How
>will node to node api class scale?
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/2597#issuecomment-279581784

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by scd** [comment]
Yup good point. I posted a trello issue to discuss.

One thing that still remains in regards to tags is whether on not we need inherited tags at a node. Even with node to node navigation, to get to say Declaration Crag (in Arapiles) you would have had to gone through Arapiles. I think the app should have a mechanism to get inherited information from parent nodes. This is a very common thing (eg Ethic).

So we still need to work out whether you really do need inherited tags or not. Obviously I am happy to do the api enhancement.

**Comment by scd** [comment]
@nicHoch I believe we can close this now because we are doing it all through the index api. Please close this issue if this is the case

**Comment by nicHoch** [comment]
yes the index api is working well. so we close this
