### ISSUE TITLE
Gym CPR

### ISSUE THREAD

**Issue by scd** [theCrag/website#2607]
What to do about Gym CPR. Here is a brain dump to get this discussion started:

  * Grading between gyms is possibly too arbitrary to compare cpr's between gyms (ie global rankings do not make so much sense).
  * Climbers basically stick to one gym so there is still a lot of performance value in having a cpr for clilmbers.
  * Gym owners are probably interested in rankings in their gym.
  * Rather than Trad, Sport and Boulder, the categories are probably Top rope, Sport and Boulder.
  * If we do gym cpr then the stats must be separate from outdoor, so a gym sport never gets added to an outdoor sport.
  * Implementation of this is to duplicate stats fields, and have a flag on the ascent record which tells us which set of stats fields the cpr applies to.
  * If somebody is an outdoor and indoor climber then their profile will be set to either the outdoor or indoor performance graph.

**Comment by brendanheywood** [comment]
> Rather than Trad, Sport and Boulder, the categories are probably Top rope, Sport and Boulder.

I'd tread slowly here and let it be driven by the gyms. I'd suspect we'd want a single rating per gym and combine them all, but it really depends on the gym. If I was a gym climber and transitioned to outside I would not want to see 3 inside graphs + 3 outside graphs on my profile, that's just overkill and clutter. However if I was just a sport climber + indoor climber it would make sense to see 2 graphs.

> Implementation of this is to duplicate stats fields, and have a flag on the ascent record which tells us which set of stats fields the cpr applies to.

Can we just change the logic around how the data cascades up? At the gym level we only ever want the total points for a person at that node. And at the node above we just want to not include gym stats when we rollup the children's stats into the parent. The only reason we'd need to have 2 stats is if we wanted to see stats at a larger region level for gyms which I don't think we want. One edge case I could foresee is a franchise of gyms which have consistent grades within themselves because of rotating route setters and you want to compare across them. There is probably enough other edge cases to warrant duplicate fields, but I'd still hold off on all this until it's driven by the right reasons.

> If somebody is an outdoor and indoor climber then their profile will be set to either the outdoor or indoor performance graph.

I don't think forcing people to decide between only inside or only outside is useful.

**Comment by scd** [comment]
> Can we just change the logic around how the data cascades up? At the gym level we only ever want the total points for a person at that node. And at the node above we just want to not include gym stats when we rollup the children's stats into the parent. The only reason we'd need to have 2 stats is if we wanted to see stats at a larger region level for gyms which I don't think we want.

I really want to avoid that as there is a lot of extra logic. There is no other stat with cascading stopping conditions and there is a whole lot of logic around changing gym node types. It is far simpler to have a second set of stats. Also while I don't think we want regional levels, I don't know and we have not talked to enough gyms yet.

**Comment by brendanheywood** [comment]
Ok fair enough. This all just sounds like more reasons to sit on this until we understand what people / gyms want

**Comment by lordyavin** [comment]
Is there a way to view my gym CPR at the moment?

**Comment by scd** [comment]
Yup - in the main menu - Logbook - Gym Sport CPR

Will take you to this:

https://www.thecrag.com/ascents/has/gym-sport-cpr/by/captainhook/?sortby=rating,desc

You can see other peoples by going to their profile and looking in the logbook main menu again.

Note that I have started to put more stuff in the main menus.

**Comment by lordyavin** [comment]
What is are the "main menus". Please provide me a screenshot where to klick. I'm not able to find it.

**Comment by brendanheywood** [comment]
![image](https://user-images.githubusercontent.com/187449/28166986-4c343ae0-681d-11e7-9a0a-c1b0e934eca8.png)

**Comment by Mdemaillard** [comment]
CPR & Charts for Gym-Sport and Gym-Boulder have been implemented.
User setting implemented to show natural, artificial or let system choose

Candidate for closure ?
