### ISSUE TITLE
Add the ascents cpr timeline chart to the ascents facet page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2614]
We get this almost for free

* [x] only when a single climber is selected
* [x] only when exactly one of boulder, sport, or trad is selected
* [x] do we always just automatically add it? I'm leaning towards yes

**Comment by scd** [comment]
This needs to be discussed in relation to area cpr curves. Thinking out loud:

  - [ ] If single climber and boulder/sport/trad selected then the curve is automatic
  - [ ] Otherwise the user can select a performance graph.

The issue we discussed in #2616 is the general server performance and server load. Maybe the performance graphs are only selectable for premium users which would solve the server load issues for the time being.

**Comment by brendanheywood** [comment]
Lets defer this until we can properly handle the UI for the sponsors

**Comment by scd** [comment]
I think this is done now.
