### ISSUE TITLE
Handling transition of crag from illegal to legal

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2642]
Now that we've managed to hide location info on a closed crag, I've actually looked into it's status and it's on crown land, so it can be made public again. 

I've removed the private tag, and updated the access and approach directions, but apparently we don't handle the transition out of 'closed' gracefully. 

- The map is still disabled
- Approach info is still disabled (and gets deleted if you fill anything in)

There probably needs to be some kind of check on this transition, so people can't just make something public easily and immediately, but if there is additional approval or time required there should be a message to that effect 

![image](https://cloud.githubusercontent.com/assets/22091505/23729058/039b05c4-04b4-11e7-8d02-8430f97486e2.png)

**Comment by scd** [comment]
I have opened up the viewing restrictions to Scout Crag

https://www.thecrag.com/climbing/australia/new-south-wales-and-act/australian-capital-territory/area/1019938086

It will be a while before we get around to making these transitions nicer. For the foreseable future I want to be involved whenever we have to hide or show an area because it is a really sensitive issue and I want total visibility until I feel as though we sufficiently understand the best way to handle it.

**Comment by DaneEvans** [comment]
All good, that makes sense to me

**Comment by Mdemaillard** [comment]
Currently a crag tagged as either "closed" or "illegal" will still display the map and "approach" field, albeit with appropriate warning, color coding on the map, symbol, and header.

The view restriction is i believe a separate process more involve than tagging. Topic still actual or obsolete ?

**Comment by scd** [comment]
You are correct, view restriction is a different process. Closing
