### ISSUE TITLE
Workflow improvement to granting permissions

### ISSUE THREAD

**Issue by scd** [theCrag/website#2671]
Thinking out loud, about the next step to help us is to possibly create a linked request reference id in the email. If an admin clicks on the link they should be able to confirm the permissions with one button click and automatically send email. We could embed the userid and nodeid in the request reference, so we would not have to do any database update, just one template and one api endpoint. Maybe only a couple of hours work.

Ultimately we want to push this all to the system, rather than emails.

**Comment by scd** [comment]
notes to self:

climbing/australia/arapiles/account-permit/9068185

**Comment by brendanheywood** [comment]
There are two variables in how we could respond, we could change the role we give out, and more probably change the node that we give access to.

So if there was a page like:

climbing/australia/arapiles/account-permit/brendan

then I'd want to see a matrix something like:

Node | Editor | Coordinator | Admin
---- | ----- | ---- | ----
Arapiles | [ ] | [ ]  | [ ] 
Victoria  | [ ] | [ ]  | [ ] 
Australia | [ ] | [ ]  | [ ] 
World | [ ] | [ ]  | [ ] 

If that person already has a role then it should preselect, ticking anything should toggle it.

**Comment by brendanheywood** [comment]
Also at the moment we are sending an email to them, and cc'ing us. Which means that the email is tailored to them and not us. I'd prefer it to send two different emails. This could happen first as another stepping or later after we build the process into the platform.

The 3 main things I want are:
* [ ] see who it's from in the email from (ie it's not from support, to support) (yes we see the username but not their real name, and it's not where you expect it etc etc
* [ ] I want convenience deep links into two pages both of which are admin only:
  * [ ] the users contributions https://www.thecrag.com/climber/brendanheywood/settings/contributions (actually they can see this so we can easily do first with without splitting the email)
  * [ ] the review permissions page for the node: https://www.thecrag.com/processmap/reviewpermit/11747419

I've also added a new stream event item in #2657 so that we see a stream event showing who granted a role to whom, for what node and when. When we devolve the granting of roles out to the community this will be critical.

I think all the permissions stuff should be transparent and public, the contributions page above isn't really a settings page at all and I think it should just be https://www.thecrag.com/climber/brendanheywood/contributions and visible to anyone logged in. Also linking to the reverse case of #2506

**Comment by brendanheywood** [comment]
* [ ] Also once we are done we need to double check all the text like the chunk at the top of here, to make sure it's all still valid:

https://www.thecrag.com/climber/brendanheywood/karma

**Comment by scd** [comment]
@brendanheywood +1 for your above comments.

I have started the permit page implemention looking something like this:

![account-permit](https://cloud.githubusercontent.com/assets/373058/24859299/49cd76b0-1e33-11e7-8930-dc45bd765880.png)

I want to put in all the information we need to make the decision which area we grant them permissions for. One thing I want to know is if the person has permissions are sibling nodes, or descendants of sibling nodes.

If we then make the contributions page a transparent public page as you suggest and embeddable we could also embed the permissions tree:

https://www.thecrag.com/climber/leecujes/settings/contributions

into the area permit page.

This will be javascript api update of account permit. I am thinking of having a flag to say the system should send an email about the change in permissions. We may want to do this silently.

There are a few cool things about this form. It takes into account your permissions, so you might be able to adjust permissions for people in Victoria only. It also does not allow you to adjust permissions which will not change any thing. For example Lee has global coordinator permissions, so assigning him as an Editor at Arapiles will not do anything because the global coordinator wins.

There is one thing we need to discuss and that is the subtlies lf the 'User' permission. A User permission is the same as no permissions. However somebody with no permissions or User permissions is eligible for automatic editor upgrades by the system. This is why we introduced the 'User Fixed' permission so they cannot be upgrade automatically. I am thinking that we are probably going to dump the auto upgrade as we follow through on some of the suggestions.

**Comment by brendanheywood** [comment]
Great stuff :)

Have you already got some business rules for who can assign whom and where? ie if I am an admin at Vic, can I assign another admin at Vic? Or only at a lower node, or only a lower role? Part of me thinks that we should directly assign admins, and they can only assign coordinator and below. We also need to make it much clearer for everyone what each role means.

Does all this also work with the edge cases, like the crags which are locked down, and also the gyms?

What is an example url I can play with on dev (just pulled)?

> I am thinking of having a flag to say the system should send an email about the change in permissions. We may want to do this silently.

I definitely want clear communication to the user saying they have been upgraded. We should also have a clear negative comms path too for when we decline to give them access. Do you also have to add a comment when applying / declining the new role?

> I am thinking that we are probably going to dump the auto upgrade as we follow through on some of the suggestions.

I think there is still a place for the auto upgrade, it just needs to be more cautious than it was. We still need to balance our workload vs risk, but lets leave that discussion for later as long as we can leave the option open for it.

**Comment by scd** [comment]
> Have you already got some business rules for who can assign whom and where? ie if I am an admin at Vic, can I assign another admin at Vic

I have not changed any business rules for this round of work, just starting to expose them better and improve our workflow to save time.

If you have admin permissions at a node then you can grant permissions at that node or it's descendants which includes being able to grant another admin. 

> Part of me thinks that we should directly assign admins, and they can only assign coordinator and below. We also need to make it much clearer for everyone what each role means.

I understand why we would want to do that, which implies we need a higher level permissions, which is there using our role based permissions system rather then area permissions. I think we should adjust the business rules in this regard before we start granting others permissions to grant permissions.

> Does all this also work with the edge cases, like the crags which are locked down, and also the gyms?

We will have to review and test edge cases before granting others permissions to grant permissions. I thought that for a locked crag you had to be coordinator or higher. The gym permissions has an extra business rule about cascading, I think. I think admin permissions cascade into a gym, but nothing else does. So if if you are an editor of Australia these rights do not go into premium gyms.


> What is an example url I can play with on dev (just pulled)?

https://dev.thecrag.com/climbing/australia/arapiles/account-permit/leecujes

Note it is not functional yet. I have got the templated data working and the api coded, but not linked the API with the UI yet.

> I definitely want clear communication to the user saying they have been upgraded. We should also have a clear negative comms path too for when we decline to give them access. Do you also have to add a comment when applying / declining the new role?

This sounds like you do not want the user email to be optional. I am fine with that. I was thinking about a comment, but there are some complexities such as translations, and also ui flow. 

I think we need to show the language of the user. 

Declining?

**Comment by brendanheywood** [comment]
> This sounds like you do not want the user email to be optional. I am fine with that. I was thinking about a comment, but there are some complexities such as translations, and also ui flow.
> I think we need to show the language of the user.
> Declining?

We don't need to address all of this now, it depends on how much you implement inside the system vs just inside an email.

At the moment they click a button, we get an email, we do something, and then email them back.

After this issue is done are we going to:
a) going to get an email, which links to this page, we click a button which gives them the role, and then we email them back manually
OR
b) going to get an email, which links to this page, we type a comment and then click a button which gives them the role and emails them from the system

I'm ok with the simpler a) for now and we can use it to inform how we want b) to work before we codify it. We often get back and forwards emails after this anyway which is a good thing (but potentially time consuming).

**Comment by brendanheywood** [comment]
> Declining?

oops, so if we don't give them the role, in a) we email them back and say sorry nope. But if we went down b) then we still want to let them know, so we'd need a comment and a 'Sorry nope' button

**Comment by scd** [comment]
My main aim is to reduce the time it takes to deal with these things. I was planing on doing b) either with or without a comment - undecided. 'Sorry nope' can just be a return email from us.

The emails are providing some interesting touch points on people who are demonstrating a willingness to get more involved. We want to keep this.

**Comment by brendanheywood** [comment]
I think the comment is important, quite a few emails we've sent recently have had a few chunks of stuff, like reinforcing copyright or suggestions etc.

Short term I'm happy for the negative case to be a manual email, they seem to be very few and far between, but we will probably need to re-address this when we delegate this out, as the support email won't be in the loop at all. We can't have region admin's manually emailing people. So up to you to decide on how much extra work that will be.

I think a good starting point with the decentralizing will be setting up some country level admins probably with a high cross over with the translators, as this will probably be the main support query and can be done fully translated end to end. Doing this fully will also mean we need to have the proper 'request queue' including history, so other admins can see what's happened and don't double up the work.

I'm not sure how much of all this you wanted to tackle in the first cut, but if the point is to get it off you plate then I think we should. We want the queue system to:

* be able to shift most of the load to trusted people
* be able to share the load with many trusted people
* make sure nothing slips through the cracks


They way I think this could work is something like:

* [ ] if you request access to node X, then add this request to the queue
* [ ] walk up the crumb trail looking for someone people with the admin role on this node. If you find many admins at that node then randomly pick one and immediately email them the alert email with links
* [ ] we also have a daily delayed digest of all outstanding requests. All admins will get this, but with the subset of things they can action

I think this then ticks all of the boxes above. So say for Germany in the short term we could have Ulf and Nicky who are both admin's at the Germany node (but also admins at the world) so they share the workload 50/50 but if they are sick or climbing or whatever then the other will get the digest email a bit later, and finally we can action stuff if it's sat there for too long.

If and when we delegate we cannot use email directly, because the admin's aren't privy to the users email address or vica versa. So I'm thinking the easiest solution might be that we auto create a single private 'access' discussion per user and the users request message is dumped into it, and we can probably re-use this discussion in future for all access related requests. Each time an admin responds via the button it also subscribes them to the discussion and posts their reply automatically. This then makes a simple audit trail of questions and answers like copyright or whatever. The admin can easily invite others if they need help.

We'd need a way for any admin to jump into this forum at will to read it's history. Just a button on the queue process page

There are a few minor downsides I can see with this:
a) as the user moves around and asks for access in multiple places then many admins could get subscribed. But that is probably a bonus as it adds context. Any admin can always unsubscribe if they don't want it.
b) the biggest issue might be that the user then uses this discussion as a way to ask in future for more access. Not the end of the world if they do, but we want them to go via the normal queue method

**Comment by scd** [comment]
I now have a fully working prototype which sends emails. The three email use cases are:
  * Granting permissions to an area if the user did not have a permissions record specifically for that area. Note that this does not need to take into account permissions for ancestor nodes because you can only grant more permissive permissions as you go down the hierarchy.
  * Adjusting permissions to an area if the user already had a permissions record. Note that I use the word adjusting rather then downgrading/upgrading for two reasons. Firstly there is less work and secondly I think the word downgrading is too harsh.
  * Removing permissions to an area. 

The admin person can write a comment on all of the above cases. I have kept the UI really simple. As soon as you click the permission radio button the javascript immediately collects your comments and fires off the api call. This means if you want to write a comment you have to take care to write the comment before you change the radio button. There are no checks in the UI asking you if you want to write a comment. This is fine for now, but we will have to improve this before we expose to others.

I have also added the account permit link to the original request email. So our process flow will now be:
  * Get email
  * Click on account permit status link
  * If one of us have done it already then it will be much clearer.
  * Add optional comment and click radio button

This will be a lot faster. 90% of the time we will not even need a comment.

**Comment by scd** [comment]
I will not close this issue because there are too many goodies in it. I don't propose to do anything else significant for now, just tidy up of what I have done.

I think the next step will be getting translators involved. We will actually be forced to do this as soon as people from Korea and Italy start sending us requests in their own local language. To do that we have to make sure the original email requests are being cc'd to support+it@thecrag.com rather than support@thecrag.com. Checklisk of work to make this happen:
 - [ ] Create Support Lang account associated with support+lang@thecrag.com email address for each langauge we support. This must be done in prod and synced with dev.
 - [ ] If detect the users language in the request and modify the from account. 
 - [ ] Review edge cases for giving others admin permissions and adjust the business rules as discussed above.

**Comment by brendanheywood** [comment]
How can I test this? I've pulled to dev, requested access to the pipes as evil me, and then tried to view this page as real me but it's just a blank page:

https://dev.thecrag.com/climbing/australia/mount-wellington/organ-pipes/account-permit/evilbrendanheywood

**Comment by scd** [comment]
I am guessing that there is a problem with evil you being private. This would be a bug that needs fixing.

Try a public account.

**Comment by brendanheywood** [comment]
ok swapped that account to public and got it going. There is a weird bug when I set a node to a role it gets ignored or set to another role. Sometimes I get an ajax error but mostly not.

eg I set evil me to user, works. I set them to Editor it works. Then I set to Coord and it seems to work but after the reload it us back to User. No error. Then I try and set to admin, and it sets it to editor. I set it back to User. It seems like half the time for coord and admin it barfs silently and reverts to some previous state.

I'm not sure if this helps diagnose it but in the pic below I first clicked on admin for tasmania and it came back as editor, and then I click on admin for South east and it came back as coordinator.  I've checked the ajax and the post data is correct.

![image](https://cloud.githubusercontent.com/assets/187449/24912622/02ada6bc-1f12-11e7-81a6-0508ddc6a377.png)

Also I really dislike ajax things that do stuff and then reload the page. It seems to defeat the point of using ajax in the first place as you are doing 2 calls instead of 1 if you'd done a normal form post. Also if you click something, and then click something else it barfs really easily. The post should simply return the end state after the post api call, and if the end state is the same as what is selected then simply do nothing, if different then re-select the current state according to the server.


Also what are the two columns of zero and the empty 'You' column for?

![image](https://cloud.githubusercontent.com/assets/187449/24912545/c91e7322-1f11-11e7-9a20-9e6f18b80488.png)

**Comment by scd** [comment]
I have mostly fixed the private account issue, but it needs more thought when we expand this to people outside the core team.

There is definitely a problem on the second click (ie after the page reloads) with permissions not being set. It is the same if I disable the page reload. This will take a bit more investigation which will have to be done later.

Can you confirm you pulled the translations as well. It looks like some translation fields are missing.

Don't worry about the page reload now. The main reason I want it this way is because it exposes bugs when being set. The reload demonstrates to me that it has been set. We will want to fix this before we open it up to more admins. We will need to replicate the logic for disabling fields that is in the backend.

**Comment by brendanheywood** [comment]
I've pulled the lang.

* [ ] There is an issue with the disabled radio buttons. Lets say I look at a matrix and then click something accidentally and give them admin, now there is no way to go back to the original state. I can set them to the 'user' role at a node but not actually remove the role. I feel like there should be a 'no role' button which removes it completely. Maybe this is functionally what 'user' role is? Is there a reason that anyone would explicitly be given a user role at any node?

**Comment by scd** [comment]
User role is equivalent to no role. However I agree there should be something which unsets their role altogether.

The bigger issue with accidentally clicking a role is that they will be sent an email and then another email with the correction. The email should probably wait 60 seconds before being triggered. This will be a use case for the new email system we are talking about.

**Comment by scd** [comment]
I have made various fixes including fixing the shitty bug where it was not working the second click.

Still leaving it as a page reload for now.

**Comment by scd** [comment]
I am closing this issue because the core issue is resolved and there is a lot of noise in the discussion. We might want to re-open other issues about contributions.
