### ISSUE TITLE
Competition Mode Hangman

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2676]
The goal behind this competition mode is it to create a fun community game instate of a serious competition. 
The main idea is like "hangman" the climber/team has to unlock a phrase by ticking routes. The team nominates letters by ticking ascents. The first (or keypossition) letter (A) of the route name (not the ascent label) is matched against the phrase. if the phrase contains a hidden letter A than the very first occurrence hidden letter A becomes visible. If the phrase contains a second A the team has to tick an additional ascent with A. Each unlocked letter results into 1 point. The ranking is ordered by the totals points.

A tricky new part of the competition framework would be the handling and visualization of the current phrase. the phrase should be shown in the result competition table. Nice to have would be the possibility to configure if the current phrase is visible for every one or only for the logged in team member. 

<img width="622" alt="2017-03-30 10_17_32-prasentation1 - powerpoint" src="https://cloud.githubusercontent.com/assets/2226714/24494453/9ae671dc-1532-11e7-8f70-580a601c6685.png">

 
Configuration Parameters:

```
competetionType: hangman
teamSize: 1..n
phrase: "helloworld"
keypossition: 0 (first)
rootnode: the area (subtree) within all ascents have to be logged 
starttime :
endtime : 
showCurrentPhrase: [all,onlyteammember]

```

**Comment by nicHoch** [comment]
@scd what do you think is that doable in a fair amount of time?

**Comment by scd** [comment]
I will do some research over the weekend. Please remind me if I have not done anything by Monday.

**Comment by nicHoch** [comment]
Hi @scd 
i played with the new hangman mode and i relay like it. Also your idea with the * in the shown phrase  if it is not your account - is very cool.

At the moment every starting letter of an ascent unlocks every letter in the phrase. This is the normal hangman approach but I think it is important for the variation in the leaderbord that every letter in the phrase have to be unlocked by a separate ascent.
So in this example we need two ascents with "E" to unlock all "E" in freedom.
I think for a nice game a long phrase is recommended but at the moment the length of the phrase counts less than the normal character distribution.  

is that hard to change?

**Comment by scd** [comment]
There is a couple of extra lines of code.

Please provide a demo phrase so we can also trial the screen space with a longer phrase. I think I might have to make the squares smaller.

One flaw of this competition is that it does not record who got there first. Maybe we can use the epoch time of the ascent that unlocks the last element as a bonus score. More specifically it could be the number of seconds between now and the end of the competition period. But this is getting pretty complex for a social competition.

I have had an alternate thought that the score could be the grade of each climb that unlocks a letter. So that rather than unlocking a E giving you 1 point if you unlock it with a grade 21 you get 21 points. This means that you can improve your score even if you have finished all the letters.

**Comment by brendanheywood** [comment]
Can we close this off now?
