### ISSUE TITLE
Missing placeholders in request access emails {ascentCount} should default to 0

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2688]
**What actually happened**

Request access email contains placeholders:

Number ascents: {ascentCount}
Karma: {karma}

**What did you expect**

If they are missing they should be 0:

Number ascents: 0
Karma: 0

**Comment by brendanheywood** [comment]
@scd Just looking at the code this seems like two different issues:

* [ ] the key / val is passed into getText but when the value is null or undef then it doesn't get replaced. I think in this case it should get replaced with ''
* [x] karma and ascent count should be cast to numbers (done but not tested end to end)

**Comment by scd** [comment]
Your solution of mulitplying by 1 works but causes warnings. A couple of FYIs

 - `my $karma = data->{karma}||0` if you want it to default to 0. This covers serveral use cases in perl
 - the formatNumber translation function will convert the string '1234' to the number '1234' then convert to the international human readable number, which in au is 1,234. Generally we should use that in templates.
 - Email test patterns which output to standard out are defined in the same email directory. In the script directory run `./test-email email-templates/RequestEditorPermission.test2`

I am closing this issue as the bug is fixed, but I want to keep the second part open for discussion.

**Comment by scd** [comment]
see #2708 for discussion on undefined translation variable behaviour

**Comment by brendanheywood** [comment]
stuff like $data->{karma} should always be defined. The template should never have to deal with optional stuff like this it should be handled in the atom functions or elsewhere in the backend

**Comment by scd** [comment]
fair enough
