### ISSUE TITLE
Idea to establish decay cpr parameter

### ISSUE THREAD

**Issue by scd** [theCrag/website#2709]
With a small bit of coding we should be able to allow the decay parameter to be passed into the CPR curve, as the CPR values for this curve are calculated dynamical. It might be a little bit painful, but there should be no fundamental reason why we cannot do this.

Once we have a dynamic decay, we could the create a survey using twenty or so sample accounts and five predefined decay values.

The survey would ask present each of the sample accounts with all five decay values and ask the user to select the one that they think is the best to use.

If we got a 100 climbers going through this survey, each with 20 sample accounts then this is 500 inputs on what the best decay value should be.

This will take a fair bit of setting up, but the project itself could create community interest.

**Comment by brendanheywood** [comment]
Hmm I dunno how useful it will be but we can try.

For people who climb often, the decay almost doesn't matter at all so asking them is a little pointless as all of their cpr curve variants will be identical. eg if they have plateaued, or if they are gradually getting better then it's irrelevant. Decay matters mostly to people who climb irregularly and or have had a break. Or a smaller edge case is where people are still climbing quite a lot but are going backwards in terms of grade. The important thing is that the decay is high enough so that their cpr curve "shrink wraps" down to their lower grades if they don't keep pushing their limit.

The only real visual impact it will have for regular climbers is the final cpr value / slope.

Secondly I still think the power factor and decay are / should be intimately tuned together and both should have ideally have a statistical basis.

**Comment by scd** [comment]
We have a reasonable basis for the power factor, so unless some feedback comes back pointing something out we have missed it should be relatively stable.

The survey would be asking about other peoples timelines.

If we found a strong statisitical basis for the decay then this would be my preference. In the absense of this I would like to go down some sort of process to determine it. In some ways the survey is a statistical basis on what people think. 

I am not tied to the idea and it is a lot of work. Regardless I don think we should have a decay parameter in the timeline as this will be a great visualisation of shrink wrapping cpr

**Comment by Mdemaillard** [comment]
Was that done ? we do see decay over time in the CPR calculations. 
Or is it to refine the existing underlying logic ?

**Comment by scd** [comment]
Decay was not calculated statistically but anecdotal observation. We are
not going to do any more with this issue. Please close
