### ISSUE TITLE
add more date formats for the logbook importer

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2713]
**What happened?**

the main export data formate for the 8a export tool is not suported by our inport function

**What you expected:**

add more date formats

    (d)d.(m)m.yyyy

is there some encoding auto detection we can utilize for special chars?

**Comment by scd** [comment]
@nicHoch I have added the the date format. However I think this date format should still have worked with the 'dd/mm/yyyy' date format as the system accepted both a `.` and '/` separator characters.

I have added the new date format anyway because it is potentially confusing.

This makes me think the import problem was due to the encoding. I could not find the original file that had import problems. Are you able to send this to me?

I am going to split this into two issues and close this issue.
