### ISSUE TITLE
Translation: capitalisation wrong

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2717]
**What happened?**
https://sandpit.thecrag.com/climbing/world/climbers/using-stat/sport-rating/
Title shows "Sportklettern leistungsfaktor Rangliste weltweit"

(please also provide urls and screen shots)

**What you expected:**

should be: "Sportklettern Leistungsfaktor Rangliste weltweit" 

Couldn't find it with the new report https://dev.thecrag.com/climbing/world/climbers/using-stat/sport-rating/?lang=de&langreport=1

**Comment by scd** [comment]
Please use the same domain for the reports, so it should be:

https://sandpit.thecrag.com/climbing/world/climbers/using-stat/sport-rating/?lang=de&langreport=1

However that is not the issue here. If you look at the following version:

https://sandpit.thecrag.com/climbing/world/climbers/using-stat/sport-rating/?lang=xx

(note that this just replaces xx for all translations).

You can see that that field is actually build from three separate terms (ie three xx's). This means it is probably a structural issue. Building the title is pretty difficult because we have lots of separate terms. I was fully expecting this to come up at some point, but I do not know how to resolve yet. 

Can you please let me know what it should look like?


Also I have had another idea for helping you find translation keys. Would it be of use to have another language like xx (call it 'yy') which replaces all keys with the key itself. It will look fairly crazy, but it will make it explicit what key is being used in this component. Would this be useful

**Comment by rouletout** [comment]
I think the current report works fine so far, what it should look like is here:

What you expected:

should be: "Sportklettern Leistungsfaktor Rangliste weltweit"

**Comment by scd** [comment]
So it is just a capitalisation issue?

**Comment by rouletout** [comment]
Yes

**Comment by scd** [comment]
I presume you do not need further assistance on this one. Please close when done

**Comment by rouletout** [comment]
There is something wrong withthe title - lang=yy shows a key that I can't find in the translation system (the first of the 3) - so please check and fix

**Comment by rouletout** [comment]
Moved to translations, closing here
