### ISSUE TITLE
Add chinese to translations

### ISSUE THREAD

**Issue by scd** [theCrag/website#2723]
@ulf I am a little confused with what to add to our system. I cannot work out what the chinese language is.

The iso code for chinese is zh. Ideally we will just use this, however there are compexities.

zh covers both simplified characters and traditional characters which I don't really understand (zh_HANS for (generic) simplified Chinese characters, and zh_HANT for traditional Chinese characters). See

http://stackoverflow.com/questions/4892372/language-codes-for-simplified-chinese-and-traditional-chinese

zh applies to china and taiwan but china and taiwan have different forms (There exist two standardised forms of the language, namely Putonghua in Mainland China and Guoyu in Taiwan). See:

https://en.wikipedia.org/wiki/Standard_Chinese

Technically we will be implementing something like 'zh-Hans-CN' for chinese simplified mainland china.

Then there is also mandarin versus cantonese

So @rouletout  I need you to do some research. What flavors of chinese do we want to implement?

This will effect how I propose to implement. If it is really only one flavor we want then I will just use zh and map some standard browser settings to our internal zh language.

**Comment by rouletout** [comment]
OK, will check that out and let you know

**Comment by scd** [comment]
Technically the zh code is Chinese, but this can mean a lot of different things. The standards seem to be
 - zh_HANS for simplified Chinese characters
 - zh_HANT for traditional Chinese characters

The issue is that different systems use different standards. Sometimes zh_CN (ie Mainland China) is used for simplified Chinese and zh_TW (ie Taiwan) is used for traditional Chinese. In fact this is what is mostly used, but it is stupid, because the CN is supposed to distinguish region differences of a langauge. So you get confusing things such as zh-CH, zh_CH-CH. 

So we are going to implement the technical correct way behind the scenes and map browser settings to our way of doing stuff.

@ulf could you get your Chinese translator to answer the following

 - [ ] If all the information you had is that a language is Chinese, without actually seeing the language, would you assume it is simplified or tradtional chinese characters? I need to know this because sometimes browsers are set to just zh langauge code, which means Chinese.
 - [ ] Confirm that Mainland China's language is simplified Chinese?
 - [ ] Confirm that Taiwan's language is traditional Chinese?
 - [ ] What form of the language is spoken in Singapore?
 - [ ] What form of the language is spoken in Hong Kong?

**Comment by scd** [comment]
@rouletout I have added Simplified Chinese as language code as zh_hans and Traditional Chinese as zh_hant

This is available on sandpit, so you can get started.

Please note that this will not be user selectable until after next upgrade.

**Comment by rouletout** [comment]
Here the answers to the points above, we should go with traditional AND simplified:

If all the information you had is that a language is Chinese, without actually seeing the language, would you assume it is simplified or tradtional chinese characters? I need to know this because sometimes browsers are set to just zh langauge code, which means Chinese.
Sam Answer - The simplified Chinese is major used in China. Even they have much more people than other area. However, the internet usage is limited by China government. The other area like Taiwan are usage the traditional Chinese. Therefore, most website in the world will offer both options. The conditions you assume what I will think is traditional Chinese.

Mainland China's language is simplified Chinese?
Sam Answer - yes

Taiwan's language is traditional Chinese?
Sam Answer - Yes

What form of the language is used in Singapore?
Sam Answer - before the traditional Chinese major. Now should be 50%50%

What form of the language is used in Hong Kong?
Sam Answer - Now Hong Kong is one part of China so that the simplified Chinese is the official usage. But most of them know both.

**Comment by scd** [comment]
I think this is done
