### ISSUE TITLE
show email status when using grant permissions web form

### ISSUE THREAD

**Issue by scd** [theCrag/website#2726]
We should show the users email when using the grant permissions form so that we know when to send them a manual email or an internal message.

**Comment by scd** [comment]
Note that we have to be a bit careful about this because we don't want anybody unauthorised seeing emails.

**Comment by brendanheywood** [comment]
The main concern is whether we need to send someone a message inside the platform or via email for free. Ultimately it should all be inside the platform and the email is just a notification rather than a key component. So just a message saying: No email | Unconfirmed email | Confirmed email should be enough

**Comment by brendanheywood** [comment]
I think this may not be needed. If it is still an issue, a really simple idea could be that we don't hand out permissions to anyone unless they have a confirmed email

**Comment by scd** [comment]
Closing
