### ISSUE TITLE
topo png endpoint is brocken

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2729]
**What happened?**

https://www.thecrag.com/topo/589719624/png?targetWidth=223&targetHeight=320

leads to 503

**What you expected:**

it shoudl work our Alto Mijares homepage needs that endpoint

**Comment by scd** [comment]
Hmmm this is serious and weird. This end point triggers phantomjs on itself so in the background we get something like
```
phantomjs headless/phantom/rasterize-topo.js "https://www.thecrag.com/topo/589719624?targetWidth=223&targetHeight=320" ttt
```
But this returns 'Unable to access network'

So I tried with just http and the error no longer occurs.

**Comment by scd** [comment]
Using http causes further errors and is not a long term solution because we do not want http anywhere.

Ok it looks like I need to use --ssl-protocol=any when calling phantomjs.

I don't know how the latest release caused this, but maybe it was already broken. I did change a default somewhere from http to https, so maybe this was it.

**Comment by scd** [comment]
FYI, this issue troubled me because this end point is so important for a lot of things we do. I am relieved that the fix was pretty simple in the end.
