### ISSUE TITLE
Climber page details

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2733]
**What happened?**

You need to slide right on each climber to fully visualise info, is it intended?
https://www.thecrag.com/climbing/world/contributors

**What you expected:**

All info visible

**Comment by brendanheywood** [comment]
Nope thats a bug. As an unrelated aside, how are you adding the urls into the github issues? Because they end up as broken links eg the link above you added in markdown as:

```
[https://www.thecrag.com/climbing/world/contributors](url)
```

which when you click on it goes to 'url' which is not a real url. If it was left as just a raw url without the []() then it would auto link. I've fixed up a few of these from your last couple issues. I suspect you are just clicking the link button and then not filling out both parts?

**Comment by brendanheywood** [comment]
Back to the way it should be in dev:

![image](https://cloud.githubusercontent.com/assets/187449/25432112/8205a878-2ac6-11e7-8b09-1e0d85934d3e.png)
