### ISSUE TITLE
Topo upload failing

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2753]
**What happened?**

So I just tried to upload a bunch of topos from yesterday and had the upload process fail in 3 different overlapping ways utterly thwarting me doing a pretty basic action:

* [ ] I uploaded a batch of a few topos, 1 file didn't upload which is not unusual. But there was zero way to recover from this, I could not make the file re-upload. Nor could not remove it from the batch. We need to be able to re trigger an upload.
* [ ] even though I had 9 files upload ok I could not progress to the next page in the process because 1 had failed. The process is a dead end and the user can't do anything at all! It should accept this and do what it can with the good files. 
* [x] because I couldn't progress I started again, and this time only upload a couple files. After I uploaded them ok on the next screen I got an error saying they were already submitted. Yes again another dead end and the user is trapped and can't do anything. This one was almost rage inducing - I'm not sure how many users would be this persistent but to try again and get denied completely and have absolutely no way to correct an issue that wasn't their fault in the first place is a pretty bad experience. 

Error Cannot continue process: information already submitted
State: 17218
Error Code: 2

CodeReference: CIDS::Process::SupplyInformation::InitialiseTopo, /opt/CIDS/perllib/CIDS/Process/SupplyInformation/InitialiseTopo.pm, 637

**What you expected:**
One of my fundamental over arching IX design principals is forgiveness, and wherever possibly gracefully recovering from errors 

http://www.jankoatwarpspeed.com/forgiveness-in-ui-design/

**Comment by brendanheywood** [comment]
Error

Cannot continue process: information already submitted

State: 17218

Error Code: 2

CodeReference: CIDS::Process::SupplyInformation::InitialiseTopo, /opt/CIDS/perllib/CIDS/Process/SupplyInformation/InitialiseTopo.pm, 637

**Comment by brendanheywood** [comment]
So tried a couple times to correct this, point 3 above is a complete no show. This is worth of a priority hot fix

![image](https://cloud.githubusercontent.com/assets/187449/25778071/8d226af2-3336-11e7-87a2-64709e7e7fdf.png)

**Comment by scd** [comment]
I am put. I will have a look when I get back

**Comment by scd** [comment]
It sounds like it was rage inducing :)

The bigger issue is that daemon is failing quite a bit and needs restarting. In this case even if the UI worked nicely it would still have failed and was failing for every topo uploaded until 5 minutes ago.

The rage quit issue is a mechanism I had put in to protect the system from duplicate entries when people press the reload button. In most cases it is not really needed and I have been taking it out when it becomes an issue.

The irritating thing with this is that you have to start the whole process again, so pressing the browser back button to the upload screen will not work. Most users would not even know that.

I have removed this code from the initialise topo.

Not worth a hot fix though because the root problem is still there. All we would be doing is changing the error message.

**Comment by scd** [comment]
I am wondering if we can close this. I know the topo upload UI is not great, but we have fixed two of the frustating issues. The already submitted issue was fixed a while ago and the application server crashing looks like it may be fine now since I made a fix two releases ago. Since then the application server has not crashed.

There is now a lot of noise in this issue. So I recommend with either close, reword the opening summary or close and open a new issue about enhancing plupload capability.
