### ISSUE TITLE
CPR - Ignored repeated asscent triggered when it should not

### ISSUE THREAD

**Issue by scd** [theCrag/website#2758]
**What happened?**

The route Bad Habits has been ticked twice and both ticks report that the ascent has been ignored.

https://www.thecrag.com/ascents/with-route-gear-style/sport/in-setting/natural/by/tiburonny/?sortby=rating,desc

(please also provide urls and screen shots)

**What you expected:**

The pink point should not report that the ascent has been ignored.

**Comment by scd** [comment]
I think I have found what is going on here. The direct statistic is correct, but the rollup statistic is incorrect.

Baselining the node statistic fixes the issue, so it is likely that there is something going on in delta mode for the stats processing.

**Comment by scd** [comment]
I think I have fixed this one. There was a logic flaw in delta mode for when ticking multiple ascents. I have hot fixed and am now re-running all the node statistics.

**Comment by FreddieChopin** [comment]
I think the issue may not be fully fixed. See these two ascents:
https://www.thecrag.com/ascent/3500590371
https://www.thecrag.com/ascent/3339039048

It says that they are ignored for the purpose of CPR, because these are repeates. Not only they are not (as I have only 1 ascent of each of them), but I actually have the only logged ascents of these routes on TheCrag.

**Comment by rouletout** [comment]
Hmm @FreddieChopin they are both eligible for CPR - do you see that as well now?

**Comment by FreddieChopin** [comment]
Seems to work fine for these two routes. I also don't see any other examples in my logbook.

**Comment by rouletout** [comment]
Closing
