### ISSUE TITLE
refactor dashboard notices

### ISSUE THREAD

**Issue by scd** [theCrag/website#2764]
Refactor dashboard messages into it's own template
 - [x] so we can call notices for other pages
 - [x] swap profile missing height message to a notice
 - [x] allow for start and end times for messages
 - [x] allow for messages not to be shown on new accounts if specified.
 - [x] instagram
 - [x] email verification
 - [x] translations
 - [x] hotfix

**Comment by brendanheywood** [comment]
This seems to be evolving into the same direction as 

https://trello.com/c/B3T0lY8m/62-prepare-platform-for-mailing-campaigns-to-users

Maybe we should cross check the requirements and filters so that later on this is as simple as adding the email component as an alternate output to the dashboard and we save a bunch of code

**Comment by scd** [comment]
I think there is a very small overlap for dashboard notices and email. Dashboard notices are not delivered, but rather just triggered. Note that nothing is stored in the database for dashboard notices, except for a tag saying the user has discarded the notice so it does not appear again.

You are right, if we want to deliver internal messages, so any platform development we do should allow for both internal messages and email. 

Perhaps I should share my thoughts about what I recommend we implement on the email side of things. I have just done a really cool development in my other commercial system. I have documented my thoughs here:

https://docs.google.com/document/d/1RrjFlrhNXKDCPz6t_60AlwN0muKeTyZLobVesuyK2v4/edit#
