### ISSUE TITLE
api/index/detail is not working for lower than TLCs

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2790]
**What happened?**

https://sandpit.thecrag.com/api/index/detail/436557324?withdata=NodeID%2CParentID%2CName%2C&abbr=0&key=xxx

does not work but the TLC (parent of the sector above) works:

https://sandpit.thecrag.com/api/index/detail/11880457?withdata=NodeID%2CParentID%2CName%2C&abbr=0&key=xxx

**What you expected:**
as discussed this endpoint should return the subtree regardless of TLC or lower level

**Comment by scd** [comment]
@nicHoch please add to=leaf to the query. 

The to parameter determines the stopping behavior of the query. If it is not specified the system tries to work it out, and in this case it worked out to stop at tlc. 

It is more efficient if you always have a to parameter. The choices are:
  * leaf
  * arealeaf
  * tlc

And after I enhance it we will probably also allow something like `child`.

**Comment by scd** [comment]
Nicky can you please confirm this works and close the issue. Also I have done the child stopping condition (plus a bit of a refactor). So your app should now use one of the following in it's to parameter

  * leaf
  * arealeaf
  * tlc
  * child

I had to do quite a bit of refactoring because I wanted to align some code so it uses a common function. Please be aware that I have made significant changes on sandpit when testing your app. There is a chance I have broken something even though I have done a bit of testing.

I have not updated prod, but as soon as you give me the go ahead I will also update prod.

**Comment by nicHoch** [comment]
- [ ] leaf
- [ ] arealeaf
- [ ] tlc
- [ ] child

what is the idea of arealeaf ?

**Comment by scd** [comment]
arealeaf excludes routes. This is usefull if you are just doing maps.

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
scd@thecrag.com
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by nicHoch** [comment]
is looking good
