### ISSUE TITLE
api/index/detail areaType data should lowercase labels

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2799]
the areaType in the api/index/detail API is upercase like "Area, Crag" but should be area,crag ...

**Comment by scd** [comment]
This is not a simple change because it is in the database as title case. If I change it then it should be changed consistently throughout the system. For example area templates use title case, for example:

```
subType": "Region",
```

Also if we change it then it will be a breaking change for every consumer of the API. 

I presume that you want it lower case so you can use it as a stub for language keys. If this is the case then we should think up a different solution which does not have such far reaching consequences.

What about having a parameter like use_translation_stubs=1 as an api parameter which will then return the translation stub for each of field that could be returned as translation stubs. Actually the full translation stub may be returning too much repeated text so something like use_stubs=1 which just returns the variable component of the translation stub.

Alternatively if this is the only field that is effected then we could define another field called AreaTypeStub

@nicHoch please outline your preferred solution

**Comment by nicHoch** [comment]
please add NodeTypeStub and AreaTypeStub as with parameter and only return the variable part of the key.

**Comment by scd** [comment]
If you add `stub=1` to the url query then you get various fields translated to their stubs. We may need to discuss this a bit further. There fields that are effected by this parameter are:

 - [ ] NodeType (see discussion below)
 - [ ] History (not implemented but should be - see discussion below)
 - [ ] Description
 - [ ] AreaType
 - [ ] GearStyle
 - [ ] AlternateName
 - [ ] Topo

@nicHoch please let me know if this causes problems with app functionality.

NodeType Discussion
=====

Internally the stub for a Route node type is `climb`. Initially one of the reasons why I did this was because of the similarity between `route` and `root` node types.  I think we are better off just using `route`, because there are many other places in the server that this has been used as `route`. 
 - [x] Current solution uses `route` for trial purposes
 - [ ] Nicky to confirm if he is happy for the app to use the NodeType stub `route` over `climb`. 
 - [ ] Simon to add translation key for route as well as climb.


History Discussion
====

This should be implemented as a stub (eg first-free-ascent), however there are currently no translation keys.
 - [ ] Current solution does not implement History as a stub
 - [ ] Nicky to confirm what he wants
 - [ ] Simon to add translation keys if we want to change

**Comment by nicHoch** [comment]
what data is translated in 

TOPO?

**Comment by nicHoch** [comment]
is the stub=1 already working?

I see now effect on sandpit:

https://sandpit.thecrag.com/api/index/detail/world?key=XYZ&withdata=NodeID,ParentID,NodeType,AreaType,TLC,Name,Webcover&abbr=0&stub=1

**Comment by scd** [comment]
Yes it should already be working.

In the topo there is an object type in the array.

**Comment by nicHoch** [comment]
could you please send an example: 
this is not working:

https://sandpit.thecrag.com/api/index/detail/11742859?withdata=NodeID%2CParentID%2CLastUpdated%2CSiblingSequence%2CNodeType%2CName%2CPoint%2CAreaType%2CNumberAscents%2CNumberRoutes%2CNumberTopos%2CPopularity%2CTLC%2CAlternateName%2CDescription%2CTopo%2CTag%2CGearStyle%2CGrade%2CStars%2CHistory%2CRegisteredGrades%2CWebcover%2CFence%2CCountryNodeID&abbr=0&to=child&stub=1&key=xyz

**Comment by scd** [comment]
sorry my bad, try `stubs=1`

(ie change stub to stubs)

**Comment by nicHoch** [comment]
yes this is coming along nicely. To adapt  in  the app by Nicky:

- [ ] NodeType
- [ ] History 
- [ ] Description
- [ ] AreaType
- [ ] GearStyle
- [ ] AlternateName
- [ ] Topo

**Comment by scd** [comment]
Closing as mostly done and remaining issues can be written up as separate cards.
