### ISSUE TITLE
In favorites and webcovers facet pages show new crag summary cards

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2823]
**What you expected:**

* add gear style breakdown
* add total routes
* add total ascents
* add num of total favs

All this should be in exactly the same format as in the main index template

**Comment by brendanheywood** [comment]
Also I think for consistency we should swap the json nesting. ie instead of being a list of webcovers which contain a node, it should be a list of nodes which have a webcover. Do we care about showing two webcovers for those nodes which have more than one?

**Comment by scd** [comment]
I will do template data

> Do we care about showing two webcovers for those nodes which have more than one?

Because it is a webcover search I think we want to show one webcover per area. If there are mulitple webcovers assigned then we should dup the node and show the expicit webcover.

I am still committed to do the slide show webcovers at a crag area if there are multiple web covers. We just have to make sure it makes sense in the facet.

**Comment by scd** [comment]
@brendanheywood good call about restructuring the webcover facet data. This is now done and we get the rest of the issue done for free.

You can pull from repo. Please close when you confirm it is what you want. 

Also let me know what you want for the home page.

**Comment by brendanheywood** [comment]
dev has old data, and for some reason the ajax to save webcovers is busted so I don't have nor can make any webcover test data. @scd can you please fix which ever is easiest?

**Comment by scd** [comment]
easiest is just to resync. I actually forgot to do the post release syncing which I have started this morning. 

I probably will not sync to your dev until this afternoon

**Comment by scd** [comment]
Dev has been resynced.

**Comment by brendanheywood** [comment]
Check this out:
https://dev.thecrag.com/climbing/world/webcovers

This is almost there but missing a few bits of data:
https://dev.thecrag.com/favorites/by/brendanheywood

@scd can you please:
* [ ] add webcovers to favorite->node, I think this probably needs it's own atom, or should be an option in the atomArea

* [ ] We should decide what we are going on the second page when there is not yet a webcover for a given node. I'm kinda a fan of exposing it as missing nice image icon to prompt people to add it, rather than choosing something automatic, but I could go either way.

**Comment by scd** [comment]
Nice work.

We should expose as missing nice image icon.

One of these webcovers will end up on the home page, rotating every month or so?

**Comment by brendanheywood** [comment]
> One of these webcovers will end up on the home page, rotating every month or so?

Something like that, more likely that we will fit 2-3 of them in a section. We can cross that bridge when we get to it.

I've added a fallback to a map if it is located:

![image](https://user-images.githubusercontent.com/187449/28120305-f68d7c0e-675a-11e7-9b79-bcdafd5ddf75.png)

and if not located then just a gradient placeholder.

* [ ] @scd I have added an IncWebCovers option to atomArea and used it in the favorites facet. There is probably a bunch of refactoring you can do elsewhere to use this. Please review that code and then this issue is done and can be closed

**Comment by scd** [comment]
@brendanheywood have you pushed all your code. I cannot find IncWebCovers

**Comment by brendanheywood** [comment]
doh try again

**Comment by scd** [comment]
On a cursory look it seems fine. 

One gothca here is that if a photo is associated with another copyright other than ours then you must have the copyright param included otherwise it will return nothing. The idea is that you should always be dealing with copyright when querying a copyrighted photo.

There is the image bug you alluded to in #2837 so I am going to keep this open until this is also fixed.

**Comment by scd** [comment]
I re added the copyright param.

From a performance perspective I prefer to do the `selectWebcovers([$id])` on a list of ids rather than one at a time. I think having a IncWebCovers option in atomArea is valuable when you want minimum coding effort. 

With facets we have a list of nodes we need to get the web covers for, so typically I would do that outside the atomArea and pass through the results into atomArea. I am happy to just leave it as it is in the fav code for now.

**Comment by brendanheywood** [comment]
yeah sounds good, I was going to ask you to add the data but I was too keen to get it finished last night
