### ISSUE TITLE
Dynamic and editable facet filtering title idea

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2827]
**What happened?**

Check out this:
https://www.kickstarter.com/discover/tags/kickstarter-gold?ref=discovery_overlay

![image](https://user-images.githubusercontent.com/187449/27918851-898d26d2-62b3-11e7-83ae-b1c1ac5ca0b0.png)

**Comment by scd** [comment]
I am not so keen on this. I prefer a nice clean title and we have lots of facet components. I think keeping the title and filter separate will give us more flexibility, especially coming up with a responsive design.

I am happy for you to keep this open and try and convince me, otherwise please close as won't be done.

**Comment by brendanheywood** [comment]
ok, I'll close this
