### ISSUE TITLE
Sandpit is being crawled by google

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2856]
**What happened?**

https://www.google.com.au/search?q=bonnies+roof+in+the+gunks%20site:thecrag.com

![image](https://user-images.githubusercontent.com/187449/28497153-ce543bb2-6fc3-11e7-82a7-6a9b3ab2beb2.png)

See full list here:
https://www.google.com.au/search?q=site:sandpit.thecrag.com

**What you expected:**

This result is curious because google did find the main www site too but decided that sandpit should be shown as the canonical.

* [ ] as a second level of defense, I think all environments should server their canonical url as being the prod www so if they are scraped then the don't split page rank and also don't get counted.
* [ ] non prod urls should not be crawled via robot.txt  Given that these pages are already out in the wild, we should add the canonical first, wait a month, and then fix the robots.txt

**Comment by scd** [comment]
I have updated headTag template so that it always uses canonical as https://www.thecrag.com/...

I have updated the sandpit build process so that it uses the dev robots.txt file, but for now kept it as the prod version. After next release it will be updated.

Sandpit code has also been synced with prod so that canonical is working. Checkout 

https://sandpit.thecrag.com/climbing/australia/grampians/mt-stapylton-amphitheatre/route/14980147

This issue can probably be closed unless we want to do some further post release checking.

**Comment by brendanheywood** [comment]
I'd prefer to close this once I know google has been fixed, so lets keep watch on this. I haven't added sandpit to the google search console yet, if I did I could force a recrawl of that one url but I'd like to make sure the whole class is going to get fixed.

**Comment by scd** [comment]
I just checked and it seems to be producing the right results now. Closing
