### ISSUE TITLE
Proposed Ground Up red point tick type

### ISSUE THREAD

**Issue by scd** [theCrag/website#2883]
From a member...

As I mentioned on the fb page, I'd love to see a 'ground-up' ascent added to the list of possible styles as there is a very strong ethic of this style of ascent in the UK trad-scene.

I will admit that semantically a redpoint and ground up ascent are very much alike however there is a difference - it one of both attitude and process.

Suppose for example that I attempt to onsight a route and fall. What happens next dictates whether a subsequent clean lead will be a redpoint or ground-up ascent. If I were to pull on the ropes back up to the highest piece of gear/bolt, rest, inspect the holds, try the sequence out, then go bolt-to-bolt all the way to the top, then when I lead the route cleanly it would be a redpoint ascent. i.e. failed onsight -> dog -> clean lead = redpoint

In comparison, if after I fall I instantly lower to the ground, pull the ropes, tie back in and then lead the route cleanly, the ascent would be a ground-up ascent. Although I have climbed part of the route cleanly, I haven't inspected the holds where I fell and everything after the point that I fell is technically an onsight. The main crux or even a second or third crux could be waiting after the point at which I fell. In this way a ground-up ascent differs from a redpoint. i.e. failed onsight -> lowered off -> clean lead = ground up.

**Comment by brendanheywood** [comment]
This is probably the 3rd person asking for this and seems good to have.

As an aside even though issue #1217 is closed I've still been tweaking and maintaining the list of dimensions for ticks here:

https://github.com/theCrag/website/issues/1217#issuecomment-121139883

I'm also cross linking to 'onsight solo' #1320 + #2835 as it makes sense to add these in a batch

Thinking through this:
> failed onsight -> lowered off -> clean lead = ground up.

It seems to me that there is 2 or maybe 3 new tick types:

* ground up onsight - which is exactly the same as an onsight so isn't needed
* ground up red point
* ground up pink point

In the example given, technically we'd call that a pink point if half the gear was on from the previous attempt and then you pull the rope and retried. But if it's immediately after then perhaps people call this a red point, and it seems like most people over a certain grade would call this red regardless and never pink. So I'm thinking we can probably get by with only adding a single new tick type which is 'ground up redpoint'. I don't think any other tick types are on high enough ethics to consider having the ground up option. eg a flash has beta so doesn't quality.

I've also got the icon ready to go for whenever we get to this:

![image](https://user-images.githubusercontent.com/187449/29353232-dba06592-82ac-11e7-9562-f8f6f0e4c3b2.png)

https://brendan.thecrag.com/svg/groundupredpoint?v=1

![image](https://user-images.githubusercontent.com/187449/29353503-b6ed60f0-82ad-11e7-97bd-365ac8eae50e.png)

**Comment by scd** [comment]
This is done in simon's dev

![tc-groundupredpoint](https://user-images.githubusercontent.com/373058/29506238-f5ffc22c-868d-11e7-95d9-ec35531af487.png)

I have also written some guidelines for what is involved for adding new tick types:

https://docs.google.com/document/d/1PVvSjEHehxOPiKtl1Y_cchk8O7NrgMRoZ9-IIle9e8A

**Comment by scd** [comment]
@brendanheywood I just looked at issue #2835 and you have already done the svg for onsight solo. I will preplace what I have done with yours.

**Comment by scd** [comment]
From Philip, he thinks that ground up is a multi pitch tick type

'Yes, a ground up redpoint means, that you start a multipitch and climb each pitch without falling once. Redpointing a multipitch means, that you did each pitch in as a redpoint, but it is ok if you fall, to lower to the last stand and redo it.

https://www.thecrag.com/discussion/1413505461/release-57---tick-images

**Comment by Drazhar** [comment]
So I'm Philip,

My main suggestion is, that in the help it should be mentioned, that the ground up tick type is just for multipitches. 
My main issue is, that there are so many tick types and for many beginners it is completely confusing and daunting. And now you even have two types which have the same description (redpoint and ground up redpoint).

**Comment by brendanheywood** [comment]
@Drazhar this isn't my understanding at all. Ground up means you had as many attempts as you needed, but all of them were from the 'ground up' with no inspection on rap, and if you fell then you lowered and started over. It applies equally to all styles including trad and sport, regardless of single or multi pitch and potentially even high ball boulders where other people might top rope it first.

Top few hits in google are all in agreement with this:

> Ground-up means climbing a route without top-rope or abseil inspection (you climb from the ground up). It usually means the route was attempted onsight/flash and then a fall (or a few falls) were taken.

https://www.ukclimbing.com/forums/t.php?t=439073

> Ground up - To climb a route, starting at the bottom, and working your way up. You might take some falls, return to the bottom and start again.

https://www.thebmc.co.uk/climbing-how-to-talk-the-talk (from google cache)

> Ground Up Attempting and climbing a problem or route without inspecting it from a rope and starting from the ground on each attempt.

http://threerockbooks.com/index.php/bouldering-terms/

Ground up still also applies to multi pitch too: the generally accepted definition here is that if you fall you go back down and try again. But the subtle difference is that you only have to go back down to the last non hands rest, (which is usually the last belay), rather than all the way to the bottom.

An extension to this is when routes were bolted on lead too, vs rap in cleaning and bolting. Ground up bolted routes in some circles are consider more pure, but more widely have a reputation for often being a bit shit and unsafe because the bolts are always where the good stances were and not where you actually need them.

There is also a second less common complication in the use of 'ground up' which is if you have sieged a multi pitch via rap inspection and sent every pitch, you might like to go back and then re-attempt the whole thing ground up. For example Ondra worked and sent every pitch of the dawn wall, and then once it was all dialed he want back and did the "ground up" ascentt. Importantly note that he still took lots of falls on several pitches, so he didn't do the whole thing end-to-end perfectly clean in one go. But when he did fall he still went back down to the start of that pitch.

> November 14, he began his ground up push on the Dawn Wall, .... He fell nearly a dozen times before calling it quits for the day.

https://www.outsideonline.com/2138561/how-adam-ondra-pulled-dawn-wall

I think for our purposes we just need to cater for the first meaning which is by far more common, and what we had several requests for. The second meaning I think could be mentioned in our help docs, and people can just mention this in their ascent comments if they care.

Stepping back, I think a good litmus test to help us decide things related to tick types is whether it could potential affect cpr. We don't need to get the exact values right now, but it sounds reasonable to me that a person who "ground up"'s a route should get a bit more cpr for that ascent than someone who top ropes it and then red points it. We give more cpr for an onsight, and a ground up is kinda half way between an onsight and a red point.

**Comment by brendanheywood** [comment]
This is live:

https://www.thecrag.com/article/TickTypes#groundupredpoint
