### ISSUE TITLE
Rework the wording of the email verification token message

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2890]
**What happened?**

"We are unable to send you a verification email because of the following error: Token does not match account."

**What you expected:**

I'm a bit confused about the flow here so I might have this wrong, but:

* [ ] Firstly "We are unable to send you a verification email..." seems wrong, aren't we on a page that we got to by clicking in an old email? Isn't this an issue with *processing* the link in that email, and not *sending* that email ??

* [ ] There is no call to action here, and no info about why the error actually happened. This just forces people into emailing us. It should say things like:

 "Sorry we couldn't verify your email, it looks like you are logged in using a different account, please try logging in again ..."

or

"Sorry we couldn't verify your email, it looks like that the email might have been old, please do blah to re-send the email (with link)"

**Comment by scd** [comment]
+1 another supporter email today

**Comment by brendanheywood** [comment]
An idle thought, should we care at all if they are logged in using another account? The only thing that matters is that they a) got the email and b) they decided to click on the link. Perhaps the page they go to should just work and ignore who they are logged in as, or even whether they are logged in at all.

**Comment by scd** [comment]
Maybe this is ok. I suspect that what is going on is that an old verification link was clicked. I would have to look up the data structure, but my guess is we have done a one-to-one on the account / verification code. This probably should have been a one-to-many so that any old link could be clicked and it would be verified. Actually is probably should be one-to-many on the actual email rather than the account.

**Comment by scd** [comment]
I think we revamped this a while ago. Closing.
