### ISSUE TITLE
Forum email notification for now reason eg 0 unread

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2891]
**What happened?**
Why did I get this in an email?

![image](https://user-images.githubusercontent.com/187449/29499253-b1fa6024-8650-11e7-93f8-2a038742d75d.png)

I still have '1 unread message' in my dashboard which I cannot get rid of and I've had for months from some deleted thread. Possibly related.

**What you expected:**
* [ ] should not have got a notification in the daily email

**Comment by scd** [comment]
I know about this. I am going to look into it after I sync my dev with a new copy of the database. I don't want to debug this one on prod.

**Comment by scd** [comment]
The root cause for this is two different fields for determining if a message is read. This is done for optimisation purposes. These fields have become out of sync. 

I am not really too concerned why the fields have become out of sync, but more the impact when they do. I have made some changes that minimises the impact:

 - [x] The discussion is not hidden on your dashboard so you can find out which discussion is causing grief.
 - [x] If you open the discussion it now uses both fields to determine if the read status needs resetting.

This means to fix the problem you just have to re-open the discussion.

Hot fixed
