### ISSUE TITLE
Translations: make it possible to identify changes to already translated keys

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2899]
**What happened?**
If the English text of an already translated key is changed it is currently impossible to filter for these keys and ensure that the translation is carried forward to all available languages.

(please also provide urls and screen shots)

**What you expected:**
Easy way to tag / identify changes to keys

**Comment by scd** [comment]
Does this method clash with our other requirement of making the english editable using our software interface?

**Comment by brendanheywood** [comment]
I can't see any reason why these would clash. We'd just need some discipline when adding the original keys, or ideally we could add the keys within that same gui.

A few other requirements I'd like further down the timelines to keep in mind when extending this system:
* [ ] for every key, have an example url for where we can see that key in action. This example url could be at a higher key prefix level so apply for a whole set of keys in one, will make the translators job much more tangible to see things in context - especially for keys which need to fit in a certain layout space
* [ ] see a list of places each key is used, in particular show a report of keys which are not longer used

**Comment by scd** [comment]
Ok I missed something in your explanation. We do not automatically commit after an edit in the UI, but rather I manually commit from time to time. I can see there is no clash if a micro edit is done which saves the updates on the server then does a git commit on the file. There may be other issues, like not making the save and commit blocking.

One thing I like about the way I currently create articles in the translation database, the multiline capability makes it much easier to architect.

Note that is is only the english version of the langs which have multiline keys in the saved files.

**Comment by brendanheywood** [comment]
> We do not automatically commit after an edit in the UI, but rather I manually commit from time to time.

I suspected this, we need to implement this. We also need to do semi regular auto push /pull, but that can still be manual for a bit

> There may be other issues, like not making the save and commit blocking.

I'd do some simple data checks, when you load a string into the web gui store a time, when you save if that date is older than the last mod date (either the file last mod which is easy or the key git blame last mod date) then barf and make them reload so they have the latest version of the key. It's brutal but with our numbers of translators this is a small edge case.

We will probably also need a git repo level file lock so commits are serial and don't clash as we only have one git working directory.

> the multiline capability makes it much easier to architect.

I'm only talking about the way the json itself is serialized, not the contents in the json. I totally agree we should have multi-line strings, but each of those should be a single line in the json.

```
"key": "line 1\nline2",
```
vs
```
"key": "line 1\n\
line2",
```

I find editing these files to be pretty painful with all the escaping etc, I'd prefer to just be able to edit english the same as any other language. Editing the long English article string keys is the worst.

Note there is nothing stopping us right now from an ajax helper so that if you are in a dev system you could just inline edit the text strings directly in the context of the page. This would be infinitely easier and I think the end game here. In particular this would mean editing the articles would be a complete breeze and the authors can do that directly in the article.

**Comment by rouletout** [comment]
I think we have an established management process now, even when it is a lot of manual activity. I close this for now.
