### ISSUE TITLE
Image handling: delete duplicates

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2921]
**What happened?**
During the review process we are observing loads of duplicate images and could easily delete them during the review process. Is there a simple way?
The deeper issue is a user interface that is not handling nework interruptions or poor connections very well but until this is fixed it would save space and make the views "cleaner".

(please also provide urls and screen shots)

**What you expected:**
A procedure to deleet duplicates during the review and later

**Comment by scd** [comment]
The duplicates is because people think the photos are failing due to a long sync process. This is pretty shitty and I have vastly improved this my development server for next release. The sync process is now non-blocking so moving from one upload screen to the next is fast. There is a spinner which makes it look like the photo is loading while you fill in photo details.

I have also added a link to the photo template from the assess photo screen. This is only on dev, but you can get there manually by constructing the url from the photo ID, for example:

https://www.thecrag.com/photo/1234

Where 1234 is the id you can copy and paste from in the Status field on the Assess Photo page.

Once you are at the template:

    Click on the 'Edit' link
    Click the disable photo button. (note just the disable photo, not the delete photo).

Then back on the assess photo page check the 'Exclude' index quality grade. This probably does not matter so much, but may as well align with the disable status.

**Comment by rouletout** [comment]
Foto upload has been improved, duplicates are rare, closing
