### ISSUE TITLE
date format issues for bulk import

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2973]
**What happened?**
an sandpit i tryed to import a file with 16.000 routes.
Unfortunately there is a date error somewhere. but the tool does not say where.

please try: ./import-area -W 0.0002 -H 0.0002 1521409137 692089023 bompar.xls

error: Day '0' out of range 1..31 at ./import-area line 1171.

**What you expected:**
in case of hard errors it would be nice to see the line number that crashes the import from the import file not from the code script only

**Comment by nicHoch** [comment]
hi simon
any time estimates for that one.
I simple print statement which line causes the error would be sufficient as a hot fix.

**Comment by scd** [comment]
On the weekend. The problem is that I am on non crag days wed-fri.

There are a couple of urgent things due and they are all in different spots
so it is possible I miss things at the moment, so if I do not do this by
Saturday please email me again.

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
scd@thecrag.com
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Instagram <https://www.instagram.com/thecrag_worldwide/>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by scd** [comment]
@nicHoch  I have made the update so it reports the line and column that it fails on. Actually this is a strange unexpected edge case where an Excel cell with a properly formatted date is giving us something that is causing an error. Once we find the row then I expect this will uncover another issue I have to resolve.

Could you make sure you do a test run with this before you do on prod and visually check dates are coming through ok.

I have updated on both prod and sandpit. Please close when you verify correctness.

**Comment by nicHoch** [comment]
@scd thx that output really helps. And especially the column number in that case. It was not a incorrect date it was the name. The route name was "7:30" and automatically changed to a date/time cell in excel (one function from excel that i really hate that date auto format).

so i close that
