### ISSUE TITLE
Webcovers should not allow links to disabled / removed photos

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3017]
**What happened?**

1) a photo was added
2) a webcover was linked to this phot
3) the photo was disabled / removed
4) the webcover remains

https://www.thecrag.com/discussion/1638938913/release-58---webcover-view

**What you expected:**

Either one of these:
* [ ] when a photo is disabled the webcover link is removed
* [ ] the webcover facet excludes ones which are linked to disabled photos

**Comment by scd** [comment]
This photo has been unlinked from a node

https://www.thecrag.com/photo/1639861356

But is still a webcover. The template is missing the javascript that allows it to be removed.

**Comment by scd** [comment]
So I had already made the disable photo and remove photo buttons to be not available if the image is a webcover. Once a photo has made it to become a webcover, I really don't want somebody to remove the photo. It has to be first removed as a webcover before it can be removed.

This problem here was the unlinking the photo. You should not be able to unlink or relink a photo that is a webcover. 

I have also fixed the javascript so if it does happen you can still remove the webcover.
