### ISSUE TITLE
opensearch points to wrong search page

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3018]
**What happened?**

The page https://thecrag.com/search is active, but not reachable from the main page. I usually arrive there when using Chrome's bulitin search from the address bar.

This search doesn't yield a faceted view, but instead a strange tabular display. Furthermore, Unicode is not accepted there.

**What you expected:**

Make the /search page call the same search as the one on the main page.

**Comment by scd** [comment]
I have fixed this so the search uses the same search template as the main page. 

@quaestor can you explain in more detail how you get to this page, because we are not really using this page internally and I am confused as to how chrome takes you there. In otherwords I want to be able to reproduce what you do.

@brendanheywood the main search was broken so I have made a few fixes there. In particular it was doing a search on the node id, so I have changed it to take me to the crag directly if it is selected. I also updated the template so you can specify the reference node. Also I removed a backend efficiency issue with the sql so that we can now start the search at zero characters.

**Comment by quaestor** [comment]
I just type "thecrag" in may address bar, followed by [TAB], then it gives me the opportunity to enter a search term.

<img width="659" alt="screenshot 2018-01-22 00 47 25" src="https://user-images.githubusercontent.com/54371/35200384-deccbcc4-ff0d-11e7-836a-9ef324c56cb5.png">

That used to work. I deleted that entry now and it was not automatically recreated, so I presume I added this myself a few years back. Sorry for the fuss.

However, I don't know how Chrome usually determines search fields on webpages, but since it doesn't automatically do it for thecrag, this might be worth investigating, so people get that feature for free, without adding a search engine on their own.

**Comment by scd** [comment]
I also have something in chrome which points to theCrag as a search engine

![screenshot from 2018-01-22 11-26-02](https://user-images.githubusercontent.com/373058/35200755-936802ca-ff67-11e7-9b6d-2adf940c513a.png)

I am unable to work out how to use it though.

@brendanheywood do we want theCrag to be a search engine in browsers?

**Comment by brendanheywood** [comment]
Yes supporting 'opensearch' is a feature, it's even documented here but out of date:

https://www.thecrag.com/article/search

See also:

http://www.opensearch.org/Home

What I don't know is wether if we change our open search xml definition file wether each browser will auto update the definition:

https://www.thecrag.com/open-search.xml

**Comment by scd** [comment]
Hmmm I had totally forgotten about this.

So rather than use

http://www.thecrag.com/search?S={searchTerms}

We should probably use:

https://www.thecrag.com/nodes/fuzzy-search/{searchTerms}

I cannot get the suggestions working though?

**Comment by lordyavin** [comment]
The same issue for me on Firefox ESR. Added theCrag as search engine as proposed by Firefox and gave it a try. The result for searching the term "Donautal":
![grafik](https://user-images.githubusercontent.com/1528540/35209490-8780dcc0-ff4e-11e7-8e18-456f9d8b10b1.png)

**Comment by brendanheywood** [comment]
also url encoding is different to parameter encoding, so opensearch expects things like

https://www.thecrag.com/nodes/?fuzzy-search={searchTerms}

instead of:

https://www.thecrag.com/nodes/fuzzy-search/{searchTerms}

so need to test with a search query which includes slashes or & as a test

http://www.opensearch.org/Specifications/OpenSearch/1.1/Draft_3#OpenSearch_URL_template_syntax

**Comment by scd** [comment]
From the specification:

```
 The "searchTerms" parameter

Replaced with the keyword or keywords desired by the search client.

    Restrictions: The value must be URL-encoded. 
```

So I think it should be ok.

**Comment by brendanheywood** [comment]
In fact it is already broken in a similar way from the main search in the top right corner already, as well as also in the facet search form:

https://github.com/theCrag/website/issues/3020

They need to get fixed first and then I'm still pretty sure this will need to get swapped to the query param version in order to work properly with opensearch, eg either of these work right now:

https://www.thecrag.com/climbing/world/nodes?fuzzy-search=nought

https://www.thecrag.com/nodes?fuzzy-search=nought

**Comment by brendanheywood** [comment]
I've just set up a test example, this should work and find a route called 'nought / crosses' but does not:

https://brendan.thecrag.com/climbing/australia/new-south-wales-and-act/northern-tablelands/nodes?fuzzy-search=nought%20%2F%20crosses

https://brendan.thecrag.com/climbing/australia/ebor-gorge/route/13332313

Also is there an search indexing lag after renaming a route? this could be a red herring if there is. I noticed this didn't work either which I would have expected to even in the current state:

https://brendan.thecrag.com/climbing/australia/new-south-wales-and-act/northern-tablelands/nodes/fuzzy-search/nought%20crosses/?sortby=at,desc

**Comment by quaestor** [comment]
It also seems like the search page has no mobile version. Clicking the magnifying glass icon on the main page changes to the desktop view which is hard to navigate on small screens.

**Comment by scd** [comment]
I am not sure what exactly needs to be done for the release and what we are pushing to do later. But what I have done is made:

https://www.thecrag.com/search?S=arapiles

Show results. There is some code that is commented out, but the way it was formatted was absolute crap. So now I have areas call the `card-crag` template. Is there an equivalent `card-route`?

I think I have done what must be done for the release.

**Comment by lordyavin** [comment]
Is the production site already fixed? I don't get any result if I call the mentioned URL. Looks like the search field is filled but the query not executed.

**Comment by brendanheywood** [comment]
@lordyavin no generally we don't hot fix things unless they are either trivial or critical, and if we do then we state it in the issue

**Comment by lordyavin** [comment]
Please excuse me. I was attracted by the production URL.

**Comment by brendanheywood** [comment]
This is now done, the open search url hasn't changed it's just we now have something sensible at this location see https://github.com/theCrag/website/issues/2881
