### ISSUE TITLE
Route with grade range badge render issue

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3019]
**What happened?**
Added a [new route](https://www.thecrag.com/climbing/germany/area/563192130) with a grade range to a gym. The text "7 to 7+" does not fit into the badge.

![grafik](https://user-images.githubusercontent.com/1528540/35208957-20cab274-ff4b-11e7-9e85-c2d8c6ef4fbe.png)

**What you expected:**

* [ ] Display max grade only or make it fit.

**Comment by lordyavin** [comment]
Hey guys, any reaction on this?

**Comment by scd** [comment]
No reaction right now. It will probably end up being a slash grade

**Comment by nicHoch** [comment]
@scd  it is a render problem that get not solved by a slash grade.
XIIb/XIIc will never fit into that badge as well.

**Comment by scd** [comment]
XIIb/c

On Feb 15, 2018 08:00, "Nicky Hochmuth" <notifications@github.com> wrote:

@scd <https://github.com/scd> it is a render problem that get not solved by
a slash grade.
XIIb/XIIc will never fit into that badge as well.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/theCrag/website/issues/3019#issuecomment-365743627>,
or mute
the thread

**Comment by scd** [comment]
I think this will mostly go away next release with a change to grade displays. It should now look like 7/7+

There may be some grades that still spill, but it is much less of a problem.

**Comment by lordyavin** [comment]
Great. Looking forward to confirm the fix.

**Comment by brendanheywood** [comment]
Confirmed this is working now
