### ISSUE TITLE
Multi-pitch grade display

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3024]
**What happened?**

It is impossible to identify first pitch grades without opening the route page. When at a crag with a mix of single and multi-pitch routes (e.g. https://www.thecrag.com/climbing/mexico/el-potrero-chico/area/11932111) it is a painful process to select routes by grades if you just want to do single pitch sport routes as the grade of the multi-pitches shows the hardest grade only. 
You are likely to miss e.g. a good warm-up route if the first pitch is 5.10b but the multi-pitch is graded 5.12c.

(please also provide urls and screen shots)

**What you expected:**

Propoer display of pitch grades or at least first pitch grade in the crag view. I think we have a similar request for PDFs.

**Comment by scd** [comment]
For example you can see the first pitch grade for Estrellita? However I cannot see any other multipitch routes in the crag info. 

Is there any reason why we cannot add pitch info to the description of each multipitch route. I would expect a proper description.

Given that properly worked descriptions are missing do we also show the pitch grades and distances in a summary at the top of the description. In terms of Estrellita it would be duplicate information, but may be valuable information for other routes missing this in their description.

Even if we do this, I think we want to still know what climbs can be done as a single pitch route. You may not be able to easily wrap off some multipitch routes, or should we just assume that all multipitch routes can be done as their first pitch only.

If a lot of people are ticking first pitch only then I think we should improve the ticking process as well, so that they can choose to tick either the full route or the first pitch only.

**Comment by rouletout** [comment]
You see, even when you know what you are looking for you miss it ;-). There are more multi-pitch routes in this crag, Thunderkiss (listing all individual grades for each pitch) - this is a very common problem for e.g. almost all sectors in Potrero Chico and elsewehere.

We can not expect full text description for each multi-pitch but we should show grades.

Also, if you can climb the first pitch I assume you can get down - there may be weird edge cases but what goes up comes donw - at least on pitch 1.

**Comment by scd** [comment]
I think the best thing to do here is just to put it in as you requested and see what happens.

It did trigger some other issues.

 - [ ] citations of grades from private accounts are not transparent - now made it transparent but do not name the account
 - [ ] if there are multiple citations matching the number of pitches then there is no way to control which one the system picks - now pick the last contribution so at least we can have some control. I think we need an official multipitch grade citation so it can be controlled.
 - [ ] the one it picks for Thunderkiss has some extra unwanted stuff at the beginning and end of the list. The input starts with '9 Pitches( ...' which is totally unwanted.

**Comment by brendanheywood** [comment]
I think this is connected to lots of issues but which are technically unrelated. For instance if you have an easy first sport pitch with a an anchor, but the rest is trad, would you expect this to be show up in a facet searching for sports routes? Would you expect this to show up in searches if you filtered by grade and the whole route was much harder? I would say a typical climber would say yes. Even things like looking at a topo which has each route color coded by grade band, it would appear that the first route is red and hard instead of orange or green.

**Comment by lordyavin** [comment]
I'm sorry, but I have to state my opinion on the current rendering. I have the feeling that route lists are more confusing now than before rendering the grade badges per pitch.
![grafik](https://user-images.githubusercontent.com/1528540/36979949-3e1616de-2089-11e8-9789-28b47530f85b.png)
I have no clear idea how to solve this to get clear insights with as much info as possible but may be the alignment of the route/pitch details could be overdone (two alternative proposals in route 2 and 3):
![grafik](https://user-images.githubusercontent.com/1528540/36980875-e157a52c-208b-11e8-9c65-3a743e20b10a.png)
Looking at the route list tables in general I would like to have more things aligned in columns to improve readablility and to help the eye to focus on the information that is of interest. Currently the Route names are not left aligend because of varying star ratings. First step could be to reserve space for all 3 stars and align names accordingly.
![grafik](https://user-images.githubusercontent.com/1528540/36981288-0d6c1cfa-208d-11e8-90d1-64c92b606bb5.png)

**Comment by rouletout** [comment]
+1

**Comment by brendanheywood** [comment]
There are multiple issues tangled together here. The pitches is one, and the stars & title alignment is another.

Neither is trivial as there are lots of use cases to consider holistically, and the best solution for some makes others worse off. For now I've tweaked the text margins to they line up a little better:

![image](https://user-images.githubusercontent.com/187449/37012389-77ba93be-2148-11e8-9ff5-cd3d68d62f4e.png)

![image](https://user-images.githubusercontent.com/187449/37012439-b8267026-2148-11e8-94b7-f351c715710f.png)

I think the colored grades for pitches it probably a bit much, so I think I'll tone that back a little. The multi column approach clearly doesn't work well for routes with only 2-4 pitches but does work well for long routes:

![image](https://user-images.githubusercontent.com/187449/37012675-f9aad6bc-2149-11e8-9e5d-6233c7d5f65d.png)

eg I find this much more easy to scan than when the pitches are left to right and wrap:

![image](https://user-images.githubusercontent.com/187449/37012749-520ac024-214a-11e8-9084-7e69c8e3c1df.png)


Some more ideas: (not done)

1) Make the grades 'shrink wrapped'. I suspect part of the problem is just the extra grades are visually too heavy, so perhaps we could either tone back the grade colors or make them smaller:

![image](https://user-images.githubusercontent.com/187449/37013221-f2ff386e-214c-11e8-8919-f4d6ffa7e080.png)

2) If there is a small number of pitches then we could swap from the columns to inline text:

![image](https://user-images.githubusercontent.com/187449/37013312-540d812e-214d-11e8-94c7-4dde59813f2d.png)

So who likes 1) and or 2) ?

**Comment by scd** [comment]
I think yes to both shrink wrap and inline text.

**Comment by lordyavin** [comment]
I vote for smaller badges, tone back colors and inlining if the number of pitches fit into one line. If the number of pitches exceed the space for a line then I prefer the multi-column appraoch and agree with @brendanheywood that this is better to scan. But could this be confusing if we switch the ordering from left-right to top-down, left-right?

**Comment by brendanheywood** [comment]
Ok so I've done this, it swaps between inline vs columns when there is 6 or more pitches.

Some test cases:

9 pitches, US grades, no heights (columns)
https://brendan.thecrag.com/climbing/canada/bugaboos/area/11915977#n12739831

3 pitches US, no heights (inline)
https://brendan.thecrag.com/climbing/mexico/el-potrero-chico/area/11932111#n169582590

13 pitches, with heights, (columns)
https://brendan.thecrag.com/climbing/australia/ebor-gorge/area/12094657#n13332313

The main test case that I think still looks a bit funny is when there is a large number of pitches so it shows in column mode, but there are no heights, and you are in a 'lite' grade system like AU grades and usually really easy single digit grades. I considered detecting the lack of heights and making it thinner columns but then this looks worse when there are multiple routes like this adjacent so I think we just live with this one:

https://brendan.thecrag.com/climbing/austria/route/691654188
![image](https://user-images.githubusercontent.com/187449/37088230-c19e9a08-2250-11e8-8533-aaab4d7885b3.png)

Also I've added pitches to the routes facet search: https://github.com/theCrag/website/issues/3103
![image](https://user-images.githubusercontent.com/187449/37087886-b1d9d2fa-224f-11e8-8ee1-328a60c9192f.png)

I've also run into this issue while testing, which I think we need to fix as part of this broader topic: https://github.com/theCrag/website/issues/3053

**Comment by lordyavin** [comment]
Is there any way to align the size of batches to the biggest one? Currently the badges size depends on their text content. For UIAA grades this can range from one up to 7 characters (e.g. "3", "10+/11-"). It looks like the space is available. I think it should quite easy to determine the biggest badge in a column or the whole table and to align the rest.
