### ISSUE TITLE
Crag history display wrong node in area column.

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3038]
**What happened?**
I clicked on the button in the history description of [a crag](https://www.thecrag.com/climbing/germany/sauerland/area/859741506) to display the [list of historic ascents](https://www.thecrag.com/climbing/germany/sauerland/area/859741506/routes/?sortby=when-history,asc). The column area display the [parent](https://www.thecrag.com/climbing/germany/sauerland/area/424556391) of the selected crag, not the crag itself. This is somehow irritating and maybe wrong.

**What you expected:**
* [ ] The column "area" display the selected crag and its descendants only.

**Comment by brendanheywood** [comment]
I don't think this has anything to do with the history page, I think this is just another manifestation of the TLC algorithm, and the idea of the TLC vs the BLC.

See https://github.com/theCrag/website/issues/2097

Or perhaps instead this node should be a region instead of an area, so the TLC is just Hillenberg

https://www.thecrag.com/climbing/germany/sauerland/area/424556391

**Comment by lordyavin** [comment]
I already changed from crag to area and thought that would fix the issue. I chose area instead of region because "Generally these pages are controlled by site management...".

I still don't understand when to use region and when area. The distinction isn't clear to me. Maybe we lack some more fine grained node types. Today I thought about if the following node (sub) types would make sense:

**landscapes**
* valley
* mountain range

**political regions**
* municipality
* country
* state

But back to the original issue. Is the TLC algorithm explained to the user? Since I'm lacking the knowledge about it's behaviour I don't see how less involved users should know and understand it.

**Comment by brendanheywood** [comment]
The simplest way to explain it, is that whatever you consider 'the crag', then the level above it should be a region. So if 'Hillenberg' is what people would say they are going climbing at, then 'Arnsberger Wald' should be a region. I have just swapped this, but now the crag column is showing as 'unknown'

@scd can you take a quick look at this? I suspect it might be a stats or caching thing and might sort itself after a while, I thought we'd seen this before and it had been fixed. The isTLC flag isn't coming out in the template data for whatever reason:

https://www.thecrag.com/climbing/germany/sauerland/area/859741506/routes/?sortby=when-history,asc

Re the more refined list of node types, yes there is some value here and other db's have a finer list like that. We have considered this, but we still need to sort out the TLC logic properly before we consider adding more node types and muddying the waters more.

**Comment by lordyavin** [comment]
Still unknown area listed. May be this isn't a caching problem.

**Comment by scd** [comment]
Caches of node information is up to around a week.

**Comment by lordyavin** [comment]
One week. That's long. Could you explain the caching strategy?

**Comment by scd** [comment]
There are many different layers of caching. Caching is currently a necessary evil for performance reasons. We are trying to get rid of the caches in as many places as we can, however this is long term infrastructure work.

It was the node cache, which caches all information that the templates need quick access to for areas and routes. This should be reset on all updates but there are some updates where it does not happen for some reason. The cache is long lasting (a week or longer) with a random expire strategy so that not all nodes expire at the same time. 

I have reset the cache for all nodes in the area.

**Comment by lordyavin** [comment]
It works now as expected after changing the node type(s) and waiting for the cache to update. So what to do with this issue? Is it "not an issue" or fixed?

**Comment by scd** [comment]
It is still an issue but will not be fixed for a long time.

**Comment by brendanheywood** [comment]
Another data point, I swapped gara to a region, under it is 'Upper Gara' which is the real crag. Everything has been busted for the last day in the same way:

https://www.thecrag.com/climbing/australia/gara-gorge/routes/?sortby=when-history,asc

https://www.thecrag.com/climbing/australia/gara-gorge/ascents

![image](https://user-images.githubusercontent.com/187449/41567853-e4631a72-73a5-11e8-93fd-e4eda8d100f6.png)

I still don't understand is why this is busted, if the cache is stale I would expect the TLC to just be wrong not missing.

**Comment by brendanheywood** [comment]
Ok I've sorted the inconsistent caches, this is now correctly (?) showing the stale cached version. There is still the cache expirey issue but at least now it's showing something until the cache expires. I've hotfixed this
