### ISSUE TITLE
Multi Pitch logging does not show grades per pitch

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3040]
**What happened?**

https://www.thecrag.com/climbing/mexico/el-potrero-chico/route/11934061

looks like this on logging per pitch:

<img width="1125" alt="screen shot 2018-02-02 at 15 43 26" src="https://user-images.githubusercontent.com/19162952/35758678-d2a5dc2e-083a-11e8-9621-41b417ddfe00.png">

**What you expected:**
All grades shown for every pitch

**Comment by scd** [comment]
Fixed in simons dev

![screenshot from 2018-02-26 17-18-17](https://user-images.githubusercontent.com/373058/36655814-157057dc-1b19-11e8-8901-f32f3ca76cd5.png)

**Comment by scd** [comment]
It is a drop down because the main grade field is a drop down. Unfortunately ascents do not have the same flexibility as route grades. There is a piece of work required to change the data structure for ascents so that they can accept grades of the same complexity as routes. I don't want to go to text until I can support it properly in the back end data structure.
