### ISSUE TITLE
Don't show context and system prefix for grades in correct system but incorrect context eg {US} FR:6c+

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3046]
**What happened?**
I changed the default grading context in Russia https://www.thecrag.com/climbing/russia from US to FR
some weeks ago. I also reset the cache today again.

https://www.thecrag.com/climbing/russia/krasnodar/route/1297962489

If a new route is added the default grading system is still US.

**What you expected:**

Default grading context when adding a new route should be now FR.

* [ ] A route in a node which has a context of say FR, but which has a route whose context is US, but the actual grade system is French (and the french system is ok in the US context) then do not show the context and system prefix: "{US} FR:6c+", just show "6c+"

**Comment by lordyavin** [comment]
Cold war reloaded 😉

**Comment by scd** [comment]
Here is an example where the context seems to be misaligned.

https://www.thecrag.com/climbing/russia/krasnodar/area/1297961313

**Comment by scd** [comment]
The add route seems to get the default context from the country and ignores the area settings. Hmmm, I thought we had fixed this, so I have to investigate further. Note to self CreateClimb.pm

Once the country context is changed some server caching means we have to restart apache in order for it to take effect.

Anyway you can add routes with FR context now, even though the core issue is not resolved.

**Comment by brendanheywood** [comment]
New routes here are correctly in the FR context. The remaining issue is any routes that were previously made under the US context.

So I think this issue itself is mostly a display issue, ie if a French system grade inside a US context, is shown in side a region which is a French context, then because the French system is fine in both the FR and US context then it should not show the "{US} FR:" prefix. I thought this was logged already but couldn't find it so I'll rename this issue

**Comment by brendanheywood** [comment]
+1 again from https://www.thecrag.com/discussion/2005091973/reconsider-standard-grading-system-for-belgium#m2005154193

It's also hard to gauge the scope of the problem without https://github.com/theCrag/website/issues/2567

**Comment by rouletout** [comment]
@nicHoch I still see this sometimes - anything we can do about it?

**Comment by georg-d** [comment]
Could anyone please look shortly whether this issue causes the histogram in https://www.thecrag.com/climbing/italy/monte-campo-dei-fiori  to be in YDS while grade context is FR and all routes are in FR? I value this as unexpected/bug because of [help description](https://www.thecrag.com/en/article/gradesonthecrag#article.gradesonthecrag.header.grade-contexts). It may also have other causes, e.g. all routes have _unknown_ climbing style or something else. It works fine for all other crags in the area I looked at.
![grafik](https://user-images.githubusercontent.com/45993293/164265003-278f91a0-85f8-42cb-9272-ea9873a573a6.png)

**Comment by scd** [comment]
All routes being unknown is most likely the cause. The system uses the underlying gear style to work out the grading system to display with. I am pretty sure we don't have a use case for dealing with unknown, other than defaulting to YDS.

**Comment by georg-d** [comment]
Thanks @scd, because that symptom most likely has other causes than this issue is about AND because the mentioned crag is likely not the only with the symptom AND a grade band chart in YDS is mostly useless in central Europe, I created dedicated issue https://github.com/theCrag/website/issues/4051
