### ISSUE TITLE
Ascent facet navigation broken

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3050]
**What happened?**

When visiting the facet view for ascents via a node, the url is, for example,

https://www.thecrag.com/ascents/at/420460980

But from there, you cannot navigate away to another node, because the URLs generated look like this (when trying to move to the higher node "Germany" in my example above):

https://www.thecrag.com/climbing/germany/ascents/at/420460980

So the /at/$node is appended to the original URL.

**What you expected:**

The "filter by ascent" links in the nodes should point to e.g.

https://www.thecrag.com/climbing/germany/area/420460980/ascents
instead of
https://www.thecrag.com/ascents/at/420460980

**Comment by scd** [comment]
Click on the Index menu item. 

This is intentional, but I am not so sure it is obvious or desirable that once you are in facet mode you stay in facet mode while navigating.

**Comment by quaestor** [comment]
That's not what I'm saying. Navigation *should* stay in facet mode, but I should be able to navigate in the first place, which isn't happening.

**Comment by scd** [comment]
I am definitely confused if my comment is not what you meant. It might be a little bit irritating but could you please upload a screen shot with a circle around one of the links you mean.

**Comment by quaestor** [comment]
Here's a video: https://youtu.be/yxqb8IwBhhQ

**Comment by brendanheywood** [comment]
I think this boils down to the /at/{nodeid} url structure should be completely deprecated in favor of the slug url prefix version. We kinda made this decision implicitly but not fully carried it through. The urls being generated in the side menu contain a mix of the old and new url structure which clash and one takes precedence. The second quasi-bug is that the original links from the index page to the facet should use the new slug version instead of the at version.

ie the original link should not be 

https://www.thecrag.com/ascents/at/420460980

but instead be:

https://www.thecrag.com/climbing/germany/area/420460980/ascents

**Comment by quaestor** [comment]
Yes, that's exactly what I wrote in my original post. ;-)

**Comment by scd** [comment]
I get it now, you are actually navigating, but the `/at/420460980` is staying tacked onto the url which is confusing the system. 

There are two issues here. We should be eliminating the `/ascents/at/420460980` form of facet reference in the first place and if it does occur then we should not include the `/at/420460980` in nav links.

Actually it is more significant than that because the filters and swapping facet types is also broken when you use that form of facet url.

@brendanheywood this is actually a fairly significant use case because it is triggered from index page nav. The url is not generated in the nodeListView template but rather from javascript in common.js using the node id. 

I think the fix here maybe to detect the style of url and update the canonical to the correct form.

**Comment by brendanheywood** [comment]
@scd there is two completely unrelated bugs. The old url style while we should deprecate it still needs to be supported. 

So going here should continue to work, but the links on this page are broken which is a backend issue. This is the more important bug.

https://www.thecrag.com/ascents/at/420460980

However there should ideally not be any links to this page, which is the frontend js issue. But if the above is fixed then one won't strictly matter. But I'd still like to fix it mostly for analytics reasons so the urls are consistent. The link could be done server side instead of client side, I think I did it in js that way partially to save payload and partially because having all those tiny links when on mobile is a pain. I'm not too fussed which way we go, but sticking with frontend is easy: I'd suggest we add an extra class to the a tag containing the url base to make it easy to lookup dynamically, ie this:

```
<a href="/climbing/germany/frankenjura">
```
becomes:
```
<a class="baseurl" href="/climbing/germany/frankenjura">
```
and then in js we grab that and tack on the /ascents suffix. I can do this if you want after you've fixed the first bug

**Comment by scd** [comment]
Please review my fix for the ascents facet which I believe is the least work and the right way to do things here. When we see the old style url `/ascents/at/` I map the canonical to `/climbing/germany/area/420460980/ascents`. All functions then seem to work properly. 

This is hotfixed, so you can look at the canonical on this page for example:

https://www.thecrag.com/ascents/at/420460980

I think this is the right way to go, and is only a couple of lines to fix, but needs a fix for each facet.

If you agree I will roll out the fix for all facets.

**Comment by brendanheywood** [comment]
Looks good to me, fixed in the left menu and the crumb trail

**Comment by brendanheywood** [comment]
Ah found one bug:

go here:

https://www.thecrag.com/ascents/at/420460980/with-ascent-grade/AU:1:39/?sortby=when,desc

It's canonical is now:

https://www.thecrag.com/climbing/germany/area/420460980/ascents?sortby=when,desc

when it should be

https://www.thecrag.com/climbing/germany/area/420460980/ascents/with-ascent-grade/AU:1:39/?sortby=when,desc

**Comment by brendanheywood** [comment]
And that bug above affects everything including the left side nav links etc

**Comment by scd** [comment]
Whoops I refered to $3 instead of $2 in a regex, so I was replacing with null rather than the trailing string.

Please check again

**Comment by brendanheywood** [comment]
Yup looks good

**Comment by scd** [comment]
@quaestor this was a good pickup, thankyou. 

It should be resolved now on prod.

**Comment by quaestor** [comment]
Great, thanks for the fix!
