### ISSUE TITLE
gym labels print: same font and background color

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3070]
**What happened?**
Brought up as an issue from our test gym partner in Germany:

https://www.thecrag.com/climbing/kletterwerk/gym-wall-cards

Finding a font color for the label print in gyms that will work on all route colors is hard. 
Main candidates for the font color are white and black. But having white or black routes colors will result in invisible names on the label.

<img width="228" alt="2018-02-23 12_29_49-wall cards _ thecrag" src="https://user-images.githubusercontent.com/2226714/36592308-723003b8-1895-11e8-8cac-d4a8486a8da3.png">

**What you expected:**

* [ ] readable names on each background

maybe a fallback color if background is equal or very similar to font color. but that sounds hard for css.

**Comment by brendanheywood** [comment]
Ok this is fixed in dev. At the moment the logic is brutally simple which is if the color is yellow or white then set the text color to black which is consistent with the listview grades. At some point we should replace this with logic based of the hue of the color.

Note that in each gyms css it will be hard coded to white which we need to change to use the css variable I am populating, ie this:

    color: var(--item-color-bw);
    background: var(--item-color);

There is a working example here:

https://brendan.thecrag.com/climbing/australia/queensland/rockit-climbing-gym/area/421397004/gym-wall-cards

**Comment by brendanheywood** [comment]
I have also hot fixed this and also configured that gym to use the variable:

![image](https://user-images.githubusercontent.com/187449/36626602-a4063ffc-1989-11e8-9a1f-f13ba3099023.png)
