### ISSUE TITLE
Improve new grade and heights display for multi pitch routes

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3071]
**What happened?**

![image](https://user-images.githubusercontent.com/187449/36625558-f1b82260-1975-11e8-9f91-bf135a68f3b0.png)

The first time I saw this I thought it was a cut and paste error, it's not clear what it is or what heights and grades go with what pitch. It's also worse and redundant when there is also the markdown pitch breakdown as well. 

**What you expected:**

* [x] A new line to break it from the markdown content
* [x] for the summary to be inside the column breaks
* [x] incude the pitch number
* [x] format it nicely

**Comment by brendanheywood** [comment]
@scd can you please give me a grade band for each pitch grade?

mockup of what I have in mind:

![image](https://user-images.githubusercontent.com/187449/36625721-3e76103c-1979-11e8-970e-dac508de03b8.png)

**Comment by brendanheywood** [comment]
Ok I have refactored this to use the same pitch template as the ascents / stream pages and cleaned up the pitches template to everything is aligned more nicely

Test pages:
https://brendan.thecrag.com/climbing/australia/ebor-gorge/area/12094657
https://brendan.thecrag.com/climbing/australia/ebor-gorge/route/13332313
https://brendan.thecrag.com/event/616575097
https://brendan.thecrag.com/ascent/616574944
https://brendan.thecrag.com/climbing/australia/ebor-gorge/ascents/with-route-gear-style/trad/is/multipitch/

A route with pitches:
![image](https://user-images.githubusercontent.com/187449/36626323-df73d5cc-1984-11e8-9568-ff9acb8b7d03.png)

An ascent with pitches:
![image](https://user-images.githubusercontent.com/187449/36626305-8fb796fe-1984-11e8-91dc-55f4fefe88d3.png)

@scd this is pushed, the only thing left is adding the gradeband to the route atom pitches template data and then you should see the pitch grades light up. There may possibly also be a different between how ->{height} vs ->{heightText} so ideally please make template data consistent between routes and ascents too.

**Comment by brendanheywood** [comment]
@scd actually can you go this slightly differently, can you please make a new gradeAtom something vaguely shaped like this:

```
"pitch": [
{
  "grade": {
    "raw": "13",
    "label": "13",
    "internalLowGrade": 120,
    "internalMidGrade": 170,
    "internalHighGrade": 220,
    "gradeBand": 1,
    "system": "AU",
  },
  "height": "10m"
},
{
  "height": "30m"
  "grade": ...
},
```

Getting an atom in place for this sets us up for a few things down the track like universal grade conversions

**Comment by scd** [comment]
There is a technical discussion we should have about the mid grade point. Mid grade point is already part of the grade framework so it should be fairly easy, however since CPR work I have concluded that it may not be what we want. 

Any CPR calculation on grade ranges maps back to a CPR equivalent internal grade which I think is just a little more than the mid point. What is good about this internal grade is that it represents the difficulty of the route as best we know it, so we should probably be doing universal conversions based on this number not mid point.

I am also happy to provide four internal grades like such:

    "internalLowGrade": 120,
    "internalMidGrade": 170,
    "internalCPRGrade": 174,  # just a guess for discussion purposes only
    "internalHighGrade": 220,

**Comment by brendanheywood** [comment]
+1 Sounds perfect

**Comment by scd** [comment]
So this is what pitch grade now looks like:

```
                         'grade' => {
                                      'band' => 0,
                                      'internalGrade' => 97,
                                      'internalHighGrade' => 100,
                                      'internalLowGrade' => 93,
                                      'label' => '12',
                                      'raw' => '12',
                                      'system' => 'AU'
                                    },
                         'height' => '20m'
```

Note that `internalGrade` is the CPR equivalent grade for the given grade range. It is rounded to the nearest integer. @brendanheywood please confirm that calling it plain old `internalGrade` makes sense in terms of other template data.

Also please confirm that we do not need MidGrade. I don't see the point of this grade as the grade we are really concerned with is the one that cpr calculates.

Note that I have not updated this in any of the templates, but I have pushed to repo. Note also that I had to increment the cache node version number so that the first time you get nodes again it may be a bit slow because the node cache has been invalidated.

**Comment by scd** [comment]
`system` is the actual grade `system` not the context. Context cannot change between pitches, but systems can. 

For a universal system we probably need both, but for pitches for now we probably need neither.

BTW I have decided to use this as the first step toward slash grades so we now have something like:

```
grade' => {
                                      'band' => 2,
                                      'internalGrade' => 201,
                                      'internalHighGrade' => 213,
                                      'internalLowGrade' => 181,
                                      'label' => '5.10a/b',
                                      'raw' => '5.10a to 5.10b',
                                      'system' => 'YDS'
                                    },
```

I can do this because we have now agreed to use the CPR measure of the grade range. For two adjacent grades of the same grade width the slash grade and grade range are equivalent according to CPR. This means it does not matter whether we write '5.10b to 5.10c' or 5.10b/c as far as cpr (grade difficulty) is concerned. If the grade widths are different then there could be a difference between grade range and slash grade, but it depends on interpretation and it will only be minor. This little insight means we can simplify without worrying about grade ranges or slash grades as we can treat them the same for adjacent grades.

I have written a little helper which simplifies 5.10a/5.10b to 5.10a/b. It will also simplify 10/11 to 10/1, so we may need to monitor this to see if the results are understandable.

**Comment by brendanheywood** [comment]
> 5.10a/5.10b to 5.10a/b

perfect

> 10/11 to 10/1

I don't get this one?

Are you writing business rules specific to each grade system or trying to come up with something generic for any two strings?

**Comment by scd** [comment]
Generic based on repeated text. What I am saying is that this may not be
sufficient. Ideally I want to keep it generic so I think we need some test
cases in different grading systems.

**Comment by brendanheywood** [comment]
Right, so I think we'll need something a little more nuanced. I've scanned all the grade systems and I think this will do the job:

1) break up the text via regex anywhere there is a word boundary \b, or the transition from numbers to letters, or vica versa, or upper case to lower case, or vice versa

2) If one array is longer than the other, then merge the right two most elements of the longer array then repeat until they are the same length

3) Find the common prefix and merge them

4) Join the remainder with a /

Examples:

```
5.10a to 5.10b
Step 1: ['5', '.', '10', 'a']    ['5', '.', '10', 'b']
Step 2: n/a
Step 3: ['5.10', 'a', 'b']
Step 4: 5.10a/b

5.10 to 5.11a
Step 1: ['5', '.', '10']    ['5', '.', '11', 'a']
Step 2: ['5', '.', '10']    ['5', '.', '11a']
Step 3: ['5.', '10', '11a']
Step 4: 5.10-11a

5.10c to 5.11a
Step 1: ['5', '.', '10', 'c']   ['5', '.', '11', 'a']
Step 2: n / a
Step 3: ['5.', '10c', '11a']
Step 4: 5.10c/11a

7a to 7a+
Step 1: ['7', 'a']   ['7', 'a', '+']
Step 2: ['7', 'a']   ['7', 'a+']
Step 3: ['7', 'a', 'a+']
Step 4: 7a/a+

7a+ to 7b
Step 1: ['7', 'a', '+']   ['7', 'b']
Step 2: ['7', 'a+']       ['7', 'b']
Step 3: ['7', 'a+', 'b']
Step 4: 7a+/b

V8 to V10
Step 1: ['V', '8']   ['V', '10']
Step 2: n / a
Step 3: ['V', '8', '10']
Step 4: V8-10

VIIIb to VIIIc
Step 1: ['VIII', 'b']   ['VIII', 'c']
Step 2: n / a
Step 3: ['VIII', 'b', 'c']
Step 4: VIIIb/c


```

**Comment by brendanheywood** [comment]
@scd I think your grade bands have an off by one error are are 0-4 instead of 1-5

**Comment by scd** [comment]
doh, fixed band levels.

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
scd@thecrag.com
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Instagram <https://www.instagram.com/thecrag_worldwide/>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by brendanheywood** [comment]
@scd I have finished my side and also made the pitches template gracefully handle either text grade or atom grade so this original issue is now finished. Do you want to keep this open or close it and split off the slash grade task?

**Comment by scd** [comment]
Irritatingly word boundary would be perfect if 10a was split, but this is treated as one word. I made an small enhancement to clump digits, alpa and others together and it seems to work good. 

I also had to treat the -+ modifiers as the same word as either the previous digits or alphas so we get 6a/a+ or 5.10/10+

Actually I am wondering if 6a/+ may be preferred over 6a/a+   (this is beyond my capability to work out which is preferred, but we are doing the later based on your spec above).

We can close this now
