### ISSUE TITLE
Don't animate webcovers in stream

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3074]
**What happened?**
Since a while webcovers are animated with an automatic zoom in. This leads to quite a significant load of the CPU.

**What you expected:**
* [ ] Disable animation for streams and other views where the webcover is displayed as a thumbnail.
* [ ] Build in measurements and checks whether the user's computer is capable of displaying the animation smoothly. If the JS engine and/or the computers performance is to low then disable animation.

**Comment by brendanheywood** [comment]
Yeah this was one reason why I was hesitant to roll this out. There might be something wrong with the css because this should all be offloaded to the gpu but I suspect older browsers will always choke trying to emulate this. I think it's best to remove it completely, the detection of cpu is a pita and not worth the effort.

hotfixed

**Comment by lordyavin** [comment]
Wow, that was fast. Thanks.
