### ISSUE TITLE
sandpit/translate api post error: Internal Server Error

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3090]
Tried to translate the text article.gympermissions.body.markdown and got the gollowing error when saving.

![grafik](https://user-images.githubusercontent.com/1528540/36869411-009047d4-1d9c-11e8-91c0-c980c6658e77.png)

Is the translator broken? Second time I got that error.

**Comment by scd** [comment]
Hi Kai,

Could you please try again. Something was not functioning correctly but I
don't know what exactly the problem was. Do you have a copy of the German
text. If not your update was logged in a log file so I can give it to you.



--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
scd@thecrag.com
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Instagram <https://www.instagram.com/thecrag_worldwide/>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by lordyavin** [comment]
No I didn't save the text before submitting.

**Comment by scd** [comment]
I have loaded the text that was logged into the translation key. Hopefully not too much is lost. Please check.

**Comment by lordyavin** [comment]
Works again.

**Comment by lordyavin** [comment]
I got the error again. Could it be that there is some sort of timeout again? I reloaded the translation interface and saving worked.
