### ISSUE TITLE
'alt grade' dropdown in ascent form is confusing and ambiguous

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3097]
**What happened?**

Confusion over grade vs alt grade in ascent log process:

![image](https://user-images.githubusercontent.com/187449/36945213-e304b848-1ffe-11e8-86a1-4c06f1e08e67.png)

**What you expected:**

Short term:
* [ ] tooltips explaining what it is

Long term
* [ ] replace both dropdowns with an empty free text field with placeholder text (in both ascent and pitches fields)

**Comment by lordyavin** [comment]
+1

**Comment by birgander2** [comment]
The current system of personal / community registered grades is a bit confusing. The registered grade is fine, but what I would expect here is that I can log a kind of personal opinion of the grade, from which ideally some statistics are shown. To "edit" a route in order to set a personal grade is strange, this should definetly be possible during ticking.

**Comment by scd** [comment]
Less confusing in the new tick flow, however it is still a problem but less of a problem. I am closing
