### ISSUE TITLE
Bugs with slash grades combined with pitch grades

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3115]
**What happened?**

"18/19"  -> "18/19" correct, shows the slash grade

"5,10,15" -> "15" correctly shows the hardest grade

"18/19,5" -> "5-19" incorrect, combines all grades into slash grade.

"7a,8b,7b" -> "8b" correct
"7a,8b,7b/7c -> "7a - 8b" incorrect

**What you expected:**

Each pitch grade should be parsed individually and then the hardest of the grades extracted as the route grade, not parsing all the pitch grades together

* [ ] 18/19,5 -> 18/19
* [ ] 7a,8a,8b/8c -> 8b/c

Perhaps unrelated there also seems to be some display issues with slash / vs dash  -, ie

* [ ] 5.12a - 5.12b -> 5.12a/b (correct)
* [ ] 5.12a - 5.13b   -> 5.12a - 13b incorrect, should be 5.12a/13b
* [ ] 9a/9b -> 9a - b, should instead be 9a/b

I was under the impression that from now on / and - are treated exactly the same, and so how they are displayed is more or less a purely aesthetic decision? In which case I prefer / in all cases as it's smaller by 2 characters widths.

**Comment by scd** [comment]
There seem to be some parsing bugs, which is a bit worrying. 

The display rules use / (slash) for adjacent grades and - (dash) for non-adjacent grades. I have never seen slash for non adjacent grades in guidebooks. Most people assign slash grades because they think the route difficulty is exactly in the middle of two adjacent grades.  Aesthetically I like the distinction even though it has no effect on the difficulty level.

**Comment by scd** [comment]
I have fixed the multi-pitch slash grade issue on Simon dev. See screenshot for a working example:

![screenshot from 2018-03-26 15-52-44](https://user-images.githubusercontent.com/373058/37887506-df3cec56-310d-11e8-9f66-e2b193e9e86b.png)

I think the slash versus range is fine.

Closing
