### ISSUE TITLE
More fine tick type polish (yoyo, one-hang, all-free / AF, repeat)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3136]
**What happened?**

Various bits of fine tuning of the new tick types

* [ ] more inline help when ticking (need custom tick selector)
* [ ] dynamic 'tick chooser' in the help article to help people learn what each means
* [ ] all free with rest, refine description, refine icon, so it's less of a 'tick'. Look into the feasibility of only allowing it in certain locations. See raw definition here in german: https://de.wikipedia.org/wiki/Begehungsstil#a._f.

Possible new tick types
* [ ] lead with rest / fall (aka hang dog - would we replace or have two the same?)
* [ ] yoyo (icon ? https://github.com/theCrag/website/issues/1217#issuecomment-302103328)
* [ ] one hang
* [ ] Also need DWS flash, onsight etc

* [ ] Move ticks around between groups, maybe have an 'advanced' group at the bottom for the weird edge cases

**Comment by nicHoch** [comment]
"All free with rest" is a absolute valid tick in the areas where used. Even the actual route grade includes the allowance of resting in the (very sparse) bolts - otherwise the is an additional red point grade.

**Comment by johnpitcairn** [comment]
I think availability should definitely be region-dependent. There is some creep starting to show - I've seen it used on Arapiles ascents and some here in NZ, where it is unheard-of. If you fell or rested and continued without lowering then it's a hangdog.

**Comment by johnpitcairn** [comment]
How many hangs/sits/falls, etc, are surely something that can be taken care of in the ascent notes field for those who care? If you are yo-yoing, isn't that a separate shot?

**Comment by johnpitcairn** [comment]
Since the other long thread about tick handling is closed:

Seen purely as ascent attributes when logging, if I were architecting this, I would use TWO selectable ascent attributes, not one attribute that attempts to combine both. Conflating these into one set of options confuses _how the route was climbed_ with _what happened while trying to climb it_, both usefully separate data points:

How did you climb it?
**Ascent style:** Climbed (default?), Soloed, Led, Seconded, Top roped, Top rope soloed, Lead soloed, Aided, Aid soloed, etc

Did you succeed?
**Tick type:** Tick (default?), Onsight, Flash, Redpoint, Pinkpoint, Greenpoint, Dab, Clean(?), All-free, Fall, Rest, Aid(?), Attempt, Retreat, etc

That gives you two shorter and constrained choices to make, rather than a huge confusing list of combinations.

The resulting data is more granular and accurate, easier to manipulate, and adding a new tick type or ascent type does not require adding all the possible ways they can be combined.

Choices in each of these could still be limited according to the type of route (Boulder, Sport, Trad, DWS etc), or the region (for things like All-free), or even (rather more sophisticated and harder) according to the choice made in the other list - ie if you soloed a route you wouldn't have "rest" or "pinkpoint" available.

**Comment by brendanheywood** [comment]
Cool, so this is not so much about the actual tick types themselves but more purely the UI for how to conceptually present and choose them. I've copied this to #3158 which is probably more what you were after

**Comment by scd** [comment]
From support email: User wants to record a Flash of a Pink Point.

**Comment by johnpitcairn** [comment]
Ha. So the gear style is a separate data point? Placed on lead or pre-placed.

Might be simpler to add "pinkpoint flash"? Redpoint flash is a "flash".

**Comment by scd** [comment]
Don't know how we solve this yet. Just collecting requirements. It always seems to get deeper and more complex then once first thought :)

**Comment by johnpitcairn** [comment]
If we want to capture the data, categorize ascents, show relevant icons, and assemble a natural-language statement, and don't want 100 combinations in a single tick-type field, we need more than one field. Something like:

Ascent type:
climbed (default?), soloed, led, seconded, greenpointed, redpointed, pinkpointed, top roped, top rope soloed, lead soloed, attempted

Ascent style:
A: onsight, flash
B: all-free, with dab, with aid, with rests, with falls, with retreat

In some places we are dealing with natural language output. So the result becomes (crudely) something like:
Climber XYZ [ascent-style-A] [ascent-type] [route name] [ascent-style-B]

Each ascent style and tick type would have additional non-user-visible metadata to control output, including an input (form) term and output (display) term, a grammar positioning index for output (crudely resulting in A and B above but per language), and a modifier map that could hide or change the input or output term depending on the corresponding region/route/ascent-/tick-type.

Complicated? Sure. But 2 fields will mean fewer options that the user has to deal with, and allow more natural language assembly and flexibility than 1 field with a lot of (but never enough) predefined combinations.

**Comment by brendanheywood** [comment]
> Can we please have more ascent types for DWS ticks? Just logging as a dws ascent is not enough. Also need DWS flash, onsight etc Thanks!

https://www.thecrag.com/discussion/2893563414/dws-ascent-types

**Comment by Luen** [comment]
Likewise roped soloing

> > Can we please have more ascent types for DWS ticks? Just logging as a dws ascent is not enough. Also need DWS flash, onsight etc Thanks!
> 
> https://www.thecrag.com/discussion/2893563414/dws-ascent-types

Likewise roped soloing. Currently you can only do lead roped solo and top rope solo. Nothing about onsighting, flashing, or redpointing. 

I like the idea of splitting it up into to segments (Ascent style and Tick type).

**Comment by rouletout** [comment]
+1 from support (Nicolas):

I sometimes do some rope solo lead and i was wondering :
- why these ascents are not eligible to CPR
- why they do not account as "sport climb" ascents
- why there is just 1 tick type for rope solo lead, without disctinction of Onsight, Red point, Hang dog, etc. I particularly do not understand this last point since you built up this highly granular matrix (which generates endless discussions on the forum about red and pink point ! ah ah !). Even Top rope ascents include details about the ascent type, i thought rope solo lead would deserve some more reward for the performance :)

**Comment by rouletout** [comment]
This is solved with the new ticking interface - closing
