### ISSUE TITLE
Compeitions don't appear in ascents menu if you are anon

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3146]
**What happened?**

![image](https://user-images.githubusercontent.com/187449/38676960-0f26d360-3ea0-11e8-829c-626158d9d522.png)

**What you expected:**

* [ ] comps

**Comment by scd** [comment]
At the moment the competition ony shows for users in Australia because it is an Australian comp.

I am hard coding all this while we work out the rules. I don't think the Easter comp should be shown ubituously for any anon user anywhere in the world. If they had an IP from Australia or they were browsing Australlian nodes then we would want to show it.
