### ISSUE TITLE
Thumbor failure on massive images

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3156]
**What happened?**

This photo is black:

https://image.thecrag.com/485x320/e0/59/e0592c9b4ffba747868ecd4d6aece139566dc57f

But the photo page which renders at a larger size is fine:

https://www.thecrag.com/photo/1769474424

https://image.thecrag.com/1454x960/e0/59/e0592c9b4ffba747868ecd4d6aece139566dc57f

If I try to serve a random variant like 1 pixel bigger:

https://image.thecrag.com/485x321/e0/59/e0592c9b4ffba747868ecd4d6aece139566dc57f

Then I got this:

502 Bad Gateway
nginx/1.13.11

But I assume this is actually nginx timing out, because the image works the second time:

https://image.thecrag.com/485x321/e0/59/e0592c9b4ffba747868ecd4d6aece139566dc57f

**What you expected:**

* [ ] The nginx timeout was really short, probably in the 100ms but I think that could be a bit longer like several seconds.
* [ ] a working pic

**Comment by brendanheywood** [comment]
@Drazhar can you please dump any urls of topos or photos you keep finding into this issue

**Comment by Drazhar** [comment]
This morning I tried to use this photo also as an topo:

https://www.thecrag.com/photo/1769474424

I tried it two times, but because it was just black, I deleted it again after some minutes. But I can upload the image again in the testing area to reproduce the error.

**Comment by scd** [comment]
I have just cleared all the cache so if there are any more black images I want to know about them.

Also I have reduced the number of thumbors from 4 to 2 in case there was some sort of memory issue.

I have done three things, but I am not sure if this is fixed because I got a bad gateway still but when I did a shift reload it disappeared. Since I have not got a bad gateway. I am sure this is not fully fixed.

**Comment by scd** [comment]
nginx does not cache the failures. The cache is coming from thumbor. I am not sure why some bad images were being stored. I need a few more examples of black images to work out how this is happening. I think there are several layers of failure happening here.

**Comment by scd** [comment]
see also #3144 

The image from this example is

https://image.thecrag.com/2314x550/6a/54/6a549117a7119b3c08f18fa0dd6394799bbc5988

**Comment by scd** [comment]
Here is one problem from the logs:

thecrag_thumbor_thumbor.3.wtz17refcv39@theCrag-photos    | 2018-04-23 23:25:58 thumbor:WARNING [PILEngine] create_image failed: Image size (79658108 pixels) exceeds limit of 75000000 pixels, could be decompression bomb DOS attack.

**Comment by scd** [comment]
I have resolved one of the issues (maximum pixel size), but I suspect there are multiple things going on so I am keeping this open as a collector for bad images. If we don't find any in the near future I will close the issue.

**Comment by scd** [comment]
@Drazhar there are multiple failure modes. The 75 megapixel problem was most probably different then your example.

Generally speaking we want the originals and we scale down on the fly. If we add a feature which can take advantage of a larger image then it would be a shame to not have the original.

My suggested workflow is to upload the original and report if does not work. In which case you may want to upload a smaller version because it can take us a while to get around. Don't delete.

**Comment by brendanheywood** [comment]
Long term I want to be able to support stuff like this:

https://www.thebmc.co.uk/zoomtopo/stanage/

see also https://github.com/theCrag/website/issues/2944 and https://github.com/theCrag/website/issues/1701

**Comment by brendanheywood** [comment]
closing for now
