### ISSUE TITLE
Custom tick type selector with inline help when logging ascents

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3158]
**What happened?**

A few people have suggested various ideas to make the selection of the various tick types easier and more intuitive, and to also help aid proper understanding of the various tick types for people unfamiliar with them. This is a general place to collect all the ideas around this. Some high level principals:

* [ ] should prioritize or encourage the most common tick types at the top
* [ ] should allow, but discourage the more esoteric tick types or which are advanced (eg green point etc)
* [ ] should have inline help / descriptions and not just a label
* [ ] should show both the icon and the labels together
* [ ] should gracefully expand or contract so we show different sets for bouldering, dws, indoor gym, etc etc

One idea is to have a widget more like a tree widget with only 2 levels, instead of a split selector. 

* Always at least one open by default, which saves one tap / click
* Can open more than one
* Long hover opens
* Tap opens
* Select closes
* Store in the session which ones you use the most

Internally I'd do this as a select with optgroups (as it is currently) and progressively enhance this.

**Comment by brendanheywood** [comment]
A thought I've been mulling on: a 'matrix' selector, which has a similar breakdown to now but presented as a grid. Top row would be say 'lead' for a sports route and contain the most common 4-5 tick types which are based on you leading. Next row might be say 'top rope'. As you either mouse or touch over then you get a full description of the tick type at the bottom

**Comment by brendanheywood** [comment]
Thought from Christoph Rauch via https://www.thecrag.com/discussion/1771023078/dws-ticktype#m1774598001

This is another instance of a case where I think a system with two "tick type" dropdowns instead of one would make a lot of sense:

first dropdown: [lead, top rope, second, solo, …]
second dropdown: [onsight, flash, redpoint, …]
where the contents of the first dropdown might depend on the type of the route and the contents of the second might depend on the selection made in the first.

This way, the tick type list doesn't explode as it does currently and it doesn't complicate things much for the users.

**Comment by lordyavin** [comment]
+1 to work on that. I like Christophs idea but no idea if the two drop downs are convenient. I agree that the current list is too long and needs some filtering. E.g. Onsight and flash could removed if I already climbed a route.

**Comment by quaestor** [comment]
By the way, UKClimbing is using a system similar to what I described above:

<img width="516" alt="screenshot 2018-09-19 12 41 38" src="https://user-images.githubusercontent.com/54371/45748579-7c3e8600-bc09-11e8-9d86-a926c13405d6.png">
<img width="607" alt="screenshot 2018-09-19 12 41 45" src="https://user-images.githubusercontent.com/54371/45748578-7c3e8600-bc09-11e8-8e2b-339fc0272d38.png">

**Comment by lordyavin** [comment]
Please make the list of tick types context sensitive. Remove all tick types that are impossible. E.g. routes in a gym can not be green pointed.

**Comment by brendanheywood** [comment]
I really like this idea of conceptually splitting via 'intention' vs 'result'. It's more or less the same as other 2 level breakdowns people have suggested but this is the clearest conceptual way of how to go about deciding the 2 levels.

from @johnpitcairn via https://github.com/theCrag/website/issues/3136#issuecomment-432042994

Since the other long thread about tick handling is closed:

Seen purely as ascent attributes when logging, if I were architecting this, I would use TWO selectable ascent attributes, not one attribute that attempts to combine both. Conflating these into one set of options confuses _how the route was climbed_ with _what happened while trying to climb it_, both usefully separate data points:

How did you climb it?
**Ascent style:** Climbed (default?), Soloed, Led, Seconded, Top roped, Top rope soloed, Lead soloed, Aided, Aid soloed, etc

Did you succeed?
**Tick type:** Tick (default?), Onsight, Flash, Redpoint, Pinkpoint, Greenpoint, Dab, Clean(?), All-free, Fall, Rest, Aid(?), Attempt, Retreat, etc

That gives you two shorter and constrained choices to make, rather than a huge confusing list of combinations.

The resulting data is more granular and accurate, easier to manipulate, and adding a new tick type or ascent type does not require adding all the possible ways they can be combined.

Choices in each of these could still be limited according to the type of route (Boulder, Sport, Trad, DWS etc), or the region (for things like All-free), or even (rather more sophisticated and harder) according to the choice made in the other list - ie if you soloed a route you wouldn't have "rest" or "pinkpoint" available.

**Comment by johnpitcairn** [comment]
Cristoph's solution appears functionally identical to mine. All mine adds is (possibly) more user-friendly labelling for the thought process involved - those two questions I would show to the user.

I like the _(optional)_ default available in the UK version rather than my _Climbed_ default. Presumably leaving it as that, the second selection would be hidden or empty, and you would just get a "tick" with no additional detail. Users could still choose to add a "lead tick" by not making a second selection. So people could stay lazy if they want, then regret it a couple of years later ;-)

I think these would want to be two separate fields in the DB, which would entail migrating the current single-option field into 2 fields via an appropriate mapping for each current tick type.

**Comment by quaestor** [comment]
One more example why the two-phase approach is good: I rope soloed a route recently to clean it and practise the moves. However, there is no tick type for "rope solo with rest", so this ascent shows up as my "hardest top rope ascent" on the new profile page. Two dropdowns would get rid of such exceptions, since "with rest" ascents simply wouldn't show up in the profile.

**Comment by johnpitcairn** [comment]
A UI with 2 data points aggregating to internal storage of one data point would raise my eyebrows in an architectural discussion. That's a bunch of ongoing processing to present and store the UI. Past CMS experience suggests that internal storage should be two DB fields, with a one-time tested migration script to map and store current single-field data to the new format, instead of mapping old single-field data to a new 2-field UI on every request. 

There is also a reduced maintenance burden if/when new ascent types and tick types are added if the data is two fields in the UI and in storage. Adding a new ascent or tick type does not require adding N new combinations and associated UI mapping logic.

**Comment by brendanheywood** [comment]
+1 from another thread https://www.thecrag.com/discussion/2559368481

**Comment by lordyavin** [comment]
So how can we (the community) push this issue to get solved?

**Comment by brendanheywood** [comment]
Wanna write a js component for us? This is one of the few things that it would be easy to write standalone and easily wire in. Lets chat offline

**Comment by lordyavin** [comment]
Why not. I'm not that js god, but I can give it a try. Send me details at my thecrag email.

**Comment by scd** [comment]
THis is resolved in the new tick flow release
