### ISSUE TITLE
Bulk editing form does not list the community registered grade

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3170]
**What happened?**

I wanted to remove all my personal grade contributions from routes I didn't climb at all. For that I started the bulk editing a [node](https://www.thecrag.com/climbing/germany/schwaebische-alb/donautal/area/249417609) and used filters to display the grade stuff only. Problem is that the column for the "community registered grade" does not list a grade for a lot of the routes:

![grafik](https://user-images.githubusercontent.com/1528540/39802484-7754adc6-536e-11e8-933b-44448a55cac2.png)

I think I had that problem before, didn't recognize and ended up deleting all the community registered grades.

**What you expected:**

* [ ] Correct handling of already community registered grades
* [ ] Don't let a user add personal grade contributions until he/she logged an successful ascent 
* [ ] Don't add automatically an personal grade contribution if the user registers a new route.

**Comment by lordyavin** [comment]
Could someone confirm this bug, please?

**Comment by scd** [comment]
Yes I can confirm the bug and I have hot fixed this the error with the community grades.

Sorry to take so long, I have been very distracted with some other events and over the last couple of weeks a few things have got lost.

Other suggestions need further discussion, but in principle sound. One issue is that I don't think we want to force people to log ascents in order to participate the collaboration tools.

**Comment by scd** [comment]
I don't propose to do anything further on this issue as the core work is complete. The remaining tasks are discussions on the underlying business rules. It is too confusing having these discussions interleaved in resolving a technical bug.
