### ISSUE TITLE
PDF image resolution is very low

### ISSUE THREAD

**Issue by fpieterse** [theCrag/website#3171]
When downloading the PDF for [hanglip](https://www.thecrag.com/climbing/south-africa/northern-province/area/1751183877), the resolution of the topos is too low and you can't read the label numbers on the routes. This is also true for other topos I have downloaded.

I inspected the PDF to try to identify the scaling of the images and found the following:
* When I export the images from the pdf they come out as .png files, I think this means that they are encoded in the PDF as png. png is not a good format for images and the size of the PDF will be much lower if they are encoded as jpg.
* It looks like the size of the image is set to 90 pixels per inch. I think a decent printer can print at 300 ppi. I view the guides on a cellphone and would be able to zoom into the topos so printer capabilities is not a limitation. Inspecting the first topo (for routes Combi and Innominata) I see the image width in the 2 column pdf is 3.542 inch. The resolution of the largest topo in the online html guide is 1271x640 (px). If the largest photo is used in the PDF, the image resolution will be 360ppi.

Issue #766 mentions that the 1 column guide is bigger than the 2 column guide. This is related to this issue; if the same resolution photos are used but the ppi is adjusted to make the images the correct size then the two guides should have more or less the same size.

**What you expected:**

* [x] use jpg images in PDF guides
* [x] use high resolution images
* [x] adjust the ppi of the images to scale the images in the PDF output

**Comment by brendanheywood** [comment]
My test case:

https://www.thecrag.com/climbing/australia/ebor-gorge

I generated a custom pdf with default settings: 8,871Kb

It took roughly 2 minutes to generate the pdf. Also 1 topo itself: 199k, TTFB2.05 and download of 2.65

Swap to jpeg: topo itself: TTFB unchanged but download is now averaging about .4 secs which is a significant win. The filesize is also around 10% 24k instead of ~200k :smiley: 

Generation time for the PDF didn't seem to change much overall, but the end result PDF was now only 2,327Kb or 25% of the size which is a massive win :nerd_face: 

1 box ticked! I'll play with the res next...

**Comment by brendanheywood** [comment]
See also https://github.com/theCrag/website/issues/3080

**Comment by brendanheywood** [comment]
Ok I've just bumped up the resolution by a factor of 2. That same PDF is now 4,391Kb so still half the size and much more legible. The single column one is bigger at 7,325Kb which is odd to me, they should be the same but I'm ignoring this for now.

There was a side effect of the lines and labels now being smaller, but generally I think this is actually an improvement so I've not worried about this.

**Comment by brendanheywood** [comment]
And this is hot fixed
