### ISSUE TITLE
number formatting is sometimes wrong for profile karma

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3201]
**What happened?**

Example url(s) to reproduce the problem:

https://www.thecrag.com/climber/anderlnought

1126.0k 
![image](https://user-images.githubusercontent.com/187449/41628845-c0411760-7469-11e8-941a-f801c4d1615e.png)

**What you expected:**

* [ ] should be ~400k
* [ ] add unit tests for various numbers and where they drop significant figures
* [ ] add flags to have more or less sig fig, eg 1126.0k vs 1126k vs 1.1m
* [ ] have flag to return raw number and units so this can be passed onto the bigstats component to render properly instead of the units being part of the number text

**Comment by scd** [comment]
@brendanheywood I think anderl's karma is right. Here it is in the json:
```
"totalKarma": "1151190",
```

Why do you think it should be about 400k? If it should be about 400k then there is a deeper problem because it is wrong in the json.

I have found no other evidence that the display is wrong. 

I have created some tests `Translate.pm/formatNumber.t` and it seems ok

I don't think we want significant figures by default if we are converting to k and the number is greater then say 20k. I have just added some logic for this. So Anderl's karma will now read 1151k instead of 1151.2k

We can add the other logic in as needed. We probably want to extend to the million unit.

@brendanheywood I don't propose to do any more for the profile release.

**Comment by brendanheywood** [comment]
I think is probably an inconsistency between the facets or perhaps the area karma stats. I should have added a link for the second place. Let’s kill this for now
