### ISSUE TITLE
Maps: Google Maps switches to 3D-view when zoomed in, loaction shown wrong

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3216]
**What happened?**

https://www.thecrag.com/climbing/united-states/the-black-hills/area/1902929319 shows the location of e.g. Seashell wrong as the default view in Google Maps is 3D.

Ideally also provide screenshots:

**What you expected:**

Correct location display or default to 2D-view
<img width="1046" alt="screen shot 2018-07-23 at 14 33 02" src="https://user-images.githubusercontent.com/19162952/43094805-3bad6f84-8eb4-11e8-8cba-633ccc514c7c.png">

**Comment by brendanheywood** [comment]
I'm not sure what to do here, that 3d view is something you get by default out of the box and I think it's broadly useful where it is available. I don't think I'd want to disable it everywhere. The real issue here is that the google maps tiles themselves are not aligned due to parallax error, over time these things tend to improve.

When we redo the maps in leaflet we may lose the 3d ability anyway

**Comment by brendanheywood** [comment]
It's worth noting it's more or less the same issue as when you locate something in google maps, but then it's wrong in bing maps or in open street map. Or even locating it in google maps and then a year later they update the tiles and everything has shifted, that has happened to me a few times but again generally it gets more accurate over time.

**Comment by brendanheywood** [comment]
Closed as redundant in new maps
