### ISSUE TITLE
Have a concept of an active account or inactive account

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3226]
**What happened?**

This is complementary to the proposed process to archive old empty accounts, but this is kinda the reverse. There are plenty of accounts which are full of data and for which we wouldn't want to archive them (eg FA history, tick quality votes etc) but where it might be useful to show that the account is not active anymore.

See also https://github.com/theCrag/website/issues/1758

**What you expected:**

* [ ] show inactive accounts on profile
* [ ] de-emphasis them in certain auto completes, like forum mentions

**Comment by Mdemaillard** [comment]
first box is ticked. 
Second not sure, but seems to be the case (tested on form ascent who with). Inactive accounts are linkable, but if partial match finds multiple user they seem to be lower down.

Not sure due to possible private thing clouding data, and just small sample to find test case

Candidate for confirmation & closure
