### ISSUE TITLE
Adding subareas too difficult to find

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#3265]
**What happened?**
The "add subarea" for this node is not displayed:
https://www.thecrag.com/climbing/france/massat
Adding is only possible via the 3 dots next to "Edit cliff". I found this too hard to find out, despite being a long-time user and knowing what to look for.
Conversely, other nodes only display the "Add subareas" button:
https://www.thecrag.com/climbing/france/calames
Is this intended?

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/france/massat

Ideally also provide screenshots:

**What you expected:**
I'd like to see both options "Add subareas" and "Add routes", at least from the Crag level and downwards.

**Comment by MelwinQ** [comment]
Indeed, I first had to remove a placeholder route before being able to add the sectors, so I wrecked my example, sorry.
So Christoph thinks that this is intended behaviour. I guess I'd agree in most setting, but I can think of occasions where sectors exist next to some "extra routes" that do not belong into a sector.
Additional to this situation, I may want to add a new route I have climbed, but do not know what sector it belongs to, so I'd add it at the main node for someone else to sort in.
An experienced user will find a workaround for this, but the novice may not. If this is compensated by forcing a more rigorous, I can accept it.

**Comment by brendanheywood** [comment]
Yeah this is intentional, we actively discourage adding both routes and areas mixed together. The only time you really want this is when you are in the process of breaking up a large areas into subareas. The full list of actions will always be under the 'action' or '...' menu so if it is ever missing from there then that is definitely a bug. So I think I will close this one. 

Also if you want to make permanent failing test cases make them in the test area:

https://www.thecrag.com/climbing/test-area
