### ISSUE TITLE
Add tags for topos & route order to be left to right, or right to left

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3278]
**What happened?**

Split from https://github.com/theCrag/website/issues/2916#issuecomment-424593740

**What you expected:**

* [ ] tags which describe the order

**Comment by rouletout** [comment]
Coud be nice - now it is often in the description and not consistently used.

**Comment by Mdemaillard** [comment]
+1

**Comment by rouletout** [comment]
What about the Mountain Project approach to allow switching from R->L to L->R? So meaning this "tag" could be active to click on? Overkill?

**Comment by gui84** [comment]
+1

**Comment by Mdemaillard** [comment]
hum i dont really see the point of the dynamic switching, and it would have to be linked to the topos display and all.
 
If we have a crag properly set up and accordingly tagged, that is good for me.
If say the guidebook is on the opposite direction, we do have somewhere the option to reverse the order (is it in bulk edit ? or move ? dont remember) and can replace the tag.

**Comment by georg-d** [comment]
**IMHO short explanation of the need and benefit would be great :)** so everyone can understand why we shall add complexity in code & GUI.

**When is TRL/LTR/unsorted information is required or helpful?** 

For my climbing tours, it is virtually never, because we'll virtually only go climbing somewhere 

1. we have _not only_ knowledge about route names but also other context information like topo and/or names written on the wall and/or input from other climbers or a hut crew or information desk and/or... that make LTR/RTL/unsorted information clear or redundand
_OR_ 
2. we can see routes in enough detail to tell apart feasible routes from those that are too difficult or dangerous for us, so we just go climbing - completely independent of LTR vs RTL. 

For maintenance of theCrag website, it IMHO does also not make a difference: 

- If I do know a crag, I instantly see routes are not sorted according a natural order, and can correct it. 
- If I do not know a crag well enough to know the routes are not sorted, I would also not be able to tag as "unsorted".
- If in between i.e. I doubt current order makes sense but I cannot correct it, it's IMHO much better to privately ask users that have been at the crag/cliff whether they'd correct the sequence, or start a public discussion - in both cases, people are pro-actively nudged / made aware of a need to edit, while a tag would be passively sitting around.


**If TRL/LTR information is helpful, it can already be conveyed in route/crag/cliff description. How does adding a tag help better?**

- If already mentioned in description, how does _additionally_ (or instead) setting it as tag add value? I never felt I want to use route sorting order as filter like tag "_wet in rain"_ or _"morning sun"._ I can't imagine I'd ever want a a report on it. Etc.
- If sorting order is missing in description, IMHO also a tag would be missing: Descriptions and tags are modified in _exactly the same_ edit crag/cliff page. So, if everyone saw too little benefit to add TRL/LTR in description to type the few characters _"Routes are ordered from left to right",_ I massively doubt they are seeing sufficient benefit to open the same edit page and search in the quite long list of tags for _"Routes ordered LTR"_.
