### ISSUE TITLE
Private or restricted crags

### ISSUE THREAD

**Issue by johnpitcairn** [theCrag/website#3295]
For crags where access is highly sensitive, or where the landowner or developer wishes to restrict access to a specific tightly-controlled group of climbers, it would be useful to be able to add those crags so ascents can be logged, but tightly restrict view, edit and logging permission.

Generally the landowners or developers do not want the full crag details to be publicly viewable, and do not want online or printed guides freely circulating, because that results in people just turning up at the gate or entering without permission, especially travellers and gym climbers who are not familiar with local access issues.

They may be more comfortable with a moderated process for obtaining view access, and that process could be explicitly shown in place of  the usual crag details if the user does not have permission.

It's unlikely landowners would want to manage such permission themselves (they already manage land access), and generally they are not very technical, so this is probably something that would need to be delegated to a trusted user. 

Access in New Zealand is becoming very sensitive, a lot of crags are on private farmland. Has this sort of thing been considered before?

**Comment by scd** [comment]
This is half in place already. We have crag restrictions based on completely restricted, logged in only, karma and permissions levels. We also find that aspects of crags are sensitive, so some crags have location hidden or topos hidden but routes are available to tick.

This is a hugely complex area because these restrictions need to be propagated everywhere including feeds, maps and api and are dependent on the eyes of the beholder.

We have been using this to manage sensitivities, but it is still a hammer because all the restrictions are based on global characteristics of climbers. 

We have specked out secret crags for groups, but are dependent on our teams implementation before this can work can be completed. 

Philosophically we are also against the local climbers only mentality. If it is private land then it is the right of the private land owner to decide, but if it is public land then we are unlikely to turn this off and make it available for local climbers only.

With sensitivities the first thing to do is to document them accurately on the crag in question.  Where sensitivities are genuine we are happy to reflect this in the level of information that is provided.

**Comment by johnpitcairn** [comment]
There are a couple of crags in particular I am thinking of where it would be good to be able to log ascents for those who have been granted access. One of these is definitely private land with access specifically granted by the landowner on a visit-by-visit basis, the other is a sea cliff but with some government department land-use and Maori oversight issues that the developer needs to resolve.

The one on private land I'd like to open a conversation with the owner about making some details public to clarify access and prevent the spread of old info and guides. If he is open to that idea, how might we proceed? It's not a locals-only thing.

**Comment by scd** [comment]
Land owner: whatever he decides we will document and get as close to implementing as we can. I imagine he wants location removed so that theCrag cannot be used to find their crag. Removing location and approach description pretty much means that nobody can find the crag so it is effectively local climbers only. Whatever we implement will be pretty much the same for everybody because we don't have teams yet. So if you want to still tick there then we should keep the routes available.

Government department: let us know the outcome. There are some crags in Sydney where information has been completely removed for everybody because of cultural significance. This is backed up by real climbing bans with penalty of fines.

**Comment by johnpitcairn** [comment]
OK, will follow up, thanks.

**Comment by scd** [comment]
With sensitive crags please be aware that public discussions are not always appropriate. When it comes to specific crags it is best to send us email rather than a git hub issue. 

The reason is that there may be information in the discussion that the person responsible for the crag does not want to be public.

**Comment by johnpitcairn** [comment]
Of course, will do.

**Comment by johnpitcairn** [comment]
Turns out the private landowner was fine with putting it on theCrag after I pointed out the advantages in having the access info more available.

**Comment by scd** [comment]
+1 for documenting the truth ...

**Comment by Mdemaillard** [comment]
see #1345

**Comment by georg-d** [comment]
**How can we ensure a crag is not getting created *and* visible?** 

Situation: Nearby my home, there's a crag with several nicely developed routes that _must not_ appear in any topo (printed or online) or the land owner closes it for climbing, because it's already strongly visited and shall not become even more visited (noise, nature protection etc). So it's "local climbers only" - but not triggered by the climbers but the land owner. 

The approach discussed in the posts above does not help: **As the locality is small and it's name is well known, it's not a solution to create the crag with it's proper name and just leave location & approach empty.** Then, people would see the routes etc, wanna go there, and by the crag's name, they know the rough location, and at the location, it's a matter of minutes to find the routes. 

**The approach of secret crags would be a cumbersome, unreliable hack:** As far as I understood https://github.com/theCrag/website/issues/1345, theCrag already supports a "secret" flag for crags. But existence of a secret crag does not prevent that someone creates another crag with same name: Currently, if you want to create a duplicate crag at the exactly same parent node, you get an error message that the crag name was already taken. As people cannot see that secret crag, they may think there is a bug in theCrag and try differently. For example, you can still create a crag with same name one level more down in the hierarchy (if e.g. someone considers the crag as a sector / sub crag of a nearby crag - realistic, as nothing about the "hidden crag" is published, there is no consensus about the parent entity). Same same for one level up in hierarchy or in sibling entities. This is absolutely OK from an application point of view, but not helping for the issue at hand. Moreover, I consider a bug that after creating the crag one hierarchy level higher/lower, you can move it one level up/down in the hierarchy and thereby creating a duplicate that has been rejected at first (this is why "test area 11" existing twice in [Sandpit](https://www.thecrag.com/climbing/test-area/area/82073166)). Hence, we'd need to create a secret entity in all entities that are around: A secret area in the region, a secret crag in all nearby areas (yeah, Murphy's law, the crag I'm talking of is at the border of 3 areas...) and also a secret sector in all nearby crags. 
**Even if we did create secret entities at all hierarchy levels, this does not prevent people from creating a crag with different name,** so assume e.g. "Gefäll" is blocked by secret area + crags + sectors, someone could create "Gfäll" (in local dialect, the e is often omitted) or "Gefäll 2" or "Gefäll East" or "unknown name", and the crag could still be found by it's location drawn on the map and the approach description.

**So a more user friendly, technical approach (but not a really reliable solution! See below) would be a combination of two features**
1) **For a given region or area, a list of names that are disallowed/blocked in _all child levels_ and a text message that the user sees when trying to create an entitiy with that name,** e.g. "Land owner explicitly wants crag XYZ not to appear". I guess we shall allow to create routes with the name because these are leafs in the tree and thus are not able to carry child elements, so cannot be "abused as a hack" to still create "something like a crack". And it's not that uncommon to name routes after areas/mountains/crags that are nearby or famous.
2) **Polygons where no location can be drawn for a given region or area.** This effectively prevents a crag appears on the map at the correct place after it has been created with different name.

Even with these 2 features, the crag may appear without exact name & location. It will still be visible in the correct area and it can still be found via access description.

**The only really reliable solution would probably be really easy to implement: A feature that any newly created crag in a certain region/area/crag needs approval by someone.** That "someone" could be an official body like "IG Klettern" or a group of users (similar process to existing one  for requesting edit rights).

**Comment by lordyavin** [comment]
Long story short: As you @georg-d already stated in your last paragraph, it is up the community to enforce that sensitive/private/secret crags are not published anywhere. IMHO there are a lot of more usability and bug issues the @theCrag/thecrew should focus on before implementing over-engineered features that help non-members and just a small group of climbers.

Think beyond theCrag. How does a landowner or a selfish group of crag developers prevent someone from publishing a guide book? You can't, if you don't know about it. If it has been published, the people concerned must ask for injunctive relief or sue for it. And if 10 years later someone publishes something again, then it starts all over again.

I also think it's utopian that every interest group in Germany or worldwide will create an account and entrust someone with the "monitoring" of theCrag, 8a.nu, 27Crags, UKC, mountainproject.com and offline publishers.

**Comment by rouletout** [comment]
This is in place with "private crags" that can be completely hidden and managed by admins. Closing.
