### ISSUE TITLE
Map bbox api should exclude test area routes

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3343]
**What happened?**

There is a random blob of 831 routes == 'Test area' https://www.thecrag.com/climbing/test-area in the middle of africa:

https://www.thecrag.com/climbing/africa/maps#2.42,6.37,5.0,,auto

![image](https://user-images.githubusercontent.com/187449/51287008-a8e49c00-1a49-11e9-8426-c67a82eb262f.png)

**What you expected:**

* [ ] exclude the test area from all stats and maps related apis

**Comment by Mdemaillard** [comment]
And it is growing. 1.5k routes at the moment.
Should we manually edit the locations grouped somewhere in the middle of the ocean as a temporary measure ?

**Comment by scd** [comment]
Test area should be excluded from API and consequently maps. Please show
example if this is not the case.

**Comment by Mdemaillard** [comment]
The only artefact is that blob hovering over roughly Ghana with label "World" and quantity of routes exactly as per the Test area (1517 at the moment). 
Since there is no route visible under world, and all continents are located, there shouldn't be a world bubble.
![image](https://user-images.githubusercontent.com/60388146/76929616-558c0900-68ed-11ea-97db-14cee7fa2cf5.png)
The crags locations themselves are only visible when editing them inside the test area. Not visible on the map.

**Comment by scd** [comment]
I think this is an API issue not a maps issue.

**Comment by scd** [comment]
This should be fixed now
