### ISSUE TITLE
Add not Kid friendly tags, and maybe 'sort kid friendly'

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#3377]
Hey,

it would be great if there where multiple tags for kid friendly. Many guides use 3 colors to classify how well a crag is suited for kids. Something like this would be cool on thecrag too.

For example take the new current icon and change the background color to Green, yellow and red:

Green= kid friendly, you can basically go there with smaller kids without a 3rd person
Yellow= ok with kids, but better have a 3rd person
Red= not suited for kids

Kids are always meant small ones, not teenager ;)

This information is basically the most important for parents.

In addition (but this is another feature request) it would be great to be able to filter on the map page. For example hide all areas with the tag "not kid friendly".

Best regards
Philip

**Comment by lordyavin** [comment]
+100

**Comment by brendanheywood** [comment]
@Drazhar can you throw some example pictures from the guides for this?

**Comment by Drazhar** [comment]
We are currently traveling, but I can submit an image of the guide books in August :)

**Comment by lordyavin** [comment]
![_20190711_083843](https://user-images.githubusercontent.com/1528540/61028346-c40ce480-a3b8-11e9-93d3-ff0ff6a08754.JPG)

**Comment by Drazhar** [comment]
Merci Kai :)
That's the publisher I would also have chosen.

**Comment by matozoid** [comment]
For me, I would love to filter this on "kid unfriendly" :-)

**Comment by killakalle** [comment]
As a parent, I totally support @Drazhar 's suggestion.

The current situation is that dogs get more tags than kids. They get two tags, kids only one:
![image](https://user-images.githubusercontent.com/30682796/82670906-4a7f8d00-9c3e-11ea-8b65-54afbadaa9d6.png)

**Why is it important to have at least a "Not kid-friendly" tag?**

In a guidebook, I can rely on the (almost) completeness of information of listed crags. So, when the guidebook offers only a "kid-friendly" tag, then I can safely assume that all crags without that tag are not kid-friendly. Here on theCrag this assumption does not hold, because most of the crags are not fully documented. At least here in my area (Spain).

So, whenever I see a crag on theCrag without the "kid-friendly" tag, to me this can mean two things:
a) The crag is not kid-friendly
b) The crag might be kid-friendly but nobody bothered applying that tag

In the end, I can only safely know the kid-friendly crags that have a tag. But crags that are not kid-friendly are not clearly identifiable.

Coming back to @Drazhar 's suggestion, I think this is great. However, if it's easier to implement, it would be already super helpful, to tag crags with "not kid-friendly". This would make that piece of information explicit.

PS:
On a side note and not seriously related...

During the Coronavirus lockdown in Spain, people were allowed to take their dogs for a walk outside - but children were not allowed any fresh air

_“Parents can be angry,” said Diego Figuera, a psychiatrist at the San Carlos hospital in Madrid who works with children. “How do you explain to them that you can take your dog out, but not your child?”_
https://www.nytimes.com/2020/04/18/world/europe/spain-children-lockdown-coronavirus.html

**Comment by rouletout** [comment]
This absolutely makes sense - it can't be No Kids though as it is not forbidden but Kids not recommended or so....

**Comment by Mdemaillard** [comment]
+1 for Not Kid friendly. 
I wouldn't go for 3 levels, the middle one would be even more vague and open to interpretation than a clear cut yes/no status. 

What would be yellow ? access is tough, but friendly once there ? friendly from 10year old upwards ? your kid will bleed but nor die ? if a 3rd person is needed, i would consider it not kid friendly. Any place is fine for any age with a full time babysitter. Something vague like that, if someone bother to document, would need a text description  in one of the fields, and make the symbol superfluous.

Also wouldn't go for colors, so far the others don't. If we use Green/Red  the NO fire symbol won't really register.

**Comment by rouletout** [comment]
Tag is available (icon still missing) - closing.
