### ISSUE TITLE
"Log Ascent" button on mobile not showing up

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3386]
**What happened?**
on mobile when selecting (multiple) routes there was a dynamic action button at the bottom of the screen: "log (X) ascents". This has gone!
 

Ideally also provide screenshots:

![image](https://user-images.githubusercontent.com/2226714/53959688-a7982d00-40e4-11e9-9bc8-6e60f64a566d.png)

**What you expected:**

- [ ] getting that dynamic action button back
- [ ] maybe getting something similar for desktop version as well

**Comment by scd** [comment]
@brendanheywood the reason for this regression is that we forgot to requireCSS responsive.css in port to new templates.

I have added it to `nodeListView` template and the button now appears. Do you remember if it was intentional to no longer link to responsive.css. Maybe there are a wide class of bugs because this was missed. 

Also I have only included the requireCSS in the nodeListView template. @brendanheywood could you please assess whether this needs to be included wider.

**Comment by lordyavin** [comment]
+1

**Comment by brendanheywood** [comment]
no responsive.css is deprecated, whatever is in there which you need we should refactor out

**Comment by scd** [comment]
Great to know. I have pulled out the relevant media query and put it into the nodeListView.less file.
