### ISSUE TITLE
Links to Google Maps App broken

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3414]
**What happened?**

On mobile, clicking on "Directions in Google Maps" leads to an error in the Google Maps App (Link not supported - this is a free translation from German). Copying the coordinates of the link manually into Google Maps App works and gives a valid route. The links also work on desktop - it seems that the app has trouble interpreting the link we hand over.

Example areas tested and not working:

https://www.thecrag.com/climbing/mexico/bernal-qro/?lang=en
https://www.thecrag.com/climbing/mexico/jilotepec
https://www.thecrag.com/climbing/switzerland/jura/basler-jura

All of these links worked until a few days ago on mobile.

Tested on iOS from Safari to Google Maps App.

Ideally also provide screenshots:

**What you expected:**

Working links.

**Comment by brendanheywood** [comment]
As you said, these links work on desktop,they worked a few days ago. They also work in most places and not here. There is nothing wrong with the links and they still confirm to the spec below. The issue is on googles side.

https://developers.google.com/maps/documentation/urls/guide#directions-action

So I can't any useful action to do here which would help

**Comment by Mdemaillard** [comment]
Currently working for a few tested areas in SA. candidate for closure ?

**Comment by rouletout** [comment]
this was a temporary glitch by Google - i close it
