### ISSUE TITLE
Photo vs topo uploading, better guidance in UI to choose properly

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#346]
I notice a lot of people uploading a photo, and then making a topo from the uplaoded photo. Aside from it just being a slower process for them it also pollutes the photos and duplicates space etc. We should do whatever we need to, to guide users directly to the topo tool.

**Comment by lordyavin** [comment]
I notice that it is not longer possible to make a topo from a previous uploaded photo. Is this by intention? You should use de-duplication to avoid storing a photo twice. Currently it is not possible to make a topo and add meta information about the underlying photo. Because of this it is impossible to use photos from other copyright holders.

**Comment by brendanheywood** [comment]
I've split that off into it's own bug here: #2693

**Comment by brendanheywood** [comment]
I'm killing this in preference to https://github.com/theCrag/website/issues/2693 

This issue was predicated on topos and photos being different things and helping people choose the right one for the job, but I think it's much better UX and conceptually to merge the two processes and make all topos photos and then topos just have an extra set of steps at the end.
