### ISSUE TITLE
Hong Kong grading

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3472]
**What happened?**

In Hong Kong, sport climbing routes are graded with French system, trad routes with UK System; boulders with V system.
In the general bar, we can see all routes sorted by technical UK system and not french grading system :
https://www.thecrag.com/climbing/hong-kong

**What you expected:**

Replace technical UK system for general grade system by french system (or just add it). It would be better to see all routes grades by french system (only 15% of trad routes here).

**Comment by gui84** [comment]
Adding French as a "General grade system" for Hong Kong should solve this issue.

**Comment by scd** [comment]
That will then break trad routes. Are there any mixed trad and sport areas?

**Comment by gui84** [comment]
Yes but only a few. Is it possible to choose French for sport dominant crags and UK technical for the trad dominant crags ?

**Comment by scd** [comment]
Yes we can swap from area to area, but if there are trad and sport as
direct children then this will need deeper consideration

**Comment by gui84** [comment]
These areas can get UKT grades :

https://www.thecrag.com/climbing/hong-kong/kowloon/area/12484603
https://www.thecrag.com/climbing/hong-kong/waterfall-rock
https://www.thecrag.com/climbing/hong-kong/clearwater-bay
https://www.thecrag.com/climbing/hong-kong/new-territories/area/3012338943
https://www.thecrag.com/climbing/hong-kong/hong-kong-island/area/831274110
https://www.thecrag.com/climbing/hong-kong/hong-kong-island/area/1508992200

And this one V scale grades : 

https://www.thecrag.com/climbing/hong-kong/hong-kong-island/area/12484819

**Comment by scd** [comment]
Let's get @Mdemaillard onto this after I have worked out his permissions

**Comment by Mdemaillard** [comment]
Hi @gui84 

For the V-scale, it seems the HongKong Context is fine. The routes were each defined as US, which creates the display issue.
See example : I changed the first route back to HK, and it is fine.
Can you please update the others ?
https://www.thecrag.com/climbing/hong-kong/hong-kong-island/area/412744662

I am looking at the sports areas now.

**Comment by Mdemaillard** [comment]
@scd i have a feeling it is more a bug than an incorrect setting (?)
![image](https://user-images.githubusercontent.com/60388146/78139440-cd4b4f00-7428-11ea-989c-cb8d9001598b.png)

The HK context includes French for Sport. 
Using the converter on https://www.thecrag.com/en/article/grades, inputing sport 7a or trad 7a does recognize both correctly (notice the color coding orange vs red)
![image](https://user-images.githubusercontent.com/60388146/78139625-18fdf880-7429-11ea-8dfb-a7d6da03225a.png)

![image](https://user-images.githubusercontent.com/60388146/78139653-22876080-7429-11ea-825f-02a7315ed0ca.png)

It is hard to say if routes which context have **not** been individually overridden are recognized correctly, since display is so similar.

But mostly the issue here is on the top grade chart. Is this hard-coded to display the main grade of the Context (in this case UKT) or is it supposed to reflect what the majority of the route are in the specific node ? (maybe with limitation that the system only checks for the grade system belonging to the context)

**Comment by Mdemaillard** [comment]
@gui84 i did all the boulders, except this one:
2 pitches, 88m .... i would change to trad, but i see one of the grade components is Boulder Joshua Tree scale ???
Can you check what is this route about ?
https://www.thecrag.com/climbing/hong-kong/stanley-peninsula/route/13964011

**Comment by scd** [comment]
It looks like Matt Tranter added the route. It is not in the stream but he is attribted in the grade contributions. Maybe ask him what the intention was. Otherwise post a message on the route.

Also 7a means different things for different contexts. I don't think there is a bug. I suspect that we made the HK context when contexts were assigned at the country level only. My understanding is that a 7a route in Hong Kong is a completely different grade if it is a sport route vs a trad route.

Welcome to the world of climbing grades. The climbing grade space is completely crazy and way more complex than anyone believes. It is a rabbit hole we still have not found the end of.

**Comment by Mdemaillard** [comment]
Agree --> My understanding is that a 7a route in Hong Kong is a completely different grade if it is a sport route vs a trad route.
Yes, i start to realize the depth of the hole :-D
a common issue seems to be differentiating sport and trad. boulder is different enough and is generally catered for well.

It just seems strange to me that a grade context is named "Hong Kong", but doesnt fit properly to the "Hong Kong" usage. 
I will look at it again. It seems i will 
- leave the Trad and Boulder area under HongKong
- change the sport only areas to grade concept FR
- leave an area if combined sport/trad so a minimum of route still needs the override and display {xx} YY

**Comment by Mdemaillard** [comment]
But that would create the expectation that every new sport crag gets updated to FR again, which is upkeep.
@scd in the HK context only, can 
- the British Adj. and British Techniacl be removed from "Main grade system"
- the french be added to "Main grade system"
- the "additional sport : FR " be replaced by "additional Trad : British Adj. + British Technical" ?

That would leave only the trad areas to be manually updated and maintained, which as gui84 points out is a smaller portion than sport, and i would then do it.

**Comment by rouletout** [comment]
@gui84 do you consider this solved or is there anything else you need for Hongkong?

**Comment by gui84** [comment]
No, because it's still UK technical grades displayed on the general grade chart rather than french sport grades (45% of the routes are sport, only 17% are trad) :

https://www.thecrag.com/en/climbing/hong-kong

**Comment by scd** [comment]
I have updated HK context so 7a

  * as a trad route will be interpreted as British Technical
  * as a sport will be interpreted as French

<img width="470" alt="Screen Shot 2020-11-14 at 1 29 37 pm" src="https://user-images.githubusercontent.com/373058/99137263-b38c0e80-267d-11eb-891d-b4cfb0803c6e.png">
<img width="462" alt="Screen Shot 2020-11-14 at 1 29 54 pm" src="https://user-images.githubusercontent.com/373058/99137265-b686ff00-267d-11eb-925a-689523fab2a0.png">

**Comment by scd** [comment]
Available next release

**Comment by rouletout** [comment]
Fixed with release 88
