### ISSUE TITLE
cite publication

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3582]
**What happened?**

Can't find anymore cite publication functionality.

**What you expected:**

* Cite a publication for a route grade
* Cite a publication for quality of a route

**Comment by lordyavin** [comment]
As I know, this feature is abandoned since a while. In Australia's index you see this quite often but for the rest of the world there are no publication maintained we could cite. I assume this is due to the fact that this citation possibility needs permission/contribution by the publishers/authors of guidebooks. So far theCrag could not attract non Austrialian publishers to cooperate with theCrag or use theCrag for marketing.

See also https://www.thecrag.com/en/article/publisherparticipation

Maybe @rouletout may give us some insights on this.

**Comment by rouletout** [comment]
This feature is still available bur not for general use. As @lordyavin mentions, it is used for publishers like advocacy groups (check e.g. Kenya or South Africa to see examples outside of Australia). If you have a sepcifc one in mind that wants to work with us, please direct them directly to my attention.

**Comment by rouletout** [comment]
This is re-introduced with release 101 - not for the public but for admins for now.

**Comment by lordyavin** [comment]
And how to use it then?
