### ISSUE TITLE
Possible Bots

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3618]
I think we are getting problems with bot accounts. I'm starting to document suspicious accounts here :

* [x] https://www.thecrag.com/climber/marta5
* [ ] https://www.thecrag.com/climber/viceionic

**Comment by Mdemaillard** [comment]
not sure if bot, but definitely spam. i flagged a few of her messages before realizing it was the same account, and oh surprise 2 days later a message is an ad for something non climbing related.

**Comment by scd** [comment]
This seems like a new spam vector.  We need a structured way of easily dealing with this. 

One wierd comment does not mean that the person is a spammer so we need to identify repeat accounts and easily manage the accounts being disabled. I am happy to disable accounts that are in the checklist of the top of this issue for example.

Our spam button seems reasonable. Now that I know this is a vector I will be more likely to accept messages flagged as spam. The accounts stream should show muliple spam removals.

I will leave it up to @Mdemaillard and @lordyavin to work out the details, because it seems to be the community will ultimately be policing the spam.

**Comment by lordyavin** [comment]
@scd, additional we should take counter measures to stop bots from registering. Currently we don't use captchas to make this more difficult.

**Comment by scd** [comment]
@lordyavin we use captcha so you can tick that off. This enhancement was made a few months ago because we got 3000 accounts registered in a day. For accounts we actually use our own spam decision engine which uses captcha as one input. It is currently fairly simple though.

Spam is a major time sink and a continual arms race. There are thousands of accounts that could be dormant spam accounts in the background. I can see that this work may start to weed some of those out.

**Comment by Mdemaillard** [comment]
linked to #1971

**Comment by lordyavin** [comment]
Next candidate found: https://www.thecrag.com/climber/viceionic

**Comment by rouletout** [comment]
This is covered now by better Spam account detection and review, closing
