### ISSUE TITLE
accounts should have a possibility of noindex flag for crawlers

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3638]
Discussion about:
- inactiv accounts
- community accounts
- private accounts

* [ ] Add flag to private account so that the account is noindex

**Comment by scd** [comment]
private accounts have noindex, community accounts should be indexed as there is no reason for them to not be discoverable by google.

I am not sure about inactive. It is probably better that they are discoverable for transparency so that climbers can find themselves and set to private if they do not want to be discoverable on google or deactivate their account if they no longer want a relationship with us.
