### ISSUE TITLE
Alternative to GoogleMaps: OSM openstreet maps / Baidu / vtrhome

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#365]
You probably have heard that Google starts to charge for the use of the map API (http://googlegeodevelopers.blogspot.com/2011/10/introduction-of-usage-limits-to-maps.html). I don't know if this is an issue for you or if thecrag can remain below the limits that still are free. If not and you are looking for an alternative, I'd like to point your attention to openstreetmap.org . Here's a short summary for your information.
pros:
- free as speech, not only as in beer - no legal restrictions when including maps
- map coverage of trails, paths, isohypses and other relevant landmarks in the backcountry is usually way better than in GM
- different map layouts can be chosen (even customized, if necessary)
- users can improve unmapped areas, if they want to
  cons:
- no easy switching between satellite imagery and maps (yet)
- API probably not (yet) as advanced as Google's
- need to be able to support static maps (eg in streams)

General tasks:
* [x] add a concept of a map service
* [x] each service may support different types of services, eg just tiles, map api, static map, directions, street vs satellite vs terrain 
* [x] each service may have a limited scope, eg europe
* [x] each service may have a collection of api keys for dividing up traffic to segments for analysis
* [x] allow any node to select, or rank, which services to use. eg Germany may prefer OSM
* [x] allow this selection to be made for different levels or area subtypes. eg for regions we want streetmaps, for crags usually want satellite.
* [x] allow a map service to quickly disabled and enabled

**Comment by brendanheywood** [comment]
Another +1 from FB https://www.facebook.com/thecragcom/posts/10153533269322604

**Comment by Drazhar** [comment]
And a +1 from me, because you aren't allowed to edit google maps in Swiss or Germany

**Comment by brendanheywood** [comment]
Yeah mapmaker worldwide has been turned off for a couple month due to some spam data.

**Comment by brendanheywood** [comment]
Bump from support email

**Comment by Heineken** [comment]
I claim the "bump". My mail was specifically about the help text on https://www.thecrag.com/article/Geolocation#addtrack encouraging users to contribute to GM without mentioning OSM.

If that has proven to be problematic and the plan is to become less dependent on GM (yay!), both facts could be expressed in that help text in order to stop sending people's ambition in the wrong direction. No coding involved :-)

**Comment by brendanheywood** [comment]
Just split that off into it's own smaller issue: #2464

**Comment by Heineken** [comment]
Names of cliffs/subareas/crags can be set in OSM, for example here:
https://www.openstreetmap.org/edit#map=19/37.17117/22.89754
I don't where they would be rendered/used, but it would be nice to exchange that data with theCrag to avoid double work. Like:
- when area location is not set in theCrag, use coordinates from OSM to show crag location or at least suggest when setting location
and, the other way around
- set the point (or area, if possible) in OSM when defining location in theCrag

**Comment by gui84** [comment]
I just wand to add that it's a pity that Openstreetmap layer is not displayed in maps area, but only when we edit location. We can't simply use their work for geolocalisation. Moreover, many times Openstreetmap is more accurate than Google maps for crags approach. It's a openproject compared to Google maps.

**Comment by lordyavin** [comment]
@gui84 I don't agree. As I stated earlier I think the map should display the layer that was used to set/draw the geo location. The different layers differ in quality and IMHO a human should decide what to display best. The standard OSM layer isn't the best for our use case because it doesn't show the terrain features. Much better would the [opencyclemap.org](http://opencyclemap.org) layer.

**Comment by brendanheywood** [comment]
Next year we will embark on a major ground up rebuild of the maps. The intention here is that the cliff / crag can specify what tile layer to use as the default. Yes OSM is better in some places, but in other places it is not great, google maps will continue to be the default unless overridden. Also pushing and pulling data into and out of OSM is very problematic for lots of reasons, some technical and some around licensing, but mostly because it's not really structured data and the semantics of it don't cleanly map to our data model. OSM is also a general purpose map, often climbing areas are called one thing by climbers and another by tourists.

**Comment by gui84** [comment]
@lordyavin "I think the map should display the layer that was used to set/draw the geo location"
But OSM is already a layer helping us to set the geolocation. And https://opentopomap.org/#map=5/49.023/10.020 layer is good.
@brendanheywood "Also pushing and pulling data into and out of OSM". You're right, I think there is not a total compatibility between CCBYNCSA and ODbL. My point is to add a layer to Map area with OSM, in order to choose between these services.

**Comment by MeForThis** [comment]
Google is good where it's market is, e.g. in many parts of Afrika it's useless. There is no money to make, so there is nothing done. Google is just usefull in the first world.

**Comment by brendanheywood** [comment]
Another example of this, google has no data for this part of malaysia so the map is just black:

https://www.thecrag.com/climbing/malaysia/area/1640276538

**Comment by brendanheywood** [comment]
That's the point though, there is no data at a fixed zoom level and we don't know ahead of time. We can zoom in the js api, but it would appear not really in the static maps api. The static maps api isn't something I've considered for the new maps rebuild, ideally each new alternate tile server we allow would also have a static map api but I doubt this is the case :(

**Comment by gogulfresh** [comment]
+1 for supporting OSM as alternative to GoogleMaps. In many areas (at least in Europe) GM has nothing but the satelite view while OSM is pretty good mapped!

**Comment by brendanheywood** [comment]
from @rouletout :

> Google Maps doesn’t work in China. For the Map-re-work we should also make sure that Chinese maps work.
> The most important ones are Baidu Map https://map.baidu.com/ and VTR www.vtrhome.net

**Comment by brendanheywood** [comment]
Note to self, google maps does work in china, but we need to set the region for it and load it differently:

https://developers.google.com/maps/documentation/javascript/localization#GoogleMapsChina

This one is a little tricky though because we are targeting where the user is from, rather than the region the user is looking at. So this should be independent of the ability to toggle maps tiles to different map bases like baidu and osm.

**Comment by brendanheywood** [comment]
Well it took 7 year to bite us...

**Comment by brendanheywood** [comment]
Work is commencing on this. If anyone has particular examples of countries or crags where on certain map service is better than google please document it here so I have as many working test cases as I can.

Also please let me know if there are any location specific map services with open access or open licensing that have better quality maps than google. I've found a couple and they are usually government run but the more the merrier. In particular ones which support terrain view or satellite / aerial view. The OSM data is only good for street maps. Or any others which may be of general interest to climbers, for instance there might be a few geology / rock type map services, or map services which help identify owner for access etc.

Not all services may end up in the initial release but I want to make sure we are flexible enough to accommodate most mapping services that we might want to down the track.

**Comment by gui84** [comment]
Great ! For Mainland China and Hong Kong (where I live), OSM data is way better than Google maps (for approach path).

**Comment by MelwinQ** [comment]
As commented on 7 Jan 2014, OSM is excels over Google Maps e.g. in Sächsische Schweiz and its Czech counterpart  Labske piskovce (see eg https://www.openstreetmap.org/#map=15/50.9086/14.2257).
I reckon that this would also apply to most other crags in Germany.
As for other alternative services, https://www.outdooractive.com/ have good maps  that are also used by the German, Austrian and South Tirolean Alpine Club on their platform alpenvereinaktiv.com . Certainly not free, but worth checking out.

**Comment by gogulfresh** [comment]
Wilder-kaiser:
http://tools.geofabrik.de/mc/#13/47.5627/12.3056&num=4&mt0=mapnik&mt1=google-map&mt2=geofabrik-basic-colour&mt3=mapnik-german
Sulzfluh:
http://tools.geofabrik.de/mc/#13/46.9993/9.8360&num=4&mt0=mapnik&mt1=google-map&mt2=geofabrik-basic-colour&mt3=mapnik-german
Spitzingsee/Rotwand (I am surprised that Google maps has quite some trails but still it's far off):
http://tools.geofabrik.de/mc/#14/47.6418/11.9396&num=4&mt0=mapnik&mt1=google-map&mt2=geofabrik-basic-colour&mt3=mapnik-german
Steinplatte (skiing is pretty good at GM but hiking...):
http://tools.geofabrik.de/mc/#14/47.5958/12.5793&num=4&mt0=mapnik&mt1=google-map&mt2=geofabrik-basic-colour&mt3=mapnik-german

**Comment by brendanheywood** [comment]
Wow that's a cool tool :)

**Comment by Drazhar** [comment]
Outdooractive is using osm with an own renderer, so it's also osm ;)

**Comment by brendanheywood** [comment]
I have briefly considered the idea of setting up our own maptile server, but only as a very last resort, and even then it doesn't solve a few issues and will create a lot more work. 

I do really like their custom static maps previews:

![image](https://user-images.githubusercontent.com/187449/45995217-7d285980-c0da-11e8-85cd-2b8f5d7615b3.png)

**Comment by TillF** [comment]
@Drazhar: While Outdooractive / Alpenvereinaktiv offer OSM as an option, they also have ther own layer which in places is significantly different (and often more detailed) than OSM. However, apparently it is not free.

**Comment by Drazhar** [comment]
@TillF: Strange, I always tought, that outdooractive is also using OSM for their default app. Espacially cause when I added something to OSM it also appears on outdooractive. As far as I understand it, it just gives you the option for the default OSM render style.
But it was a long time ago where I actively used it ;)

**Comment by lordyavin** [comment]
Hey guys, please treat this issue with high priority. I think the static maps a a real pain in the ass. I'm so used to be able to zoom out to check where a crag is located.

**Comment by brendanheywood** [comment]
Just a heads up that progress on this has been moving along fairly well. Stay tuned :)

**Comment by lordyavin** [comment]
👍 Any details?

**Comment by brendanheywood** [comment]
When we are ready we will put out a call for testers, maybe another week or so

**Comment by brendanheywood** [comment]
I am after testers / helpers specifically for Chinese maps which may have a few extra challenges, ideally people who are a bit more technical and who might know things about chinese maps services / apis / tile servers etc.

If you can help please email me at support@thecrag.com (@gui84 ?)

**Comment by brendanheywood** [comment]
I've just re-read this entire thing, and surprisingly there is very little not yet done now so I will close this. If there are particular regions that want to add a new base layer preference, or a completely new base layer then we'll do them one by one as new issues.
