### ISSUE TITLE
Don't aggregate ascents from different days

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3653]
**What happened?**
Yesterday (Wednesday) morning I logged ascents from Tuesday and in the evening I logged the ascents of Wednesday. Unfortunately the ascents are aggregated into one stream event but they are two different events. Additionally the stream comment does make it worse as it describes the event/session but some of the ascents don't belong to it.

https://www.thecrag.com/event/3231186195

![grafik](https://user-images.githubusercontent.com/1528540/80071993-e3d75880-8545-11ea-85d1-d65ef4681215.png)

**What you expected:**

* [ ] Don't aggregate ascents from different days in a single stream event if there is a delay between ticking.

Of course the threshold for delay is difficult to determine. Maybe this needs some discussion.

**Comment by scd** [comment]
I also noticed this happening to me for the virtual event.

The stream event date attribution is not very good for virtual events as there is no time zone associated with this area. Normally the stream events are pretty good with time zones because they are tied to the crag, which we know the time zone for.

I am pretty sure we have got some good algorithms for physical crags. A lot of brain power went into aggregating. We never considered virtual.

**Comment by lordyavin** [comment]
So this is an virtual issue only?

**Comment by scd** [comment]
I think it is just a virtual issue. I doubt that you would have had this problem if you posted to a physical crag in your timezone.

It is possible that there are still issues with aggregation for physical crags but our algorithms should be catching things. The virtual training will definitely have aggregation problems.

I think we can close this.
