### ISSUE TITLE
GitHub does not render contibution page

### ISSUE THREAD

**Issue by georg-d** [theCrag/website#3670]
**What happened?**
When createing a GitHub issue, at the right "Helpful resources" and "Contributing" appears, linking to https://github.com/theCrag/website/blob/master/contributing That page's source is shown directly instead of being rendered.

**What you expected:**

[ ] page is redered, i.e.  formatting tags are applied

**Comment by Mdemaillard** [comment]
Hum, in my opinion that Contributing link should be removed rather than spending time on it. 
its current content is irrelevant here.

**Comment by rouletout** [comment]
Yes agree - who can remove that?

**Comment by Mdemaillard** [comment]
Hum i didn't find where to edit or remove the link, but can now modify the link target... not perfect, but since we this github project doesn't seem to be used anymore as active repository ? 
My content proposal:

Check the website help for up-to-date details on how to contribute
https://www.thecrag.com/en/article/contributing

**Comment by scd** [comment]
It is not used any more

**Comment by Mdemaillard** [comment]
alright, it still doesnt render, but is more to the point now.
@georg-d / @rouletout , happy to close ?

**Comment by georg-d** [comment]
@Mdemaillard: IMHO much more readable :+1:
