### ISSUE TITLE
Import logbook: Gear style not taken in account (Match is marked with Red Cross)

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3671]
**What happened?**

I observe that since quite a while that on CSV import and Bulk Assessment actual matches are not shown. See screenhot, this is a perfect fit but has a red cross. Why is this?

<img width="858" alt="Screenshot 2020-05-16 at 17 28 21" src="https://user-images.githubusercontent.com/19162952/82132245-efabe880-979a-11ea-9599-8d8a043a5461.png">

Ideally also provide screenshots:

**What you expected:**

A green check and automatic assignment / match.

**Comment by rouletout** [comment]
These are 3 perfect examples of perfect matches that are not identified correctly:

<img width="760" alt="Screenshot 2020-05-18 at 17 03 14" src="https://user-images.githubusercontent.com/19162952/82267447-9de59880-9929-11ea-921f-a86c3b77866e.png">

**Comment by scd** [comment]
The tick or cross comes from how close the grade of the ascent is compared to the grade of route.

The first image in this issue is selected and has a cross. I think it has a cross because the grade may have been interpreted as a 8c French grade rather than an 8C Fontainebleau grade.  This could explain the original post, but I suspect there is something completely different.

I am kind of confused with what is wrong in each of these examples. This is a really complex form and I have not used this for a long time.

Firstly can we establish if this is broken for every ascent that is uploaded or is it broken for an edge case of ascents.

My initial guess is that this is an edge case of ascents and it is bouldering ascents with Font grades only. If this is the case then next phase of investigation is completely different.

**Comment by scd** [comment]
Note to self. Look at OrderCandidates function in MapAscent.pm module. Gear style not used in the grade assessment.

**Comment by rouletout** [comment]
It’s broken for many of my imports - I assume bouldering. The problem is that the filters don’t work then and you have to go through every ascent manually.. Nicky any ideas?

**Comment by scd** [comment]
The first step is to confirm that it is broken for bouldering imports with Font grades or is it a wider failure. @nicHoch can you please get a fail case going and a success case.

Having done a code review it does not take into account gear style when reading the imported grade, which could explain everything going on in this card. Note that the import procedure was built before we made the enhancement for grade parsing to take into account gear style.

**Comment by rouletout** [comment]
@nicHoch there is a pending import in DWoods account - this is all FB if that helps you with the test cases.

**Comment by rouletout** [comment]
@scd I played once more with this - it is what you say. If I set the context to Fountainbleau the matches are correct (but then the sport routes don't match).

<img width="527" alt="Screenshot 2020-05-27 at 16 56 44" src="https://user-images.githubusercontent.com/19162952/83080489-9023c780-a03b-11ea-98a1-855ce33813b9.png">

**Comment by nicHoch** [comment]
i looked a bit into the code.
the problem is really that the grade that is derived from the CSV fails often.

example 8A+ in us context get to 5.8 so a grade will never match. 

best solution would be to consider the gear style to all matching decisions (grade and route matching)  

for the moment the best temp. solution will be to lowercase all boulder grades in the 8a exporter. so the FB grade is seldom found.

**Comment by nicHoch** [comment]
available with next release
