### ISSUE TITLE
error handling when topo upload impossible

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3676]
I just tried to upload a topo and I get (just a millisecond after the upload has completed):

```
Software error:
ERROR: Unable to connect to localhost:31218: Connection refused

For help, please send mail to the webmaster (scd@thecrag.com), giving this error message and the time and date of the error.
```
I tried several times, always the same. Connecting to localhost seems a bit odd...

**Comment by Mdemaillard** [comment]
We have had some erratic issues with image upload the past ?weeks?.
This specific instance might have been linked to the server change, if some config was being done on the image server, since usually it works after a (few) retries.

Can you try again and update if it works now ?
Also how is the picture ? any out of the ordinary size or filesize ?

There is definitely something to solve anyway, that error should not occur.

**Comment by birgander2** [comment]
Nicky had sent me a message yesterday evening that something got fixed. And yes, it works again, thanks a lot! 

However, the listing shows now 8 topos (not 2, as it would be correct). This is due to my multiple uploads yesterday getting lost somewhere. But I cannot delete anything anywhere...

**Comment by Mdemaillard** [comment]
Yes... that is also an existing issue. counting pictures, topos gets incorrect after some errors, merging or moves. all on the list... :-)

**Comment by rouletout** [comment]
Closing this as I can't find a reference where this is wrong. if you have one, please re-open with link.
