### ISSUE TITLE
Polish slash grade "VI+/1" is not parsed correctly when editing a route

### ISSUE THREAD

**Issue by FreddieChopin** [theCrag/website#3715]
**What happened?**

When you edit a route and want to give it a slash grade, Polish `VI+/1` is parsed as `VI+`. The system understands only the long form - `VI+/VI.1`. It is worth mentioning that the short form - the one which is not parsed correctly - is much more common. As a reference see:
1. http://toprope.pl/index.php/topo/polska/858-mirow-topo-rejonu-wspinaczkowego-2016
![Screenshot from 2020-06-25 22-49-03](https://user-images.githubusercontent.com/1139038/85793969-211eb900-b736-11ea-94ef-b4720453fa9c.png)
2. topo of North Jura by G. Rettinger, 2020
![signal-attachment-2020-06-25-225401](https://user-images.githubusercontent.com/1139038/85794379-d2255380-b736-11ea-98af-d33d7d99c250.jpeg)
3. http://topo.portalgorski.pl/droga,5958,Wr%C3%B3blowa,Smole%C5%84,Jura-Krakowsko-Cz%C4%99stochowska,Wr%C3%B3blowa,Smole%C5%84,Jura-Krakowsko-Cz%C4%99stochowska
![Screenshot from 2020-06-25 22-58-44](https://user-images.githubusercontent.com/1139038/85794828-88893880-b737-11ea-84ab-4ecf1f5f9cf9.png)

Ideally also provide screenshots:
not parsed correctly:
![Screenshot from 2020-06-25 22-46-12](https://user-images.githubusercontent.com/1139038/85794408-e10c0600-b736-11ea-972a-d3abaf5ee34d.png)
works fine:
![Screenshot from 2020-06-25 22-46-34](https://user-images.githubusercontent.com/1139038/85794417-e5d0ba00-b736-11ea-8260-816e0965cbe0.png)

**Comment by Mdemaillard** [comment]
Hi Freddie, 

for comparison, it would be usefull to check parsing of other slash grades systems, like in US 5.15... 
I believe some display function are used to shorten some display of slash grades, but parsing is already a really complicated area of code with recognition between all the grading systems.

While i understand the issue for convenience, i doubt this will reach a coding priority anytime soon if something similar isnt already working for other grade systems.

**Comment by FreddieChopin** [comment]
> While i understand the issue for convenience, i doubt this will reach a coding priority anytime soon if something similar isnt already working for other grade systems.

It's worth mentioning, that the `VI+/1`, which is the issue here, is the only slash grade where there's a problem, as other Polish slash grades are parsed correctly. Therefore if this would ever be solved, I would propose to implement it as a special exception rather than trying to improve existing parsing to handle also this particular case. Sth like:

```
if (grade_context == "PL" && grade_string == "VI+/1")
  grade = Polish::VI_plus_slash_one;
else
  grade = parse(grade_string);
```

(;

**Comment by scd** [comment]
There was a configuration omission in the short form of polish slash grades. Note that the short form is `VI+/.1` which is now understood in dev.

<img width="461" alt="Screen Shot 2020-11-10 at 4 01 48 pm" src="https://user-images.githubusercontent.com/373058/98630045-5c7cf580-236e-11eb-9c41-49f01678778e.png">

However the missing `.` in the short form that was suggested in this issue (ie `VI+/1`) is not really standard because there is no `VI1` grade.

So if I see somehing looking like `1` in a polish after a slash the parsing automatically interprets this as `.1`

This means `VI+/1` can now be parsed by the system (dev only until next release).

<img width="443" alt="Screen Shot 2020-11-10 at 4 33 21 pm" src="https://user-images.githubusercontent.com/373058/98631902-79b3c300-2372-11eb-8a40-fc6d1a27a753.png">

Because of this configuration change this now makes me ask some further questions for the community 

 * [ ] should the system be able to interpret `VI6` is actually `VI.6`
 * [ ] should `6` be interpreted as `VI.6`. This is effectively what the system is doing if it encounters a slash.

**Comment by FreddieChopin** [comment]
I'm not the whole community for sure, but my input:

> should the system be able to interpret VI6 is actually VI.6

Such form is generally never used, unless someone makes a typo or writes a message to a friend from a phone and doesn't want to bother much with dots and such stuff. So I would say "no".

> should 6 be interpreted as VI.6. This is effectively what the system is doing if it encounters a slash.

This is much too ambiguous, given that sometimes people write "6" or "6+" instead of proper "VI" or "VI+". I would again say "no". If you really want to support something like that (I think you should not), then "6" is "VI" and the non-roman spelling of "VI.6" can only be "6.6". Such forms are sometimes used, but the idea is the same as above - it's easier to write "6.6" on the phone than "VI.6".

**Comment by scd** [comment]
I am not going to implement `6.6` with polish grades unless there is a strong call for it.  In particular it is the same logic which interprets `6` after the slash as `VI.6` in the grade `VI.5+/6` as it is with writing a range `VI - 6` or `VI to 6`.  In this case the 6 is also interpreted as VI.6 so the range means `VI to V1.6`.

It is common logic across all grading systems that the input can accept a range and the second number in the range is in the format equivalent to the second grade in the slash grade. Slash grades are adjacent grades specified in a range. I cannot break this common logic.

I think it is a priority to accept `VI+/1` as another short version of `VI+/.1` over accepting `6` as a version of `VI` otherwise we strangeness like `6 - 6` meaning `VI to V1.6`.

**Comment by FreddieChopin** [comment]
Maybe I was not clear and got too far with the examples (; Neither "6.6" nor "VI6" are used "officially", which is completely opposite to the very popular "VI+/1", so if this last one will be accepted by the system, then great! I think you should not accept either "VI6" or "6.6" and this is perfectly fine.

BTW - the form which is accepted currently - "VI+/.1" is - in my experience - never used. I did not ever see it anywhere. So in case this would make it any easier for whatever reason, you can safely drop that and no harm will be done.

**Comment by scd** [comment]
You were clear, I am just testing the boundaries to make sure we are on the same page. Making adjustments to grading is fraught with difficulty and almost always when I make a change to fix one thing it breaks something else.

**Comment by rouletout** [comment]
Fixed with release 88

**Comment by FreddieChopin** [comment]
Thanks!
