### ISSUE TITLE
Sector name in overview topo does not update

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3730]
**What happened?**
I have changed the main name of a sector from "Arabe Loco" to "Modo 9".  The previous name, "Arabe Loco", I added in the "Alternate name" field. I then realized that the overview topo label had not been updated accordingly. Hence, I removed the alternat name, "Arabe Loco" completely. However, the overview topo still shows the old name.

I have unlinked the respective sector and added it back in. Still, the drawn yellow box was put in place with the same old label automatically.

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/spain/jerica/topo

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/87927319-52637e00-ca83-11ea-817e-48b94113be74.png)

![image](https://user-images.githubusercontent.com/30682796/87927432-79ba4b00-ca83-11ea-9775-fae7bcda77c9.png)

**What you expected:**

* Overview topo labels are updated and in sync with the main sector name.

**Comment by killakalle** [comment]
Okay, I've just discovered that there is a label override. Through that, I was able to fix the issue on that crag topo myself.
![image](https://user-images.githubusercontent.com/30682796/87941737-dd507280-ca9b-11ea-8f6a-dc796a59f467.png)

I still don't find it intuitive that the label was not updated in the first place. Though, it's probably a bit of an edge case anyhow. With the given workaround/solution seems good enough.

**Comment by Mdemaillard** [comment]
@killakalle 
Thanks for reporting the topic and finding out some workaround.
I believe it is very probably due to some cache taking some time to propagate from the input (area edit process) to all the usages.
Some data is stored at mulitple places in cache to optimize serving the data: in multiple cases it take a few days before an edit reflects in some aggregated graph or counter, or propagate through the index. That could be one as well.
