### ISSUE TITLE
filtering routes by "dry in the rain" gives wrong result

### ISSUE THREAD

**Issue by ipesando** [theCrag/website#3743]
**What happened?**

https://www.thecrag.com/en/climbing/austria/area/518688360/routes/with-grade/AU:1:39/in-setting/natural/?sortby=at,desco 
and you get 423 routes
then filter all routes "dry in the rain" from structured tags and you get 5 routes only which is wrong.
For example you miss 
https://www.thecrag.com/it/climbing/austria/route/276057519 that is in the area.

**Comment by rouletout** [comment]
This is due to the fact that you can't search structured tags in correlation with routes iof the tag is not on the route (so in that case the dry in the rain tag is on the area, which makes sense). This is purley a server load restriction. If you PM me I can show you how to modify the query that it still gives you the info you need.

**Comment by rouletout** [comment]
Same as https://github.com/theCrag/website/issues/3702 closing.
