### ISSUE TITLE
Search does not update on changing Index when language is Spanish

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3771]
**What happened?**

To reproduce:

1. Start a search https://www.thecrag.com/es/escalar/spain/valencia/areas/at/102880932/of-area-type/170979691/?sortby=at,desc
2. On the left-hand index click on `Castellon Area`

Observe that the URL changes, however, the search stays the same.

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/areas/at/102880932/of-area-type/170979691/?sortby=at,desc
https://www.thecrag.com/es/escalar/spain/castellon/areas/at/102880932/of-area-type/170979691/?sortby=at,desc
https://www.thecrag.com/es/escalar/spain/costa-blanca/areas/at/102880932/of-area-type/170979691/?sortby=at,desc

Ideally also provide screenshots:

URL changes, but search content remains unchanged
![image](https://user-images.githubusercontent.com/30682796/96193633-d923dc00-0f48-11eb-8df7-c6254184f9b2.png)

**What you expected:**

* [ ] Changing the area in the index also reflects on the search content

**Comment by rouletout** [comment]
Yup, this is in the queue :-)

**Comment by scd** [comment]
I have looked into this and the `at` search filter should not be in the url. However the url language update regressed facet search so it always appeared in the url. I have fixed this in dev, please wait for next release.

Note that in testing the urls in this card should not be used because they were generated in error in the first place.

**Comment by rouletout** [comment]
Solved with release 88.
