### ISSUE TITLE
Lists, Search and filter list-entires same way as for ascents.

### ISSUE THREAD

**Issue by FredrikEckardt** [theCrag/website#3906]
I would like to search and filter my list entries in the same way as I can search and filter my ascents. 

The old ascent-types hit/mark/target were, on one hand annoying due to the fact they were not ascents. (Visible for all, included in stats ...) But, at the same time, the fact that were "ascents" and that they had all the ascent functionality, such as search and filtering, actually made them very powerful. 

I have previously used ascent type target to mark routes that> 
1. I have tried but not finished. 
2. I red supposed to be good. 
3. Marking possible routes (and indirectly crags) for future trips 
4. more 

The old functionality allowed me to easy find, sort and filter that I miss when replacing them with lists.

**Comment by scd** [comment]
This is a good suggestion, but solved in a different way to how you suggested. I think I want lists to be a little inert in themselves and have a defined order just like the list of routes are in a sector.

Instead we want to link the lists functionality into the routes search so we get all of the routes search features for free. I have just hot fixed this so that you can construct the search via the url. For example my wish list:

https://www.thecrag.com/routes/of-list/4751379870

I will have a quick look at some nav improvements as well.

**Comment by scd** [comment]
You can navigate to this via the list header

<img width="818" alt="Screen Shot 2021-05-17 at 2 12 45 pm" src="https://user-images.githubusercontent.com/373058/118432030-f4430e00-b71a-11eb-9073-f7b13779d7c8.png">
