### ISSUE TITLE
Attribute/field "guidebook" for areas/regions/crags

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#396]
This field could hold information that helps users to find a guidebook for the selected area. Thus, it should also be "inheritable" (is that a word?).
Second step would be a rating system, where users could comment on and rate guidebooks.

**Comment by brendanheywood** [comment]
+1 from related discussion with Kai

**Comment by brendanheywood** [comment]
See discussion (from #1562):

http://www.thecrag.com/discussion/529788180/publication-guide-books

**Comment by brendanheywood** [comment]
+1 via duplicate from https://github.com/theCrag/website/issues/3517

@lordyavin if you close something as a duplicate please add a +1 like this ^

**Comment by gui84** [comment]
What about letting users just add simple reference of one guidebook (different from the existing administrative function) ?

**Comment by matozoid** [comment]
-1 because @gui84 asks a different question than #3517. Currently links to guidebooks end up in the description field in many crags. Which may be fine.

**Comment by brendanheywood** [comment]
This issue and #3517 look the same to me, I don't understand the -1

Anyway, I think in the short term, just a url for another guide book is fine and for the foreseeable future that's all we are likely to support, this one is a long way down the todo list. Of course our general preference is wherever possible to have the information inside theCrag but that's not always pragmatic. It is also nice for historical reasons to reference a guidebook, eg ones which are no longer in print.

**Comment by lordyavin** [comment]
@brendanheywood, you are of course right that the information stored in theCrag should be as complete as possible. Furthermore, I think that we have a certain responsibility towards the publishers and authors of printed climbing guides. In contrast to Australia, the European entries are mostly based on information from the guide books (presumably). So we should at least refer to the books and offer a link where you can order them. This is the least we can give back. To be honest, I find it bad that this aspect receives so little attention.

**Comment by brendanheywood** [comment]
I don't see how Australia is any different, we have plenty of guidebooks here too. But to be crystal clear, zero content should come from guidebooks, unless there is specific permission or license granted. Any links that are added are for the benefit of climbers looking for good info, not out of any obligation or responsibility to any guidebook author. I'm fine with adding links to other online resources which can help climbers on the spot. I'm not fine with blatant promotion of other guidebooks, if they want they can buy an ad with us for that crag. There is a lot of gray area in the middle, like promoting a small local guidebook which is linked to a bolting fund is good.

**Comment by gui84** [comment]
I think it's for the benefit of climbers to promote local printed guidebooks (and not commercialised rockfax styles guidebooks) who support community and local bolting. We should be allowed to add a quick reference (title, author, year of issue and sometimes where to buy it). It's fair to route setters involvement.

**Comment by killakalle** [comment]
I support the idea of a dedicated area/field/etc for (local) guidebooks. Local guidebooks - however inefficient - often contribute to local (re-)bolting. So, advertising their existence, their purpose and where you can get them should be of interest to climbers and bolters alike.

**Comment by rouletout** [comment]
The way to handle the support of local bolting and maintenance on theCrag is via advocacy groups. While it is typically unclear who benefits from a guidebook (if there is benefit at all) a legitimate regional or local advocacy group can advertise for free on theCrag and make use of more features if interested. We kindly ask you to refer local advocacy groups to this page: https://www.thecrag.com/en/article/advocacygroups and get in contact with us.

That being said, a textual reference for a guidebook in the description is ok and useful for visiting climbers and not discouraged!

**Comment by georg-d** [comment]
**As guidebook commission is a potential revenue stream, I wonder if we could do it soon to fund improvements of the site.** Edit: For more detail, see https://github.com/theCrag/website/issues/396#issuecomment-1102957364

> So I will interpret your request as a 'I didn't even knew we have this cool feature' which means we need to do some work to make it more visible and clean it up a bit. I too think the ratings would be good along with a way to just buy it on the spot with commission etc if possible.

+1 for making it more visible (e.g. a link in "Plan your Trip" section of a crag, maybe telling how many guidebooks exist) and add a rating (IMHO ideally, numeric rating plus a text area to explain the rating)

> I'm not even sure how the data gets in there anyway, I'll follow up with the other guys.

Did you find out how we can add guidebooks/publications?  I assumed a cue in publication page or at least in https://www.thecrag.com/en/article/documentingacrag but did not find it 😞 Edit: Answer in https://github.com/theCrag/website/issues/396#issuecomment-942602090

I'd expect the possibility to enter an ISBN which will trigger automatically filling the other fields (title, edition, month+year, author(s), publishing house, image of cover, language(s), URL to more information) as far as possible – and if I do not have an ISBN, I can fill the other fields manually. Additionally, a free text field would be great to e.g. tell what changed compared to older releases or where to get guidebooks that are home made with a copy machine and available in a bar, hotel, tourist information or the like. Especially for those home made guides, please make no field mandatory, because these guides may neither have a ISBN nor title nor publishing house nor creation year...  IMHO we do not need a feature to copy existing entries, because a new release needs so few fields in total, that it's not worth the implementation effort of a copy feature – which additionally carries a considerable risk that some data is unintentionally taken over from the source guide book.

Do you think it's worth to add a guidebook feature listing all single routes and allowing to tick a checkbox at individual routes that are covered in the guide book, and vice versa? That is quick to do for users (especially with a "select all" button), it is probably quick to implement, and it may help to easily select "the right" guidebook (e.g. the one that covers the right areas/cliffs, that contains sport / trad / boulder ... routes, hard or medium or soft routes,...) Edit: Same question covered in https://github.com/theCrag/website/issues/1447

Edit: I do not know the current data model. I consider it highly important that guide books are entities on their own, so not children of a certain crag or region, because only that independence makes many other things easy & efficient – e.g. it allows to easily link an existing guidebook to a crag instead of needing to re-enter all the same data, to quickly update or extend a guide book instead of doing the same edit at each of some dozens of crags, to have one common discussion forum for a guide book instead dozens of scatterd parts,...

**Comment by georg-d** [comment]
Could anyone explain how we can add guidebooks/publications to an area?

**Comment by rouletout** [comment]
This can only be done by admins based on an agreement with the publisher.

**Comment by georg-d** [comment]
@rouletout Thank you for the input :) I digged a little deeper and found in a related issue @scd [wrote 2014](https://github.com/theCrag/website/issues/1447#issuecomment-42367025) **_"The biggest issue ... is to only add guidebooks to areas if a publisher asks us. We need to re-address this, so that anybody can add a guidebook."_ which is IMHO very true because the current approach did obviously not work out well in real life:** After at least one decade existence of the guidebook feature, theCrag effectively refers only a tiny fraction of all guidebooks. More tangible: "Guidebooks" page was empty in the ~30 areas of my sample - but guidebook information was sometimes existing in other, user editable fields. 

Why change the approach of requiring an agreement that has to be requested by publishers?

- Most content in theCrag is user crowd sourced and that works fairly well, so I see no reason to stick with another, mostly dys-functional sourcing method for guidebook references.
- Users _want to add_ that information: They add guidebook information in other fields like description, ethics, or history. They start forum discussions. They create/comment gitHub issues (see linked issues). 
- Climbers are currently finding void on theCrag concerning which guidebooks exist and the pro & con of each of them. So, theCrag forces climbers to move on - while websites usually try to keep users on the site.
- With current process, climbers cannot get a book review _from user perspectice_, because users cannot contribute to guidebooks but only publishers - who will not tell something like _"the new edition did not correct most errors and did not add the newer routes, so you can happily stick with your older edition"_
- Except for the cover photo, I do not see a legal, ethical or practical reason why a publisher shall be asked to agree that his book is referenced on thCrag: The publisher does not have an disadvantage of the book being mentioned in theCrag; it's more an advertisement shown to the very specific target group (people interested in climbing _and_ the relevant area). A book's meta data is public anyway, e.g. can be fetched at central library in several countries, at book stores,... There's no sensitive personal data published like age, contact info, payment methods, private address,... and names are obivously not considered sensitive, as we do publish First Ascent without requiring a request by the FA.
- For books that are _out of print,_ theCrag will virtually never receive _a request by publishers_ to add that book, because the publishing house may not exist any more, or sees no advantage in taking  action for a book that is out of print,... Thus, such historic information will virtually never make it into theCrag, but it carries some value, e.g. climbers know what guides existed which makes it easier to search for a used copy, it makes it easier to realize in which of the guides of your shelf you might find a crag (e.g. "plaisir" guides often cover a huge region but do cherry-pick only very few crags or even only sectors), you quickly see where you can look up historical development of a crag, if we use structured fields we can also look up activity & development publishing houses, authors, etc relevant for climbing,...
- For books that _still are in print,_ the adding process is oviously interrupted somewhere and I can't tell where, e.g. whether publishers are not even aware they could approach theCrag admins, or publishers do not want to approach the admins (e.g. because they see no benefit), or the request does not reach the admins, or the admins do not process the request, or the process starts but admins require "too much" in the eyes of publishers (too much data/work/money/...), or the process starts but starves due to current technical implementation (UI design, logic or DB problems,...), or whatever else. IMHO it's not really relevant _where_ the current process is interrupted, but only _that_ it is interrupted and thus theCrag does not have much guidebook references.
- Current state of "guidebook" feature is far away from https://www.thecrag.com/en/article/vision e.g. _"being the market leader with respect to user satisfaction, data quality, completeness"_
- Last but not least, a better working "guidebooks" feature is a potential funding source for theCrag (commission for each sold copy)

**Comment by lordyavin** [comment]
@georg-d I totally agree

**Comment by georg-d** [comment]
@rouletout as to my understanding, you're setting the prio of issues. **What do you think of prioritization of guide book feature's redesign to help funding theCrag improvement?** 

Motivation: When looking at issues, many are open for years and I repeatedly read they're not implemented soon due to lacking development resources, e.g. https://github.com/theCrag/website/issues/2584#issuecomment-1099923290.  Attracting developers and organisations donating developing time is IMHO much more difficult for a climbing website than for an open source tool that is critical (e.g. KeePass, Linux) or that DEVs use for DEV purposes (e.g. git). Hence, I've the impression increasing the funding to buy / free up development time may be a more promising path.

**Way of funding:** As briefly mentioned in both of my longer comments above, **allowing users to maintain guide books and displaying that information easily findable as affiliate marketing links (e.g. to Amazon) could help to fund theCrag – without nagging users, without requesting users to spend more money than doing anyway, but instead by extending the information richness & feature set of theCrag and thus making life easier for users, e.g.** 

- it's easier to find guide books for a given crag or sector or even a single route (routes are mainly interesting for cherry picking books like the "plaisir" which are common in & around Switzerland, or "only multi-pitch in grade X", or "only _bolted routes_" where it is uncommon like Pfalz, Sächsische Schweiz,..., or "only DWS" or...)
- it's easier to see what crags / sectors / routes are covered in a given guide book, as a simple listing (reuse of search function) but potentially also on the map – while many guide book covers / back-covers / descriptions only provide a rough content overview
- it's easier to understand what crags / routes are covered by all the guide books one owns, so to to discover "holes", "duplicates" or "updates" – or just to decide which of the books to take for a trip.
- it's easier to buy guidebooks when preparing a trip or while logging ascents (2-3 clicks will be enough when the affiliate partner offers a book and not only special organizations like a local tourist-info/club/bar/hotel/... sell them)
- depending on implementation, it could become easy to get reviews & recommendations on guide books from user/climber's perspective (see my comments above)
- it's easier to research the timeline / historical development of a crag or region

As a positive side-effect, theCrag will be found in more web search queries – potentially all searches with terms related to guide books – and thus may attract additional users.

**Potential funding value:** A quick research on the web revealed around 5% commission are usual. Many paper guidebook cost 15€-60€, for digital ones it's more complex (cheap topos for single sectors, ongoing subscriptions etc), so for this quick & rough calculation, let's stick to paper and assume an average of 35€ per book. Because I do not know how many unique visitors theCrag has, I estimate very pessimistic, i.e. that theCrag has only the really low ratio of 1 active account per 100 unique visitors per year (other crowd sourced sites have dimension 1:10,000), there are around 18,000 [registred users with Karma in last year](https://www.thecrag.com/climbers/after/2021-04-19/using-stat/karma/at/7546063/). Let's assume 0.5% of visitors use an affiliate link for only one of their purchases in a whole year. So the rough calculation is 5% x 35€ x 180,000 x 0,005.
**→ My assumptions result in roughly 15,000€/year – scaling up linear by higher amount of visitors (which is quite likely) while required efforts & resources are growing much lower. So it seems realistic that even a relatively high effort implementation of the feature will pay off within around one year.**

As potential downsides, only these came to my mind

- We over-estimate how much the feature supports the funding, e.g. because people want to support local shops and buy guide books there instead via theCrag affiliate links, or users do not enter the data, so the feature renders mostly useless. IMHO even a lower funding by this feature is still a funding for theCrag, so it's not harming but just not as helpful as hoped. And as written in above comment, IMHO users seem to want to add that data, and because I expect linking a crag to a guidebook to be a quick action, very few motivated users are sufficient to provide a useful data quantity & quality.
- We under-estimate the effort, e.g. because affiliate partners change their APIs often, many different affiliate partners are required to cover the different regions of the world, the complexity of the data model or GUI turns out much higher... IMHO unlikely because affiliate partners have an interest to minimize the barrier to use their partner programs and because we are free to choose an 80:20 approach (focus only on few partners that support most regions) and we already have a data model & GUI for guide book so have less uncertainty/risk than for completely new features.
- We introduce a target conflict: At the one hand, theCrag wants to provide useful, complete & quality information – which IMHO does also cover routes, topos and meta information like approach, orientation, kid friendliness,... reducing the desire for other information sources including guide books. On the other hand, the less routes & topos & meta info are in theCrag, the higher the potential guide book sales via theCrag, the higher theCrag's potential funding. That target conflict is IMHO marginal, at the one hand because by intention having less info in theCrag makes users move to other websites, and at the other hand, other factors are affecting sales of guide books much stronger, e.g. lacking availability, lacking translations, personal preference, mega-trend digitalization, etc. (see also e.g. discussion [Alternatives to support crag development and bolting](https://www.thecrag.com/discussion/3322830909/alternatives-to-support-crag-development-and-bolting)).
- We run into regional legal issues, e.g. a cover picture shows a lady's uncovered ankles or shoulders which is forbidden in some countries. IMHO irrelevant as we already have that risk with all other photos on theCrag – and especially for guide book covers, is even more less likely to materialize because the cover is reviewed by affiliate partners & publishing houses while other user uploaded pictures are not reviewed by anyone.

The anticipated feature may be extended in the future, e.g.

- for a single guidebook, a discussion feature. Probably it's easy to re-use existing discussion feature of crags, activities,...  including notification feature (dashboard entry, email etc) so it becomes possible to ask other users, to get news like "the announced book is on the market now!"
- <del>for a single guidebook, feature to crowd source a collection of errata & updates.</del> To be truely useful (e.g. how a route line changed), this would require photos of the inside of the guide, which poses bold legal questions (copyright etc).
- for a single guidebook – especially those that are out of print – a dedicated feature to report interest to buy it (so publishing houses can estimate demand for a re-print or a new edition), and via discussion feature also to sell or lend/borrow it 
- users could create a list of their owned guide books. This could automatically activate a subscription/notification of the discussions on that guide book. A crag/sector/route page may highlight these owned guidebooks in the list of guidebooks, so it's easier to spot where more info can be found.

**Comment by lordyavin** [comment]
bump

**Comment by georg-d** [comment]
**All of the aboved is obviously feasible as it _is done in practice_ :**

[ClimbingAway.fr](https://climbingaway.fr/fr/voyager/topos-guides-escalade/escalades-autour-d-annecy) links crags with guidebooks. For a guidebook, you can see the crags it covers, and for a crag, which of the guidebooks cover that crag. That is really useful – in general, but especially in context of cherry-picking guidebooks like the infamous "plaisir" series by filidor ([example](https://www.filidor.ch/de/kletterfuehrer/schweiz-plaisir-ost)) and "week-end" series by Jingo Wobbly ([example](http://www.jingowobbly.com/ROC2/ROC2-main.html)). 

Moreover, ClimbingAway.fr does set affiliate links. While extensively using their site during a research, it showed amazon is a well-known supplier with huge amount of articles but _for topo guides_ not nessecarily the best choice:

- e.g. https://climbingaway.fr/fr/voyager/topos-guides-escalade/bornes-aravis is not at all listed
- e.g. https://climbingaway.fr/fr/voyager/topos-guides-escalade/escalade-en-savoie-tome-1 not available
- e.g. https://climbingaway.fr/fr/voyager/topos-guides-escalade/falaises-et-via-ferrata-en-vanoise-et-beaufortain costs 77€ which is _way more_ than the usual 23€

In contrast, the online shop [kletterfuehrer.net](https://www.kletterfuehrer.net/ ) is specialized in guide books, has a very good coverage (at least all across Europe), an astonishing share of articles is in stock, and ships worldwide. Moreover, it is a small shop run by climbers, which is not surprising seeing their target market 😉 but makes them more sympathic than amazon. All in all, it seems to be a perfect matching partner for theCrag, at least for Europe because of high shipping costs to overseas.

**Comment by rouletout** [comment]
@georg-d thank you for all the thoughts and the write up - very much appreciated. While I think that the economic estimates are a bit on the positive side (we have experience with other affiliate offerings) I agree that this is a gap we should fill. We will have an internal discussion and get back to all of you here....

**Comment by rouletout** [comment]
Implemented in release 101 as an admin function but better exposed for users in the Plan your Trip section, closing
