### ISSUE TITLE
Route History Fields - consider adding First Female Ascent (??)

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3974]
**What happened?**

This is up for discussion if this is a thing we want to have or not. We would appreciate community feedback on this one.

Ideally also provide screenshots:

**What you expected:**

**Comment by rouletout** [comment]
See here for feedback: https://www.thecrag.com/discussion/5313018441/female-first-accent-addition

**Comment by rouletout** [comment]
Changed name of issue to reflect the result of the discussion from "consider adding First Female Ascent".

**Comment by lordyavin** [comment]
As I stated in the linked discussion I think the current website features are sufficient. If any notable ascent took place there is the description field, the route history entries, ticks and discussions.

I would not introduce gender specify UI because that leads to development and maintenance efforts that I don't believe it is worth for.

**Comment by rouletout** [comment]
Notable Ascent is now available, closing
