### ISSUE TITLE
Tick icons mis-positioned in activity/ascents stream

### ISSUE THREAD

**Issue by p00ya** [theCrag/website#4078]
Recently (last couple of weeks, possibly coinciding with [Release 98](https://www.thecrag.com/discussion/6084829995/release-98---new-tick-flow-part-4)), the tick icons for ascents started appearing on top of each other and the climber avatars, rather than next to each ascent.  See:

![image](https://user-images.githubusercontent.com/15805/171992926-3b1e146c-32c4-4e4e-93c7-766a8d9351bd.png)

This makes it very hard to tell which tick applied to which climb when viewing activity for a node or climber.

Browser: Chrome 102.0.5005.61

**Comment by scd** [comment]
It is fixed in dev.

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
***@***.***
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Instagram <https://www.instagram.com/thecrag_worldwide/>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by killakalle** [comment]
Maybe related? Logged with new ticking interface.

![image](https://user-images.githubusercontent.com/30682796/172956628-79753ca3-f3df-4116-810e-84ec7b398fd9.png)

**Comment by rouletout** [comment]
All fixed with latest release, closing
