### ISSUE TITLE
New tick flow - No points assigned for certain tick types, wrong points assigned for others

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4128]
In the new tick flow some tick types produces wrong CPR points, while others don't produce points at all.

Reproduce

Situation A - no points assigned
- With the new tick flow, log a route as "Seconding" + "Flash/whatever"
- Look at your ascent list and deselect all CPR types
- Scroll to the bottom of the list

Actual: In new tick flow,  certain tick types are not awarded any points
Expected: In new tick flow, all tick types are awarded points

![image](https://user-images.githubusercontent.com/30682796/199024193-19e9103b-fe65-4739-8683-c1a94147d7df.png)

Situation B - wrong points assigned
- With the new tick flow log a route as "Top rope" + "Flash"
- With the new tick flow log the same route as "Lead" + "Flash"
- With the old tick flow log the same route as "Toprope Flash"
- Compare the points awared to each ascent

Actual: In new tick flow, Toprope Flash and LeadFlash are awarded the same points
Expected: In new tick flow, Toprope flash is awarded less points than Lead Flash

![image](https://user-images.githubusercontent.com/30682796/199027185-523da6f8-4251-448b-b18d-0628ff3aa050.png)

Could be related to #4127

**Comment by rouletout** [comment]
Top Rope or Second should not get any points.

**Comment by scd** [comment]
@killakalle thanks for finding this one. It is definitely something that was missed. I have made some changes and released so that we should have more sensible behaviour with some of the edge cases you mentioned. I am sure that there will be subsequent issues and some in depth consultation with community.

**Comment by killakalle** [comment]
@scd 
I've just re-logged the Flash ascents done in toprope and seconding. They now show fewer points than before. So, intuitively this looks good.

I've also re-logged another ascent that was Hangdog - Seconding. This one now receives more points than before. Just wondering if this is correct.
![image](https://user-images.githubusercontent.com/30682796/201615725-092b8638-9a0e-4e57-b22c-438069d932fd.png)
![image](https://user-images.githubusercontent.com/30682796/201617854-b0a180cc-5bf1-458c-acb1-03a91b3df10f.png)

https://www.thecrag.com/ascent/6832304691


I found an old ascent of mine where I also climbed a 7a as a second and logged Hangdog. The points then were significantly lower:
![image](https://user-images.githubusercontent.com/30682796/201617332-18654937-277b-46c4-9a56-beaea40aa15d.png)
https://www.thecrag.com/ascent/2684585151

**Comment by killakalle** [comment]
@scd @rouletout Cold you please reopen this issue. The CPR currently still looks incorrect to me.

Yesterday I've climbed a 7a twice and the following points were awarded:

- Lead, Handdog: CPR tick shift 2151 (-650 punto)
- Second, Hangdog: CPR tick shift 2601 (-200 punto)

It looks wrong that seconding a route gets a lot higher points than leading a route.

The ascents:
https://www.thecrag.com/ascent/7137608247
https://www.thecrag.com/ascent/7137657747

There is meanwhile a similar/same issue raised elsewhere:
https://github.com/theCrag/website/issues/4142

**Comment by killakalle** [comment]
Maybe related:

I've climbed the following route twice in different sessions:
https://www.thecrag.com/es/escalar/spain/castellon/route/1450892985

- The first session was in top rope (seconding) and I flashed the route.
- The second session was in lead and I pinkpointed the route.

Arguably, the lead ascent is more "valuable" than the top rope ascent. Thus the icon should show the pink point lead ascent. However, it does show the top rope flash ascent 

![image](https://user-images.githubusercontent.com/30682796/220049010-4898e744-be00-4f14-bc63-557dd27ae4da.png)

![image](https://user-images.githubusercontent.com/30682796/220049977-d7946d3f-bc57-4d3f-80e9-21a2c38e2c41.png)
https://www.thecrag.com/es/escalar/spain/castellon/route/1450892985/ascents/by/killakalle

**Comment by killakalle** [comment]
Another screenshot that illustrates the problem well:

- Same route
- same day
- same style
- different tick  -> still the same points are awarded

![image](https://user-images.githubusercontent.com/30682796/220458661-ee347d02-e42e-4d0f-aa3c-919450e899b1.png)

**Comment by scd** [comment]
This is definitely on the list of things to fix.

**Comment by dnnr** [comment]
I'm not sure if this is tracked elsewhere but it seems related: Second flash get misrepresented in other places, too. For instance, under Notable Ascents by Area, a second flash might show up as the hardest ascent for the area. I suppose that's intended, but there is no way of telling that it actually isn't a lead flash. Similarly, the candlestick chart for CPR indicates a hardest redpoint grade even though that grade was only achieved while seconding.

This probably has been discussed already, but overall I'm really not sure why the new tick flow records second ascents using the _second_ tag. It seems to be causing all these bugs and problematic visualization artifacts. I appreciate that the new tick UI acknowledges the orthogonality of the lead/second/toprope axis and the onsight/flash/redpoint axis. I think I even suggested that years ago. But outside of the ticking UX itself, I feel there was never anything wrong with showing tick types like "second flash" with their own icon, instead of "flash ascent, tagged as second, but sometimes we just hide the tag so you never know".

**Comment by scd** [comment]
I have fixed the dog issue. It will not apply to already logged ascents until we do a full CPR recalculation. You can force a single ascent recalculation by updating the ascent.

Yes all non trad/sport/boulder ascents in the new tick flow currently have the same CPR. This is partly because we did not do rigorous stats on these but also because we have not got around to looking at what could be a logical approach. It is not urgent because CPR outside the Trad, Sport or Boulder styles does not really do anything. There are no Second CPR charts for example. 

Just so you know the plan is to look at the non-standard CPR values after we have closed down the old tick types. There are just too many moving parts right now. 

For interests sake I used the new tick interface to Tick and Clone 16 different gear style / tick type ascents. Here are the results:

<img width="490" alt="Screen Shot 2023-09-04 at 4 50 35 pm" src="https://github.com/theCrag/website/assets/373058/84617f3e-4fa4-484d-bcb4-b346f93d4e1d">
