### ISSUE TITLE
Merging of routes results in "double grade"

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4153]
To reproduce:

1. Merge two routes with a different grade (both routes are French sport)
2. Look at the grade of the merged route it has a "double grade" -> 6a 5+
![image](https://user-images.githubusercontent.com/30682796/208428029-b5b9cd91-436b-44fc-8e1b-3e10d34f8d7b.png)
![image](https://user-images.githubusercontent.com/30682796/208428156-0880d366-1aa1-4216-8b0e-5e5469507950.png)

3. Edit the route and look at the grade field (Only one of the grades is shown)
![image](https://user-images.githubusercontent.com/30682796/208428251-8ca0acb5-4602-4a0c-a65d-02fe7f3a8189.png)

4. Save the route (without changing the grade)
5. The grade remains as a "double grade"

PS: During merging it does not offer to select one of the grades. I think this was part of the workflow in the past.

Workaround

1. Edit the route
2. Change the grade to something else and save
3. Edit the route again and set the grade it should have
4. Save

Now the correct single grade is shown.

![image](https://user-images.githubusercontent.com/30682796/208428904-c7cd6c27-b774-4b29-bcda-557cfcc65aa8.png)

For reference:
This is the stream event
https://www.thecrag.com/event/6976372443

**Comment by lordyavin** [comment]
Did this happen more than once?

**Comment by killakalle** [comment]
This happens frequently (every time?) for me.

**Comment by lordyavin** [comment]
Can not reproduce. See https://www.thecrag.com/en/climbing/test-area/area/7049575470

**My steps**
1. Created test area
2. Created route 1 with grade 6a
3. Created route 2 with grade 7a
4. Merged routes and (on the preview of the merged data) changed registered grade from grade range 6a-7a to 6b+

For this scenario it worked as expected.

**Comment by lordyavin** [comment]
Tried it a [third time](https://www.thecrag.com/climbing/test-area/route/7049617440) without luck. Merge operation seams to work as expected for this artificial examples.

But I discovered,that the automatic grade conversion each user may configure does not display the grade range.

![image](https://user-images.githubusercontent.com/1528540/210653139-64365ff7-e3de-4646-bdde-cfc92ddc5909.jpeg)

![image](https://user-images.githubusercontent.com/1528540/210653182-e01ed7ba-dd78-4689-b3f8-b8f364a0edad.jpeg)

**Comment by killakalle** [comment]
To reproduce:

1. Create route 1 with grade FR 5
2. Create route 2 with grade FR 6a
3. Open route 1
4. Merge with...
5. Select route 2
6. Confirm

Result:
https://www.thecrag.com/climbing/test-area/route/7065104727

**Comment by lordyavin** [comment]
Okay, I can reproduce the issue if exactly repeat your steps. Note that the error happens even if using the context menus merge entry of the route list.

I'm pretty sure the issue is cause by the French grade "5" which isn't supposed to be a valid French grade according to ["Trad and sport grade systems"](https://www.thecrag.com/en/article/grades#trad-and-sport-grade-systems). I believe the system recognizes the 5 as an UIAA grade for example (or any other grade context that my be valid) and adds the 5 as an alternative grade. Therefore the result of the merge does not show a grade range but a combination of to alternative grades. Why the editing UI hides this detail is beyond my imagination ;-)

@scd I recommend to close this issue as "won't fix"/"not a bug" as it looks like to be an edge case that is caused by wrong user input.

**Comment by lordyavin** [comment]
BTW: There is no way the system can automatically choose the correct French grade.

**Comment by lordyavin** [comment]
@killakalle any opinion on my last comments? Can we close the issue?

**Comment by killakalle** [comment]
@lordyavin 
The particular issue of merging 5+ and 6a routes is probably not that much of an issue then.

Though, there might be a bigger underlying issue with these "fake" French grades (, ..., 5, 5+).
They are widely used also in guide books. So, they seem to be an accepted French grade, even though the actual grading system would require 5b or 5c.

Another place where this issue manifests is the grade feedback
![image](https://user-images.githubusercontent.com/30682796/214041994-6f74ca7d-65a1-4399-a876-2d1a5cd7932e.png)

**Comment by scd** [comment]
Note that theCrag has a FR grading system (6a,6a+,6b,6b+,6c,6c+) and a FR_ALT grading system (4,4+,5,5+) because both grading systems are used. However when this was encoded the thing that we did not realize is that the defacto standard at the lower grades is to use the 4, 4+ and and the higher grades use the 6c+ system. So the standard system should have been a mixture of the two grading systems and the ALT should have been the inverse.

This is super hard to fix now and requires a significant data migration work to update. Even though I would like to fix this given our resources I don't think we will be fixing this anytime soon.

**Comment by killakalle** [comment]
Fine by me to close this issue if you prefer
