### ISSUE TITLE
No Ads for Supporters!

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#4168]
Recently the sidebar "Accommodations Nearby" were introduced and I really don't like to load ads that I don't want to see. The link "Find Accommodation" was totally sufficient and is an opt-in to get ads about accommodations.

In general I always loved it that theCrag had one or two static ad banners/images only. Now these ads are going to annoy me more and more. More bad that those ads potentially decrease the overall website performance and "hide" content of interest (e.g. photos sidebar).

So I propose to totally disable ads for supporters. 
Optionally provide a setting that supporters can activate the ads.

See the "Pur-Abo" subscription models of known publishers.

**Comment by Drazhar** [comment]
Hey

First of all I agree that supporters shouldn't suffer ads, because they give money anyway. Also the accommodations on mobile take a lot of screen space and bandwidth 😔

But I also think there shouldn't be any extras for supporters, because then the next step will be premium accounts and maybe even areas which are only visible for premium users. That was the main reason why I left 27crags in the past.

So maybe removing ads for supporters is fine, but it shouldn't be advertised to become a supporter to remove ads. It should be a nice side effect.

These are just my two cents!

Best regards
Philip

**Comment by quaestor** [comment]
Thanks @lordyavin and @Drazhar, I fully support this. It‘s basically an attempt to present ads as a convenience feature, which is however „convenient“ to a miniscule percentage of daily users. As @lordyavin put it: the link „find accomodation“ was totally enough. I share @Drazhar‘s thoughts about the subtle introduction of „premium“ accounts, though, so not promoting the lack of ads for supporters might be an idea.

**Comment by rouletout** [comment]
From next release on there will be an option for supporters to disable accommodation and / or guidebook ads.

**Comment by lordyavin** [comment]
I'm kinda excited

**Comment by lordyavin** [comment]
Works! Thanks

**Comment by nicHoch** [comment]
with the latest release you can now hide all ads as a supporter.

**Comment by lordyavin** [comment]
No release promotion for this feature? ;-)
