### ISSUE TITLE
New tick system showing useless tick types

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4182]
New tick system knows if the user has already attempted a route, so it should not show the options "On sight" nor "Flash"

![image](https://user-images.githubusercontent.com/17315806/222585014-5221ad09-c500-4c5b-8f0e-4ff350589a2b.jpeg)

**Comment by skomaroff** [comment]
Checking this sort of thing seems overly prescriptive and would introduce problems.
It isn't possible to tell from the information you've provided that you aren't logging an onsight or flash.

- You might be logging a dummy route such as those used in areas where online guides and route lists aren't allowed.  There is one route I have onsighted or flashed ~20 times as far as the data base is concerned. https://www.thecrag.com/en/climbing/united-states/farley-ledges/route/5341307790/ascents/by/gmkwk 
- You could be logging an earlier ascent than the one already recorded.
- The previous ascent might be one of the now deprecated aspirational ascents, e.g. https://www.thecrag.com/ascent/3779689734
- You may have lost enough memories since your previous ascent that it is effectively your first attempt.
- You may have previously retreated from the route without falling or weighting a rope.  It's controversial, but some consider this an acceptable way to preserve an onsight attempt.

**Comment by rouletout** [comment]
Thanks for answering - this would have been our answer almost word by word - while we try to discourage user mistakes when entering data, theCrag is not intended to be a police system. If you wish to log 2 onsights - do so - you migt be challenged by the community on it but we don't want to forbid it - closing
