### ISSUE TITLE
Missed 2nd description field in ACA merge

### ISSUE THREAD

**Issue by scd** [theCrag/website#423]
OK, this is something I did not see, ACA has two 'Description' label fields:
http://www.climb.org.au/index.php?page_id=10&action=route&route_id=2046

(I love it how we can just click on a link on thecrag route page to go to aca route page).

To be honest, with the months of work I put in this I did not notice duplication of the 'Description' label, so my algorithm just got the first instance.

How common is this in ACA? It's a little bit irratating actually because to fix it is either a manual cut and paste or reparsing the whole ACA and working out which descriptions need updating. It's possibly over a weeks work to make this happen, but it would have only been 20 minutes work if I caught it before the merge.

I'm in the middle of other stuff right now so it will be a while before I can automate anything. The long term plan is to have regular data merges to capture ACA updates, so climbers can add stuff to whichever database they want. When this is implemented the problem will just go away.

I'm bad ): but this merge was extremely complex and our first one. This is the second issue which I wish I caught before the merge.

Anyway, well spotted Will. I would certainly appreciate any advice on a way to resolve this issue, but it will have to be tempered with our internal resource issues.

Simon

On 8/12/2011 4:41 PM, Will Monks wrote:

> Hi guys,
> I notice the import of route info from ACA seems to have missed the main route description field. The general info and "Start" fields have come across, but for example refer to Clean Sweep on Taipan, where the following text hasn't come across: "Aid on the bolts and jug R to the arete as for Dance of Life. From there climb straight up the grey faint groove with fantastic sustained moves all the way to the horizontal breaks, then directly up the excellent blunt arete."
> cheers
> Will

**Comment by brendanheywood** [comment]
@scd I've had a bit more of a think and look into this and I'm not sure it will be that hard to fix. I've written a fairly quick script which runs through existing ACA routes, go and regrabs the page, simulates what I think the old scraper did, and what it should have done. If the current state matches the oldscrape, then we should just swap it to the new scrape and were mostly done.

I'm not sure what else you did in the old scrape, it looks like you also wrapped known matching route names with ' so they get linked. We could simple just strip ' out when doing the comparison check, or possibly not compare and just use lastmod. Or post process to add the quotes and then compare (did you do other cleanup like markdown conversion for pitches?.

$ mysql  < routes-from-aca.sql | ./fix-aca-data.pl 
Hammer  --  http://www.climb.org.au/index.php?page_id=10&action=route&route_id=6779

CURRENT:    Up Sickle then step L to short ramp up shallow corner.\n\nStart: Start as for Sickle.
OLDSCRAPE:  Up Sickle then step L to short ramp up shallow corner.\n\nStart: Start as for Sickle.
NEWSCRAPE:  Up Sickle then step L to short ramp up shallow corner.\n\nStart as for Sickle.
ACTION: Update data
-----------------------------------------------------

Labouring the Point  --  http://www.climb.org.au/index.php?page_id=10&action=route&route_id=15809

CURRENT:    The original climb followed the upper roof-line all the way left until it ends at a short corner. An amusing concept that no-one can be bothered repeating. Stick to the first pitch as described.
OLDSCRAPE:  The original climb followed the upper roof-line all the way left until it ends at a short corner. An amusing concept that no-one can be bothered repeating. Stick to the first pitch as described.
NEWSCRAPE:  The original climb followed the upper roof-line all the way left until it ends at a short corner. An amusing concept that no-one can be bothered repeating. Stick to the first pitch as described.\n\nStart up Vanoise and, at about 15 metres move right onto the arete. Continue up to the upper roof line and rap anchor.
ACTION: Update data
-----------------------------------------------------

Clean Sweep  --  http://www.climb.org.au/index.php?page_id=10&action=route&route_id=2046

CURRENT:    For almost 25 years this route has largely been neglected due to a reputation for having a runout crux. In reality, it can be completely sewed up if you have plenty of micro-wires and a blue alien, and the endurance to hang around and fiddle them in. Plus the climbing is simply immaculate and, even despite the aid bolt, this must be a strong contender for the best 24 in the Grampians.\n\nStart: Start as for Dance of Life.
OLDSCRAPE:  For almost 25 years this route has largely been neglected due to a reputation for having a runout crux. In reality, it can be completely sewed up if you have plenty of micro-wires and a blue alien, and the endurance to hang around and fiddle them in. Plus the climbing is simply immaculate and, even despite the aid bolt, this must be a strong contender for the best 24 in the Grampians.\n\nStart: Start as for Dance of Life.
NEWSCRAPE:  For almost 25 years this route has largely been neglected due to a reputation for having a runout crux. In reality, it can be completely sewed up if you have plenty of micro-wires and a blue alien, and the endurance to hang around and fiddle them in. Plus the climbing is simply immaculate and, even despite the aid bolt, this must be a strong contender for the best 24 in the Grampians. \n\nAid on the bolts and jug R to the arete as for Dance of Life. From there climb straight up the grey faint groove with fantastic sustained moves all the way to the horizontal breaks, then directly up the excellent blunt arete.\n\nStart as for Dance of Life.
ACTION: Update data
-----------------------------------------------------

**Comment by Mdemaillard** [comment]
This looks like it was a one-time-only action to bootstrap content ?
