### ISSUE TITLE
Topos broken

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4232]
Open a crag with topo
![image](https://github.com/theCrag/website/assets/30682796/511b95df-b274-4fcb-9e19-1ef5139ed163)

Click on the topo to zoom in
![image](https://github.com/theCrag/website/assets/30682796/907094d4-5cd0-40a6-af6e-69846ee4b41e)

The topo doesn't load. Zoom out again
![image](https://github.com/theCrag/website/assets/30682796/e1c1ac72-fcac-4a4c-925c-314c78dc7096)

Topo remains broken.

Browser reload loads initially (zoomed out) topo again.

I tried on several crags, Firefox and Safari (on Mac). All with the same result.

**Comment by killakalle** [comment]
@nicHoch @scd 

Re-opening as this seems to be a general (recurring?) issue at the moment
![image](https://github.com/theCrag/website/assets/30682796/0889085c-1a25-4ddb-9f2c-a13cb63cb253)

**Comment by nicHoch** [comment]
@killakalle thx for the report we will look into this soon

**Comment by scd** [comment]
This was a totally different issue. We were unable to login to the server and we were also unable to get access to our hosting account. It looked like a network issue with out hosting provider during routine maintenance.

Yes we have a general issue we have been working through over the last couple of months. We are running out of disk space for a tmp directory which is required to serve images. I have been fine tuning the management of this disk space in order to avoid a large extra cost. Normally I will get daily notification if the disk is more than 85% full, but more recently this has been insufficient. I have put in place more aggressive management and have options to go more aggressive still but this slows down the server a little.

I am closing this card. By all means open it again when it happens again.

**Comment by killakalle** [comment]
@scd @nicHoch Thanks for looking into this. Unfortunately, this issue has already resurfaced.
This is also blocking the creation or editing of topos.
![image](https://github.com/theCrag/website/assets/30682796/0a8ad102-697d-491d-87ec-0f345cc235ec)

PS:
It seems I don't have permission to re-open this ticket.

**Comment by scd** [comment]
We did not turn off your permission, it must be github that did not allow persistent open/close. I reopened.

This is now happening with disk space available. I have found something else in the configuration that meant a more aggressive disk space clean could cause an necessary directory to be removed. This was a lurking bug which never use to come up but now does every couple of hours. 

I have put in place a fix. If the topo images are ok for the next couple of days then we can close this as fixed.
