### ISSUE TITLE
Refine stars algorithm (was "hidden gems")

### ISSUE THREAD

**Issue by cgome** [theCrag/website#560]
Ability to find high quality, low popularity routes at a crag (could be part of search, crag guru, crag stats, other?)

**Comment by willmonks** [comment]
Hi guys, just bumping my concerns from Dec 2014 about the thresholds. LOTS of "good" (42%-54% quality score) routes are still languishing with no stars in thecrag. 

This is also being noted by some other users - who agree that there is a direct correlation that "good" = 1 star, "very good" = 2 stars, "classic" = 3 stars. E.g. see the comments on these routes:
http://www.thecrag.com/climbing/australia/grampians/the-tower/route/15183319   
http://www.thecrag.com/climbing/australia/blue-mountains/western-tier-shady-side-lower/route/722745879

So I'd still really like to see the 55/62/72 thresholds for converting quality ratings to consensus stars changed to 41.6/58.3/75.  But I will go away again now ;)

**Comment by scd** [comment]
I think we agree. It is now just a matter of finding the time to fix. This fix is fairly high priority, but their are some other things that keep jumping in the way.

**Comment by willmonks** [comment]
Excellent, thanks!

**Comment by scd** [comment]
@willmonks I have made some updates to the star algorithm on our development machine dev.thecrag.com

See issue #2171 for discussion on the specifics of what has been done.

@brendanheywood please pull from repo

**Comment by scd** [comment]
I think this is done

**Comment by willmonks** [comment]
Thanks heaps guys. I think the algorithm is working exactly as it should.

I saw Simey complaining on Chockstone about thecrag "throwing stars around
like confetti" at Araps ...but when you look at the climbers' ratings of
the routes I think the algorithm is actually working perfectly.  If Simey
or any one person thinks a route is junk, but everyone else calls it "very
good", well, that's the exact definition of a 2 star route.

keep up the good work!

cheers,
Will

**Comment by scd** [comment]
Lucky I don't really read the forums, otherwise I might engage in some of these comments. 

The old system probably aligned with guidebooks more, however I think we can move on. Generally people hate change and we end up getting lot's of negative comments simply because it is different.

This is the way it will be done for the next couple of years. If somebody else wants to put in a compelling case to change it again after we have had sufficient time for the community to digest all the issues then we may change it again. But for now I think everything that was implemented was transparent, simple to explain and logical. @willmonks thanks for your investigation and input on this issue :)

**Comment by brendanheywood** [comment]
Thanks @willmonks , yeah I think it is working well too - however the one thing which now needs some more thought is the 'nearby icons' logic which leveraged this, now needs to be tweaked accordingly, see also #1456
