### ISSUE TITLE
Allow the ability to edit your conversation

### ISSUE THREAD

**Issue by adam-g-pullen** [theCrag/website#746]
While writing in a conversation i added more and more information as it came up, 

Each time i had to start a new "comment" It would be nice to be able to edit (delete maybe??) previously entered comments.

**Comment by scd** [comment]
I am sad to see Adam at the top of this issue every time I open it. 

This is partly implemented for standard discussion mode. MVP works.
 - [ ] UI for opening edit window
 - [ ] API for updating messages
 - [ ] If message has subject then this is edited as the first line
 - [ ] Version messages. 
 - [ ] Add message controls to indicate the message has been edited. 
 - [ ] Return ids to versions
 - [ ] Make sure this works in streams

**Comment by scd** [comment]
You can now edit your own messages from within the streams. In doing this I have also brought in the completions logic which was not being enabled for streams.

**Comment by scd** [comment]
- [ ] Note to self - finish of stream.js translations as I had to start this for the message editing.

**Comment by scd** [comment]
@brendanheywood this is mostly done. Can you pull and test on dev.

It could do with a bit of a UI tidy up, but I have lost momentum at this stage and am happy that all the functional components are in. Feel free to give it a once over, or we could just wait until the designer gives us an improved streams UI design. I don't care either way.

**Comment by brendanheywood** [comment]
I'm doing some minor ui cleanup now but I'll do a bunch more with the new design later.

I've also found a bug, if you are not logged in and reading a forum you cannot see the old versions

https://dev.thecrag.com/api/message/560509162?markupType=html&version=560509459

{"remote_ip":"x.x.x.x","args":"markupType=html&version=560509459","error":"You have insufficient access for the api endpoint '/api/message/\\d+', minimum level authweb","errorLabel":"insufficient-api-permissions","webSession":"61719f3d0fec846e2ab1eca69b05b8c9","method":"GET"}

**Comment by brendanheywood** [comment]
* [ ] Also should the poster be able to delete a message (as well as admin). How do you think this would work (if at all?) with the versions?

There is two semi related bugs:
* [ ] you get an error if you try to submit an empty string. This actually seems legit to me if you want to remove something. Maybe we show a 'removed' blank comment and still show the versions button so you can see what was there. But then sometimes the point of removing things is if you want it gone. So business decision? Facebook doesn't allow you to see history and you can delete stuff at will. Github doesn't keep history either.
* [ ] if you try to just add a normal comment which is empty it just spins

**Comment by brendanheywood** [comment]
If that api issue is a pain and needs some deeper work then lets just workaround it and remove that whole menu for anon people

**Comment by scd** [comment]
Fixed the api error if not logged in. 

> Also should the poster be able to delete a message (as well as admin). How do you think this would work (if at all?) with the versions

This already works but needs to be brought into line with the edit. To delete your own message go to the stream event and click on 'Moderate discussion'. Now that we have made the edit button available in the steams we should also make the delete button available there too. Maybe we can combine the edit with the versions and delete all in one menu. What do you think?

My view is that deleting removes the whole message and access to the versions as well. One of the reasons why you might want to remove a message is because it is defamatory, in which case you want to remove the versions as well. 

The behaviour of a deleted message is still transparent in that it will show that a message was there and has been removed. I think there may be inconsistencies in our UIs with this, but the transparency is what I want so it is clear a message has been deleted.

The reason why you want to edit is because you have made a mistake in the original post and want to change it. I think that having a version history is far more helpful than not. 

I do not want blank messages to appear. Let's agree that we have a business rule that blank messages are not permitted. If you do not agree then please convince me that we should allow a blank message. Once we agree then we can modify the system so it performs as per business rule.

**Comment by brendanheywood** [comment]
> Maybe we can combine the edit with the versions and delete all in one menu. What do you think?

+1 Is this a process or an api call?

Yup we are on the same page with everything

**Comment by scd** [comment]
I don't think there is any more to do with this one
